-- script to generate Canada exposure table

DROP TABLE IF EXISTS psra.BC_exposure;


-- create table
CREATE TABLE psra.BC_exposure(
    PRIMARY KEY (id),
    id varchar,
    lon float,
    lat float,
    taxonomy varchar,
    number float,
    structural float,
    nonstructural float,
    contents float,
    day float,
    night float,
    transit float,
    LandUse varchar,
    GenOcc varchar,
    HzOccType varchar,
    EqOccType varchar,
    BldgGen varchar,
    HzTaxon varchar,
    EqBldgType varchar,
    EqDesLev varchar,
    sauid varchar,
    dauid varchar,
    adauid varchar,
    fsauid varchar,
    csduid varchar,
    cduid varchar,
    SAC varchar,
    pruid varchar,
    csdname varchar,
    cdname varchar,
    ername varchar,
    prname varchar

);

-- import exposure from csv
COPY psra.BC_exposure (id, lon, lat, taxonomy, number, structural, nonstructural, contents, day, night, transit, LandUse, GenOcc, hzOccType, EqOccType, BldgGen, hzTaxon, EqBldgType, EqDesLev, sauid, dauid, adauid, fsauid, csduid, cduid, SAC, pruid, csdname, cdname, ername, prname)
    FROM 'C:\GitHub\opendrr-data-store\sample-datasets\scenario-risk\model-inputs\BC.csv'
        WITH 
          DELIMITER AS ','
          CSV HEADER ;


-- add geometries field to enable PostGIS (WGS1984 SRID = 4326)
ALTER TABLE psra.BC_exposure ADD COLUMN geom geometry(Point,4326);
UPDATE psra.BC_exposure SET geom = st_setsrid(st_makepoint(lon,lat),4326);


-- create spatial index
CREATE INDEX BC_exposure_idx
ON psra.BC_exposure using GIST (geom);


