-- script to generate Canada exposure table

DROP TABLE IF EXISTS lut.census_2016_canada_v2;

-- create table
CREATE TABLE lut.census_2016_canada_v2(
    PRIMARY KEY(SAUID),
    OID varchar,
    SAUID varchar,
    Lon float,
    Lat float,
    DAUID varchar,
    DAUID_t varchar,
    ADAUID varchar,
    FSAUID varchar,
    CSDUID varchar,
    CSDName varchar,
    CDUID varchar,
    CDName varchar,
    SACTYPE varchar,
    ERUID varchar,
    ERName varchar,
    PRUID varchar,
    PRName varchar,
    LandUse varchar,
    BldgNum float,
    CostAsset float,
    PopNight float,
    CensusPop float,
    CensusBldg float,
    CensusDU float,
    Area_km2 float,
    Area_ha float,
    RES_LD float,
    RES_MD float,
    RES_HD float,
    COMM float,
    IND float,
    CIVIC float,
    AGR float,
    CensusPopI float,
    Pop_Dens float,
    Pop_Ha float,
    Bus_Ha float,
    Pre_1975 float,
    Renter float,
    Hshld_NSui float,
    Hshld_Mntn float,
    Hshld_Mn_1 float,
    Pub_Trans float,
    Vis_Min float,
    Imm_LT5 float,
    Indigenous float,
    Age_GT65 float,
    Age_LT6 float,
    Age_Median float,
    NoSec_Scho float,
    Fam_GT5 float,
    LonePar3Ki float,
    Live_Alone float,
    No_EngFr float,
    Moved_LT1 float,
    NoWrkPlace float,
    Shltr_GT30 float,
    Inc_LowDec float,
    Unemployed float,
    Work_Partt float,
    Work_None float,
    Employ_Inc float,
    Inc_Hshld float,
    Inc_Indv float,
    Retail_Job float,
    Health_Job float

);

-- import exposure from csv
COPY lut.census_2016_canada_v2 (OID, SAUID, Lon, Lat, DAUID, DAUID_t, ADAUID, FSAUID, CSDUID, CSDName, CDUID, CDName, SACTYPE, ERUID, ERName, PRUID, PRName, LandUse, BldgNum, CostAsset, PopNight, CensusPop, 
CensusBldg, CensusDU, Area_km2, Area_ha, RES_LD, RES_MD, RES_HD, COMM, IND, CIVIC, AGR, CensusPopI, Pop_Dens, Pop_Ha, Bus_Ha, Pre_1975, Renter, Hshld_NSui, Hshld_Mntn, Hshld_Mn_1, Pub_Trans, Vis_Min, Imm_LT5,
 Indigenous, Age_GT65, Age_LT6, Age_Median, NoSec_Scho, Fam_GT5, LonePar3Ki, Live_Alone, No_EngFr, Moved_LT1, NoWrkPlace, Shltr_GT30, Inc_LowDec, Unemployed, Work_Partt, Work_None, Employ_Inc, Inc_Hshld, 
 Inc_Indv, Retail_Job, Health_Job)
    FROM 'C:\workspace\human-settlement-national\2_census-2016-canada.csv'
        WITH 
          DELIMITER AS ','
          CSV HEADER ;


/*
-- add geometries field to enable PostGIS (WGS1984 SRID = 4326)
ALTER TABLE psra.canada_exposure ADD COLUMN geom geometry(Point,4326);
UPDATE psra.canada_exposure SET geom = st_setsrid(st_makepoint(lon,lat),4326);

-- create spatial index
CREATE INDEX Canada_exposure_idx
ON psra.Canada_exposure using GIST (geom);

*/



