-- create physical exposure indicators
DROP VIEW IF EXISTS results.canada_exposure_replacement_cost CASCADE;
CREATE VIEW results.canada_exposure_replacement_cost AS 

-- 2.0 Physical Exposure
-- 2.1 Buildings
-- 2.1.3 Replacement Cost
SELECT 
a.id AS "AssetID",
CAST(a.structural AS NUMERIC) AS "StrCost",
CAST(a.nonstructural AS NUMERIC) AS "NStrCost",
CAST(a.contents AS NUMERIC) AS "ContCost",
CAST(a.structural + a.nonstructural + a.contents AS NUMERIC) AS "AssetCost",
CAST(a.structural + a.nonstructural AS NUMERIC) AS "BldgCost",
CAST(b."CAD_RetrofitCost_Bldg" AS NUMERIC) AS "RetrofitCost",
a.geom

FROM psra.canada_exposure a
LEFT JOIN lut.retrofit_costs b ON a.eqbldgtype = b."Eq_BldgType";