-- create scenario risk building indicators all
DROP VIEW IF EXISTS results.dsra_sim6p8_cr2022_rlz_0_b0_casualties_agg_view;
CREATE VIEW results.dsra_sim6p8_cr2022_rlz_0_b0_casualties_agg_view AS 

-- 4.0 Earthquake Risk
-- 4.3 Afected People
-- 4.3.1 Casualties
SELECT
b.sauid AS "Sauid",
f.source_type AS "Source_Type",
f.rupture_name AS "Rupture_Name",
f.magnitude AS "Magnitude",
'b0' AS "Retrofit",
SUM(h.censuspop) AS "CensusPop",
SUM(a."sL_Fatalities_b0") AS "sL_Fatality",
SUM(a."sC_CasDayL1_b0") AS "sC_CasDay_min",
SUM(a."sC_CasDayL2_b0") AS "sC_CasDay_mod",
SUM(a."sC_CasDayL3_b0") AS "sC_CasDay_ser",
SUM(a."sC_CasDayL4_b0") AS "sC_CasDay_crit",
SUM(a."sC_CasNightL1_b0") AS "sC_CasNit_min",
SUM(a."sC_CasNightL2_b0") AS "sC_CasNit_mod",
SUM(a."sC_CasNightL3_b0") AS "sC_CasNit_ser",
SUM(a."sC_CasNightL4_b0") AS "sC_CasNit_crit",
SUM(a."sC_CasTransitL1_b0") AS "sC_CasTrn_min",
SUM(a."sC_CasTransitL2_b0") AS "sC_CasTrn_mod",
SUM(a."sC_CasTransitL3_b0") AS "sC_CasTrn_ser",
SUM(a."sC_CasTransitL4_b0") AS "sC_CasTrn_crit",
g.geom AS "geom_poly",
g.geompoint AS "geom_point"

FROM dsra.dsra_sim6p8_cr2022_rlz_0 a
LEFT JOIN psra.canada_exposure b ON a."AssetID" = b.id 
--LEFT JOIN lut.retrofit_costs c ON b.eqbldgtype = c."Eq_BldgType"
--LEFT JOIN lut.vs30_bc_site_model_xref d ON a."AssetID" = d.id
--LEFT JOIN lut.gmfdata_sitemesh_sim6p8_cr2022_37_xref e on b.id = e.id
LEFT JOIN ruptures.rupture_table f on f.rupture_name = a."Rupture_Abbr"
LEFT JOIN boundaries."Geometry SAUID" g on b.sauid = g."SAUIDt"
LEFT JOIN lut.census_2016_canada h on b.sauid = h.sauidt
GROUP BY b.sauid, g.geom, g.geompoint, f.source_type, f.rupture_name, f.magnitude;