-- create multi hazard indicators
DROP VIEW IF EXISTS results.mh_intensity_wildfire_intensity CASCADE;
CREATE VIEW results.mh_intensity_wildfire_intensity AS 

-- 3.0 Natural Hazards
-- 8.1 Wildfire Hazard
-- 8.1.1 Wildfire Intensity
SELECT 
a.sauidt AS "Sauid",
CAST(a.fire AS NUMERIC) AS "Fire",
COALESCE(CAST((a.fire - (SELECT fire_min FROM lut.mh_intensity_canada_minmax))/NULLIF((SELECT fire_max FROM lut.mh_intensity_canada_minmax) - (SELECT fire_min FROM lut.mh_intensity_canada_minmax),0) AS NUMERIC),0) AS "Firen",
b.geom AS "geom_poly",
b.geompoint AS "geom_point"

FROM lut.mh_intensity_canada a
LEFT JOIN boundaries."Geometry SAUID" b on a.sauidt = b."SAUIDt";