-- create scenario risk building indicators for Scenario Damage Bldg
DROP VIEW IF EXISTS results.dsra_sim6p8_cr2022_rlz_0_b0_scenario_damage_bldg;
CREATE VIEW results.dsra_sim6p8_cr2022_rlz_0_b0_scenario_damage_bldg AS 

-- 3.0 Scenario Risk
-- 3.1 scenario Damage_Bldg
SELECT 
a."AssetID",
a."Rupture_Abbr",    --"Rupture Abbreviation"
f.magnitude AS "Source_Mag",  --"Rupture Source and Magnitude", hardcoded for now until we figure out how to parse
'b0' AS "Retrofit_Level",  --"Retrofit Level", 
a."Realization" AS "RealizationID", 
a."sD_None_b0" AS "sD_None",   --"No Damage"
a."sD_None_stdv_b0" AS "sD_None_stdv",   --"No Damage (stdv)"
a."sD_Slight_b0" AS "sD_Slight",   --"Slight Damage"
a."sD_Slight_stdv_b0" AS "sD_Slight_stdv",   --"Slight Damage (stdv)"
a."sD_Moderate_b0" AS "sD_Moderate",   --"Moderate Damage"
a."sD_Moderate_stdv_b0" AS "sD_Moderate_stdv",   --"Moderate Damage (stdv)"
a."sD_Extensive_b0" AS "sD_Extensive",   --"Extensive Damage"
a."sD_Extensive_stdv_b0" AS "sD_Extensive_stdv",   --"Extensive Damage (stdv)"
a."sD_Complete_b0" AS "sD_Complete",   --"Complete Damage"
a."sD_Complete_stdv_b0" AS "sD_Complete_stdv",   --"Complete_Damage (stdv)"
a."sD_Collapse_b0" AS "sD_Collapse", --"Collapse Probability"
b.geom

FROM dsra.dsra_sim6p8_cr2022_rlz_0 a
LEFT JOIN psra.bc_exposure b ON a."AssetID" = b.id 
LEFT JOIN lut.retrofit_costs c ON b.eqbldgtype = c.eq_bldg_type
LEFT JOIN lut.vs30_bc_site_model_xref d ON a."AssetID" = d.id
LEFT JOIN lut.gmfdata_sitemesh_sim6p8_cr2022_37_xref e on b.id = e.id
LEFT JOIN ruptures.rupture_table f on f.rupture_name = a."Rupture_Abbr";