-- create scenario risk building indicators for Scenario Shakemap
DROP VIEW IF EXISTS results.dsra_sim6p8_cr2022_rlz_0_b0_scenario_loss_bldg;
CREATE VIEW results.dsra_sim6p8_cr2022_rlz_0_b0_scenario_loss_bldg AS 

-- 3.0 Scenario Risk
-- 3.3 Scenario Loss_Bldg
SELECT 
a."AssetID",
a."Rupture_Abbr",    --"Rupture Abbreviation"
f.magnitude AS "Source_Mag",  --"Rupture Source and Magnitude", hardcoded for now until we figure out how to parse
'b0' AS "Retrofit_Level",  --"Retrofit Level", 
a."Realization" AS "RealizationID", 
a."sL_Str_b0" + a."sL_NStr_b0" + a."sL_Cont_b0" AS "sL_Asset",  --"Asset Loss"
a."sL_Str_b0" + a."sL_NStr_b0" AS "sL_Bldg",    --"Building Loss"
(a."sL_Str_b0" + a."sL_NStr_b0") / (b.structural + b.nonstructural) AS "sL_BldgRatio",  --"Building Loss Ratio"
a."sL_Str_b0" AS "sL_Str",  --"Structural Loss"
a."sL_Str_stdv_b0" AS "sL_Str_stdv",    --"Structural Loss (stdv)"
a."sL_NStr_b0" AS "sL_NStr",  --"Nonstructural Loss"
a."sL_NStr_stdv_b0" AS "sL_NStr_stdv",    --"Nonstructural Loss (stdv)"
a."sL_Cont_b0" AS "sL_Cont",  --"Content Loss"
a."sL_Cont_stdv_b0" AS "sL_Cont_stdv",    --"Content Loss (stdv)"
a."sL_Fatalities_b0" AS "sL_Fatality", --"Fatality"
a."sL_Fatalities_stdv_b0" AS "sL_Fatality_stdv",    --"Fatality (stdv)"
b.geom

FROM dsra.dsra_sim6p8_cr2022_rlz_0 a
LEFT JOIN psra.bc_exposure b ON a."AssetID" = b.id 
LEFT JOIN lut.retrofit_costs c ON b.eqbldgtype = c.eq_bldg_type
LEFT JOIN lut.vs30_bc_site_model_xref d ON a."AssetID" = d.id
LEFT JOIN lut.gmfdata_sitemesh_sim6p8_cr2022_37_xref e on b.id = e.id
LEFT JOIN ruptures.rupture_table f on f.rupture_name = a."Rupture_Abbr";

FROM results.dsra_sim6p8_cr2022_rlz_0_b0_all;