-- create scenario risk building indicators for building archetype

DROP VIEW IF EXISTS results.dsra_sim6p8_cr2022_rlz_0_b0_building_archetype;
CREATE VIEW results.dsra_sim6p8_cr2022_rlz_0_b0_building_archetype AS 

-- 1.0 physical exposure
-- 1.1 building archetypes
SELECT 
a."AssetID",
b.sauid AS "Sauid",    --"Settled Area",
b.lon AS "Asset_Lon",     --"Longitude"
b.lat AS "Asset_Lat",      --"Latitude"
b.taxonomy AS  "Taxonomy",   --"Building Taxonomy"
b.number AS "BldgNum",  --"Building Number"
b.genocc AS "Occ_General",  --"General Occupancy",
b.eqocctype AS "Occ_Specific",  --"Specific Occupancy"
b.eqbldgtype AS "Type_Specific",    --"General Construction"
b.eqdeslev AS "Design_Level",   --"Sesmic Design Level"
b.structural AS "StrCost",  --"Structural Cost"
b.nonstructural AS "NStrCost",  --"Nonstructural Cost"
b.contents AS "ContCost",   --"Content Cost"
b.structural + b.nonstructural + b.contents AS "AssetCost", 
b.structural + b.nonstructural AS "BldgCost",   
c.building_retrofit_cost_cad AS "Retrofit_Cost",
c.bldgarea_ft2 AS "BldgArea_ft2",
b.day AS "DayPop", --"Daytime Population"
b.night AS "NightPop",  --"Nighttime Population"
b.transit AS "TransitPop",  --"In Transit Population"
b.geom

FROM dsra.dsra_sim6p8_cr2022_rlz_0 a
LEFT JOIN psra.bc_exposure b ON a."AssetID" = b.id 
LEFT JOIN lut.retrofit_costs c ON b.eqbldgtype = c.eq_bldg_type
LEFT JOIN lut.vs30_bc_site_model_xref d ON a."AssetID" = d.id
LEFT JOIN lut.gmfdata_sitemesh_sim6p8_cr2022_37_xref e on b.id = e.id
LEFT JOIN ruptures.rupture_table f on f.rupture_name = a."Rupture_Abbr";