-- create scenario risk building indicators for Scenario Rupture
DROP VIEW IF EXISTS results.dsra_sim6p8_cr2022_rlz_0_b0_scenario_rupture;
CREATE VIEW results.dsra_sim6p8_cr2022_rlz_0_b0_scenario_rupture AS 

-- 2.0 Scenario Hazard
-- 2.1 scenario Rupture

SELECT 
a."AssetID",
f.source_type AS "Source_Type", --"Source Type"
f.rupture_name AS "Rupture_Name",    --"Earthquake Scenario"
f.magnitude AS "Magnitude",   --"Moment Magnitude"
f.rake AS "Rake",    --"Rupture Direction"
f.lon AS "Hypo_Lon",    --"Hypocentre longitude"
f.lat AS "Hypo_Lat",    --"Hypocentre latidue"
f.depth AS "Hypo_Depth",   --"Hypocentre depth"
d."vs_lon" AS "vs30_Lon",    --"Vs30 Longitude"
d."vs_lat" AS "vs30_Lat",    --"Vs30 Latitude"
d.vs30 AS "vs30",    --"Vs30 Shear Wave Velocity"
e.site_id AS "SiteID",  --"Site ID"
e.lon AS "SiteID_Lon",  --"Site Longitude"
e.lat AS "SiteID_Lat",  --"Site Latitude"
a."Realization" AS "Realization", --"Branch Number"
a."gmpe_Model" AS "gmpe_Model",  --"Ground Motion Model"
a."Weight" AS "Weight",  --"Branch Weighting"
b.geom

FROM dsra.dsra_sim6p8_cr2022_rlz_0 a
LEFT JOIN psra.bc_exposure b ON a."AssetID" = b.id 
LEFT JOIN lut.retrofit_costs c ON b.eqbldgtype = c.eq_bldg_type
LEFT JOIN lut.vs30_bc_site_model_xref d ON a."AssetID" = d.id
LEFT JOIN lut.gmfdata_sitemesh_sim6p8_cr2022_37_xref e on b.id = e.id
LEFT JOIN ruptures.rupture_table f on f.rupture_name = a."Rupture_Abbr";