-- create scenario risk building indicators
DROP VIEW IF EXISTS results.dsra_sim6p8_cr2022_rlz_0_r1_all;
CREATE VIEW results.dsra_sim6p8_cr2022_rlz_0_r1_all AS 

SELECT 
a."AssetID",
b.sauid AS "Sauid",    --"Settled Area",
b.lon AS "Asset_Lon",     --"Longitude"
b.lat AS "Asset_Lat",      --"Latitude"
b.taxonomy AS  "Taxonomy",   --"Building Taxonomy"
b.number AS "BldgNum",  --"Building Number"
b.genocc AS "Occ_General",  --"General Occupancy",
b.eqocctype AS "Occ_Specific",  --"Specific Occupancy"
b.eqbldgtype AS "Type_Specific",    --"General Construction"
b.eqdeslev AS "Design_Level",   --"Sesmic Design Level"
b.structural AS "StrCost",  --"Structural Cost"
b.nonstructural AS "NStrCost",  --"Nonstructural Cost"
b.contents AS "ContCost",   --"Content Cost"
b.structural + b.nonstructural + b.contents AS "AssetCost", 
b.structural + b.nonstructural AS "BldgCost",   
c.building_retrofit_cost_cad AS "Retrofit_Cost",
c.bldgarea_ft2 AS "BldgArea_ft2",
b.day AS "DayPop", --"Daytime Population"
b.night AS "NightPop",  --"Nighttime Population"
b.transit AS "TransitPop",  --"In Transit Population"

-- 2.0 Scenario Hazard
-- 2.1 scenario Rupture
f.source_type AS "Source_Type", --"Source Type"
f.rupture_name AS "Rupture_Name",    --"Earthquake Scenario"
f.magnitude AS "Magnitude",   --"Moment Magnitude"
f.rake AS "Rake",    --"Rupture Direction"
f.lon AS "Hypo_Lon",    --"Hypocentre longitude"
f.lat AS "Hypo_Lat",    --"Hypocentre latidue"
f.depth AS "Hypo_Depth",   --"Hypocentre depth"
d."vs_lon" AS "vs30_Lon",    --"Vs30 Longitude"
d."vs_lat" AS "vs30_Lat",    --"Vs30 Latitude"
d.vs30 AS "vs30",    --"Vs30 Shear Wave Velocity"
e.site_id AS "SiteID",  --"Site ID"
e.lon AS "SiteID_Lon",  --"Site Longitude"
e.lat AS "SiteID_Lat",  --"Site Latitude"
a."Realization" AS "Realization", --"Branch Number"
a."gmpe_Model" AS "gmpe_Model",  --"Ground Motion Model"
a."Weight" AS "Weight",  --"Branch Weighting"

-- scenario shakemap
e."event_id" AS "EventID",	--"Rupture Event ID"
e."gmv_pga" AS "PGV", --"Peak Ground Velocity"
e."gmv_pgv" AS "PGA", --"Peak Ground Acceleration"
e."gmv_SA(0.2)" AS "SA_0p2",    --"Spectral Acceleration (0.2s)" - change source to reflect 0.1 later
e."gmv_SA(0.3)" AS "SA_0p3",   --"Spectral Acceleration (0.3s)" - change source to reflect 0.2 later
e."gmv_SA(0.6)" AS "SA_0p6",   --"Spectral Acceleration (0.6s)" - change source to reflect 0.6 later
e."gmv_SA(1.0)" AS "SA_1p0",   --"Spectral Acceleration (1.0s)" - change source to reflect 1.0 later
0 AS "SA_2p0",  --"Spectral Acceleration (2.0s)" - change source to reflect 2.0 later

-- 3.0 Scenario Risk
-- 3.1 scenario Damage_Bldg
a."Rupture_Abbr",    --"Rupture Abbreviation"
f.magnitude AS "Source_Mag",  --"Rupture Source and Magnitude", hardcoded for now until we figure out how to parse
'r1' AS "Retrofit_Level",  --"Retrofit Level", 
a."Realization" AS "RealizationID", 
a."sD_None_r1" AS "sD_None",   --"No Damage"
a."sD_None_stdv_r1" AS "sD_None_stdv",   --"No Damage (stdv)"
a."sD_Slight_r1" AS "sD_Slight",   --"Slight Damage"
a."sD_Slight_stdv_r1" AS "sD_Slight_stdv",   --"Slight Damage (stdv)"
a."sD_Moderate_r1" AS "sD_Moderate",   --"Moderate Damage"
a."sD_Moderate_stdv_r1" AS "sD_Moderate_stdv",   --"Moderate Damage (stdv)"
a."sD_Extensive_r1" AS "sD_Extensive",   --"Extensive Damage"
a."sD_Extensive_stdv_r1" AS "sD_Extensive_stdv",   --"Extensive Damage (stdv)"
a."sD_Complete_r1" AS "sD_Complete",   --"Complete Damage"
a."sD_Complete_stdv_r1" AS "sD_Complete_stdv",   --"Complete_Damage (stdv)"
a."sD_Collapse_r1" AS "sD_Collapse", --"Collapse Probability"

-- 3.2 Scenario Consequence_Bldg
a."sC_Repair_r1" AS "sC_Repair",   --"Repair Time"
a."sC_Construxn_r1" AS "sC_Construxn",    --"Reconstruction Time"
a."sC_Downtime_r1" AS "sC_Downtime", --"Building Downtime"
a."sC_CasDayL1_r1" AS "sC_CasDayL1",    --"Minor Injury (Daytime)"
a."sC_CasDayL2_r1" AS "sC_CasDayL2",    --"Moderate Injury (Daytime)"
a."sC_CasDayL3_r1" AS "sC_CasDayL3",    --"Serious Injury (Daytime)"
a."sC_CasDayL4_r1" AS "sC_CasDayL4",    --"Critical Injury (Daytime)"
a."sC_CasNightL1_r1" AS "sC_CasNightL1",    --"Minor Injury (Nighttime)"
a."sC_CasNightL2_r1" AS "sC_CasNightL2",    --"Moderate Injury (Nighttime)"
a."sC_CasNightL3_r1" AS "sC_CasNightL3",    --"Serious Injury (Nighttime)"
a."sC_CasNightL4_r1" AS "sC_CasNightL4",    --"Critical Injury (Nighttime)"
a."sC_CasTransitL1_r1" AS "sC_CasTransitL1", --"Minor Injury (In Transit)"
a."sC_CasTransitL2_r1" AS "sC_CasTransitL2", --"Moderate Injury (In Transit)"
a."sC_CasTransitL3_r1" AS "sC_CasTransitL3", --"Serious Injury (In Transit)"
a."sC_CasTransitL4_r1" AS "sC_CasTransitL4", --"Critical Injury (In Transit)"
a."sC_DisplRes_3_r1" AS "sC_Displ_Res_3",    --"3-Day Residential Displacement"
a."sC_DisplRes_30_r1" AS "sC_Displ_Res_30",    --"30-Day Residential Displacement"
a."sC_DisplRes_90_r1" AS "sC_Displ_Res_90",    --"90-Day Residential Displacement"
a."sC_DisplRes_360_r1" AS "sC_Displ_Res_360",    --"360-Day Residential Displacement"
a."sC_DisrupEmpl_30_r1" AS "sC_DisrupEmpl_30",    --"30-Day Employee Disruption"
a."sC_DisrupEmpl_90_r1" AS "sC_DisrupEmpl_90",    --"90-Day Employee Disruption
a."sC_DisrupEmpl_180_r1" AS "sC_DisrupEmpl_180",    --"180-Day Employee Disruption
a."sC_DisrupEmpl_360_r1" AS "sC_DisrupEmpl_360",    --"360-Day Employee Disruption
a."sC_DebrisBW_r1" AS "sC_DebrisBW",
a."sC_DebrisC_r1" AS "sC_DebrisC",

-- 3.3 Scenario Loss_Bldg
a."sL_Str_r1" + a."sL_NStr_r1" + a."sL_Cont_r1" AS "sL_Asset",  --"Asset Loss"
a."sL_Str_r1" + a."sL_NStr_r1" AS "sL_Bldg",    --"Building Loss"
(a."sL_Str_r1" + a."sL_NStr_r1") / (b.structural + b.nonstructural) AS "sL_BldgRatio",  --"Building Loss Ratio"
a."sL_Str_r1" AS "sL_Str",  --"Structural Loss"
a."sL_Str_stdv_r1" AS "sL_Str_stdv",    --"Structural Loss (stdv)"
a."sL_NStr_r1" AS "sL_NStr",  --"Nonstructural Loss"
a."sL_NStr_stdv_r1" AS "sL_NStr_stdv",    --"Nonstructural Loss (stdv)"
a."sL_Cont_r1" AS "sL_Cont",  --"Content Loss"
a."sL_Cont_stdv_r1" AS "sL_Cont_stdv",    --"Content Loss (stdv)"
a."sL_Fatalities_r1" AS "sL_Fatality", --"Fatality"
a."sL_Fatalities_stdv_r1" AS "sL_Fatality_stdv",    --"Fatality (stdv)"
b.geom

FROM dsra.dsra_sim6p8_cr2022_rlz_0 a
LEFT JOIN psra.bc_exposure b ON a."AssetID" = b.id 
LEFT JOIN lut.retrofit_costs c ON b.eqbldgtype = c.eq_bldg_type
LEFT JOIN lut.vs30_bc_site_model_xref d ON a."AssetID" = d.id
LEFT JOIN lut.gmfdata_sitemesh_sim6p8_cr2022_37_xref e on b.id = e.id
LEFT JOIN ruptures.rupture_table f on f.rupture_name = a."Rupture_Abbr";


-- create scenario risk building indicators for building archetype
DROP VIEW IF EXISTS results.dsra_sim6p8_cr2022_rlz_0_r1_building_archetype;
CREATE VIEW results.dsra_sim6p8_cr2022_rlz_0_r1_building_archetype AS 

-- 1.0 physical exposure
-- 1.1 building archetypes
SELECT 
a."AssetID",
b.sauid AS "Sauid",    --"Settled Area",
b.lon AS "Asset_Lon",     --"Longitude"
b.lat AS "Asset_Lat",      --"Latitude"
b.taxonomy AS  "Taxonomy",   --"Building Taxonomy"
b.number AS "BldgNum",  --"Building Number"
b.genocc AS "Occ_General",  --"General Occupancy",
b.eqocctype AS "Occ_Specific",  --"Specific Occupancy"
b.eqbldgtype AS "Type_Specific",    --"General Construction"
b.eqdeslev AS "Design_Level",   --"Sesmic Design Level"
b.structural AS "StrCost",  --"Structural Cost"
b.nonstructural AS "NStrCost",  --"Nonstructural Cost"
b.contents AS "ContCost",   --"Content Cost"
b.structural + b.nonstructural + b.contents AS "AssetCost", 
b.structural + b.nonstructural AS "BldgCost",   
c.building_retrofit_cost_cad AS "Retrofit_Cost",
c.bldgarea_ft2 AS "BldgArea_ft2",
b.day AS "DayPop", --"Daytime Population"
b.night AS "NightPop",  --"Nighttime Population"
b.transit AS "TransitPop",  --"In Transit Population"
b.geom

FROM dsra.dsra_sim6p8_cr2022_rlz_0 a
LEFT JOIN psra.bc_exposure b ON a."AssetID" = b.id 
LEFT JOIN lut.retrofit_costs c ON b.eqbldgtype = c.eq_bldg_type
LEFT JOIN lut.vs30_bc_site_model_xref d ON a."AssetID" = d.id
LEFT JOIN lut.gmfdata_sitemesh_sim6p8_cr2022_37_xref e on b.id = e.id
LEFT JOIN ruptures.rupture_table f on f.rupture_name = a."Rupture_Abbr";


-- create scenario risk building indicators for Scenario Rupture
DROP VIEW IF EXISTS results.dsra_sim6p8_cr2022_rlz_0_r1_scenario_rupture;
CREATE VIEW results.dsra_sim6p8_cr2022_rlz_0_r1_scenario_rupture AS 

-- 2.0 Scenario Hazard
-- 2.1 scenario Rupture

SELECT 
a."AssetID",
f.source_type AS "Source_Type", --"Source Type"
f.rupture_name AS "Rupture_Name",    --"Earthquake Scenario"
f.magnitude AS "Magnitude",   --"Moment Magnitude"
f.rake AS "Rake",    --"Rupture Direction"
f.lon AS "Hypo_Lon",    --"Hypocentre longitude"
f.lat AS "Hypo_Lat",    --"Hypocentre latidue"
f.depth AS "Hypo_Depth",   --"Hypocentre depth"
d."vs_lon" AS "vs30_Lon",    --"Vs30 Longitude"
d."vs_lat" AS "vs30_Lat",    --"Vs30 Latitude"
d.vs30 AS "vs30",    --"Vs30 Shear Wave Velocity"
e.site_id AS "SiteID",  --"Site ID"
e.lon AS "SiteID_Lon",  --"Site Longitude"
e.lat AS "SiteID_Lat",  --"Site Latitude"
a."Realization" AS "Realization", --"Branch Number"
a."gmpe_Model" AS "gmpe_Model",  --"Ground Motion Model"
a."Weight" AS "Weight",  --"Branch Weighting"
b.geom

FROM dsra.dsra_sim6p8_cr2022_rlz_0 a
LEFT JOIN psra.bc_exposure b ON a."AssetID" = b.id 
LEFT JOIN lut.retrofit_costs c ON b.eqbldgtype = c.eq_bldg_type
LEFT JOIN lut.vs30_bc_site_model_xref d ON a."AssetID" = d.id
LEFT JOIN lut.gmfdata_sitemesh_sim6p8_cr2022_37_xref e on b.id = e.id
LEFT JOIN ruptures.rupture_table f on f.rupture_name = a."Rupture_Abbr";


-- create scenario risk building indicators for Scenario Shakemap
DROP VIEW IF EXISTS results.dsra_sim6p8_cr2022_rlz_0_r1_scenario_shakemap;
CREATE VIEW results.dsra_sim6p8_cr2022_rlz_0_r1_scenario_shakemap AS 

-- 2.0 Scenario Hazard
-- scenario shakemap
SELECT 
a."AssetID",
e."event_id" AS "EventID",	--"Rupture Event ID"
e."gmv_pga" AS "PGV", --"Peak Ground Velocity"
e."gmv_pgv" AS "PGA", --"Peak Ground Acceleration"
e."gmv_SA(0.2)" AS "SA_0p2",    --"Spectral Acceleration (0.2s)" - change source to reflect 0.1 later
e."gmv_SA(0.3)" AS "SA_0p3",   --"Spectral Acceleration (0.3s)" - change source to reflect 0.2 later
e."gmv_SA(0.6)" AS "SA_0p6",   --"Spectral Acceleration (0.6s)" - change source to reflect 0.6 later
e."gmv_SA(1.0)" AS "SA_1p0",   --"Spectral Acceleration (1.0s)" - change source to reflect 1.0 later
0 AS "SA_2p0",  --"Spectral Acceleration (2.0s)" - change source to reflect 2.0 later
b.geom

FROM dsra.dsra_sim6p8_cr2022_rlz_0 a
LEFT JOIN psra.bc_exposure b ON a."AssetID" = b.id 
LEFT JOIN lut.retrofit_costs c ON b.eqbldgtype = c.eq_bldg_type
LEFT JOIN lut.vs30_bc_site_model_xref d ON a."AssetID" = d.id
LEFT JOIN lut.gmfdata_sitemesh_sim6p8_cr2022_37_xref e on b.id = e.id
LEFT JOIN ruptures.rupture_table f on f.rupture_name = a."Rupture_Abbr";


-- create scenario risk building indicators for Scenario Damage Bldg
DROP VIEW IF EXISTS results.dsra_sim6p8_cr2022_rlz_0_r1_scenario_damage_bldg;
CREATE VIEW results.dsra_sim6p8_cr2022_rlz_0_r1_scenario_damage_bldg AS 

-- 3.0 Scenario Risk
-- 3.1 scenario Damage_Bldg
SELECT 
a."AssetID",
a."Rupture_Abbr",    --"Rupture Abbreviation"
f.magnitude AS "Source_Mag",  --"Rupture Source and Magnitude", hardcoded for now until we figure out how to parse
'r1' AS "Retrofit_Level",  --"Retrofit Level", 
a."Realization" AS "RealizationID", 
a."sD_None_r1" AS "sD_None",   --"No Damage"
a."sD_None_stdv_r1" AS "sD_None_stdv",   --"No Damage (stdv)"
a."sD_Slight_r1" AS "sD_Slight",   --"Slight Damage"
a."sD_Slight_stdv_r1" AS "sD_Slight_stdv",   --"Slight Damage (stdv)"
a."sD_Moderate_r1" AS "sD_Moderate",   --"Moderate Damage"
a."sD_Moderate_stdv_r1" AS "sD_Moderate_stdv",   --"Moderate Damage (stdv)"
a."sD_Extensive_r1" AS "sD_Extensive",   --"Extensive Damage"
a."sD_Extensive_stdv_r1" AS "sD_Extensive_stdv",   --"Extensive Damage (stdv)"
a."sD_Complete_r1" AS "sD_Complete",   --"Complete Damage"
a."sD_Complete_stdv_r1" AS "sD_Complete_stdv",   --"Complete_Damage (stdv)"
a."sD_Collapse_r1" AS "sD_Collapse", --"Collapse Probability"
b.geom

FROM dsra.dsra_sim6p8_cr2022_rlz_0 a
LEFT JOIN psra.bc_exposure b ON a."AssetID" = b.id 
LEFT JOIN lut.retrofit_costs c ON b.eqbldgtype = c.eq_bldg_type
LEFT JOIN lut.vs30_bc_site_model_xref d ON a."AssetID" = d.id
LEFT JOIN lut.gmfdata_sitemesh_sim6p8_cr2022_37_xref e on b.id = e.id
LEFT JOIN ruptures.rupture_table f on f.rupture_name = a."Rupture_Abbr";


-- create scenario risk building indicators for Scenario Consequence Bldg
DROP VIEW IF EXISTS results.dsra_sim6p8_cr2022_rlz_0_r1_scenario_consequence_bldg;
CREATE VIEW results.dsra_sim6p8_cr2022_rlz_0_r1_scenario_consequence_bldg AS 

-- 3.0 Scenario Risk
-- 3.2 Scenario Consequence_Bldg
SELECT 
a."AssetID",
a."Rupture_Abbr",    --"Rupture Abbreviation"
f.magnitude AS "Source_Mag",  --"Rupture Source and Magnitude", hardcoded for now until we figure out how to parse
'r1' AS "Retrofit_Level",  --"Retrofit Level", 
a."Realization" AS "RealizationID", 
a."sC_Repair_r1" AS "sC_Repair",   --"Repair Time"
a."sC_Construxn_r1" AS "sC_Construxn",    --"Reconstruction Time"
a."sC_Downtime_r1" AS "sC_Downtime", --"Building Downtime"
a."sC_CasDayL1_r1" AS "sC_CasDayL1",    --"Minor Injury (Daytime)"
a."sC_CasDayL2_r1" AS "sC_CasDayL2",    --"Moderate Injury (Daytime)"
a."sC_CasDayL3_r1" AS "sC_CasDayL3",    --"Serious Injury (Daytime)"
a."sC_CasDayL4_r1" AS "sC_CasDayL4",    --"Critical Injury (Daytime)"
a."sC_CasNightL1_r1" AS "sC_CasNightL1",    --"Minor Injury (Nighttime)"
a."sC_CasNightL2_r1" AS "sC_CasNightL2",    --"Moderate Injury (Nighttime)"
a."sC_CasNightL3_r1" AS "sC_CasNightL3",    --"Serious Injury (Nighttime)"
a."sC_CasNightL4_r1" AS "sC_CasNightL4",    --"Critical Injury (Nighttime)"
a."sC_CasTransitL1_r1" AS "sC_CasTransitL1", --"Minor Injury (In Transit)"
a."sC_CasTransitL2_r1" AS "sC_CasTransitL2", --"Moderate Injury (In Transit)"
a."sC_CasTransitL3_r1" AS "sC_CasTransitL3", --"Serious Injury (In Transit)"
a."sC_CasTransitL4_r1" AS "sC_CasTransitL4", --"Critical Injury (In Transit)"
a."sC_DisplRes_3_r1" AS "sC_Displ_Res_3",    --"3-Day Residential Displacement"
a."sC_DisplRes_30_r1" AS "sC_Displ_Res_30",    --"30-Day Residential Displacement"
a."sC_DisplRes_90_r1" AS "sC_Displ_Res_90",    --"90-Day Residential Displacement"
a."sC_DisplRes_360_r1" AS "sC_Displ_Res_360",    --"360-Day Residential Displacement"
a."sC_DisrupEmpl_30_r1" AS "sC_DisrupEmpl_30",    --"30-Day Employee Disruption"
a."sC_DisrupEmpl_90_r1" AS "sC_DisrupEmpl_90",    --"90-Day Employee Disruption
a."sC_DisrupEmpl_180_r1" AS "sC_DisrupEmpl_180",    --"180-Day Employee Disruption
a."sC_DisrupEmpl_360_r1" AS "sC_DisrupEmpl_360",    --"360-Day Employee Disruption
a."sC_DebrisBW_r1" AS "sC_DebrisBW",
a."sC_DebrisC_r1" AS "sC_DebrisC",
b.geom

FROM dsra.dsra_sim6p8_cr2022_rlz_0 a
LEFT JOIN psra.bc_exposure b ON a."AssetID" = b.id 
LEFT JOIN lut.retrofit_costs c ON b.eqbldgtype = c.eq_bldg_type
LEFT JOIN lut.vs30_bc_site_model_xref d ON a."AssetID" = d.id
LEFT JOIN lut.gmfdata_sitemesh_sim6p8_cr2022_37_xref e on b.id = e.id
LEFT JOIN ruptures.rupture_table f on f.rupture_name = a."Rupture_Abbr";


-- create scenario risk building indicators for Scenario Shakemap
DROP VIEW IF EXISTS results.dsra_sim6p8_cr2022_rlz_0_r1_scenario_loss_bldg;
CREATE VIEW results.dsra_sim6p8_cr2022_rlz_0_r1_scenario_loss_bldg AS 

-- 3.0 Scenario Risk
-- 3.3 Scenario Loss_Bldg
SELECT 
a."AssetID",
a."Rupture_Abbr",    --"Rupture Abbreviation"
f.magnitude AS "Source_Mag",  --"Rupture Source and Magnitude", hardcoded for now until we figure out how to parse
'r1' AS "Retrofit_Level",  --"Retrofit Level", 
a."Realization" AS "RealizationID", 
a."sL_Str_r1" + a."sL_NStr_r1" + a."sL_Cont_r1" AS "sL_Asset",  --"Asset Loss"
a."sL_Str_r1" + a."sL_NStr_r1" AS "sL_Bldg",    --"Building Loss"
(a."sL_Str_r1" + a."sL_NStr_r1") / (b.structural + b.nonstructural) AS "sL_BldgRatio",  --"Building Loss Ratio"
a."sL_Str_r1" AS "sL_Str",  --"Structural Loss"
a."sL_Str_stdv_r1" AS "sL_Str_stdv",    --"Structural Loss (stdv)"
a."sL_NStr_r1" AS "sL_NStr",  --"Nonstructural Loss"
a."sL_NStr_stdv_r1" AS "sL_NStr_stdv",    --"Nonstructural Loss (stdv)"
a."sL_Cont_r1" AS "sL_Cont",  --"Content Loss"
a."sL_Cont_stdv_r1" AS "sL_Cont_stdv",    --"Content Loss (stdv)"
a."sL_Fatalities_r1" AS "sL_Fatality", --"Fatality"
a."sL_Fatalities_stdv_r1" AS "sL_Fatality_stdv",    --"Fatality (stdv)"
b.geom

FROM dsra.dsra_sim6p8_cr2022_rlz_0 a
LEFT JOIN psra.bc_exposure b ON a."AssetID" = b.id 
LEFT JOIN lut.retrofit_costs c ON b.eqbldgtype = c.eq_bldg_type
LEFT JOIN lut.vs30_bc_site_model_xref d ON a."AssetID" = d.id
LEFT JOIN lut.gmfdata_sitemesh_sim6p8_cr2022_37_xref e on b.id = e.id
LEFT JOIN ruptures.rupture_table f on f.rupture_name = a."Rupture_Abbr";