-- create scenario risk building indicators all
DROP VIEW IF EXISTS results.dsra_sim6p8_cr2022_rlz_0_b0_economic_loss CASCADE;
CREATE VIEW results.dsra_sim6p8_cr2022_rlz_0_b0_economic_loss AS 

-- 4.0 Earthquake Risk
-- 4.4 Economic Security
-- 4.4.1 Economic Loss
SELECT
a."AssetID",
a."Rupture_Abbr",
f.magnitude AS "Source_Mag",
'b0' AS "Retrofit_Level",
a."Realization" AS "RealizationID", 
a."sL_Str_b0" + a."sL_NStr_b0" + a."sL_Cont_b0" AS "sL_Asset",
a."sL_Str_b0" + a."sL_NStr_b0" AS "sL_Bldg",
COALESCE((a."sL_Str_b0" + a."sL_NStr_b0") / NULLIF((a."sL_Str_b0" + a."sL_NStr_b0" + a."sL_Cont_b0"),0),0) AS "sL_BldgRatio",
a."sL_Str_b0" AS "sL_Str",
a."sL_Str_stdv_b0" AS "sL_Str_stdv",
a."sL_NStr_b0" AS "sL_NStr",
a."sL_NStr_stdv_b0" AS "sL_NStr_stdv",
a."sL_Cont_b0" AS "sL_Cont",
a."sL_Cont_stdv_b0" AS "sL_Cont_stdv",
a."sL_Fatalities_b0" AS "sL_Fatality",
a."sL_Fatalities_stdv_b0" AS "sL_Fatality_stdv",
b.geom

FROM dsra.dsra_sim6p8_cr2022_rlz_0 a
LEFT JOIN psra.canada_exposure b ON a."AssetID" = b.id 
--LEFT JOIN lut.retrofit_costs c ON b.eqbldgtype = c."Eq_BldgType"
--LEFT JOIN lut.vs30_bc_site_model_xref d ON a."AssetID" = d.id
--LEFT JOIN lut.gmfdata_sitemesh_sim6p8_cr2022_37_xref e on b.id = e.id
LEFT JOIN ruptures.rupture_table f on f.rupture_name = a."Rupture_Abbr";