-- script to generate relationships other source tables and exposure table

-- building level
-- results_canada_exposure.canada_exposure_buildings_building_t
-- add pkey
ALTER TABLE results_canada_exposure.canada_exposure_buildings_building_t DROP CONSTRAINT IF EXISTS canada_exposure_buildings_building_t_pkey;
ALTER TABLE results_canada_exposure.canada_exposure_buildings_building_t ADD PRIMARY KEY("BldgID");

-- exposure.canada_exposure
ALTER TABLE results_canada_exposure.canada_exposure_buildings_building_t DROP CONSTRAINT IF EXISTS fk_canada_exposure_buildings_building_t_bldgid_canada_exposure;
ALTER TABLE results_canada_exposure.canada_exposure_buildings_building_t ADD CONSTRAINT fk_canada_exposure_buildings_building_t_bldgid_canada_exposure FOREIGN KEY ("BldgID") REFERENCES exposure.canada_exposure(id);

-- lut.retrofit_costs
ALTER TABLE results_canada_exposure.canada_exposure_buildings_building_t DROP CONSTRAINT IF EXISTS fk_canada_exposure_buildings_building_t_e_bldgtypes_retrofit_costs;
ALTER TABLE results_canada_exposure.canada_exposure_buildings_building_t ADD CONSTRAINT fk_canada_exposure_buildings_building_t_e_bldgtypes_retrofit_costs FOREIGN KEY ("E_BldgTypeS") REFERENCES lut.retrofit_costs("Eq_BldgType");



-- results_canada_exposure.canada_exposure_people_building_t
-- add pkey
ALTER TABLE results_canada_exposure.canada_exposure_people_building_t DROP CONSTRAINT IF EXISTS canada_exposure_people_building_t_pkey;
ALTER TABLE results_canada_exposure.canada_exposure_people_building_t ADD PRIMARY KEY("BldgID");

-- exposure.canada_exposure
ALTER TABLE results_canada_exposure.canada_exposure_people_building_t DROP CONSTRAINT IF EXISTS fk_canada_exposure_people_building_t_bldgid_canada_exposure;
ALTER TABLE results_canada_exposure.canada_exposure_people_building_t ADD CONSTRAINT fk_canada_exposure_people_building_t_bldgid_canada_exposure FOREIGN KEY ("BldgID") REFERENCES exposure.canada_exposure(id);



-- results_canada_exposure.canada_exposure_assets_building_t
-- add pkey
ALTER TABLE results_canada_exposure.canada_exposure_assets_building_t DROP CONSTRAINT IF EXISTS canada_exposure_assets_building_t_pkey;
ALTER TABLE results_canada_exposure.canada_exposure_assets_building_t ADD PRIMARY KEY("BldgID");

-- exposure.canada_exposure
ALTER TABLE results_canada_exposure.canada_exposure_assets_building_t DROP CONSTRAINT IF EXISTS fk_canada_exposure_assets_building_t_bldgid_canada_exposure;
ALTER TABLE results_canada_exposure.canada_exposure_assets_building_t ADD CONSTRAINT fk_canada_exposure_assets_building_t_bldgid_canada_exposure FOREIGN KEY ("BldgID") REFERENCES exposure.canada_exposure(id);



-- sauid
-- results_canada_exposure.canada_exposure_settled_area_sauid_t
 -- add pkey
ALTER TABLE results_canada_exposure.canada_exposure_settled_area_sauid_t DROP CONSTRAINT IF EXISTS canada_exposure_settled_area_sauid_t_pkey;
ALTER TABLE results_canada_exposure.canada_exposure_settled_area_sauid_t ADD PRIMARY KEY("Sauid");

-- exposure.canada_exposure
ALTER TABLE exposure.canada_exposure DROP CONSTRAINT IF EXISTS fk_canada_exposure_sauid_canada_exposure_settled_area_sauid_t;
ALTER TABLE exposure.canada_exposure ADD CONSTRAINT fk_canada_exposure_sauid_canada_exposure_assets_sauid_t FOREIGN KEY (sauid) REFERENCES results_canada_exposure.canada_exposure_settled_area_sauid_t("Sauid");

-- census.census_2016_canada
ALTER TABLE results_canada_exposure.canada_exposure_settled_area_sauid_t DROP CONSTRAINT IF EXISTS fk_canada_exposure_settled_area_sauid_t_sauid_census_2016_canada;
ALTER TABLE results_canada_exposure.canada_exposure_settled_area_sauid_t ADD CONSTRAINT fk_canada_exposure_settled_area_sauid_t_census_2016_canada FOREIGN KEY ("Sauid") REFERENCES census.census_2016_canada(sauidt);

-- boundaries."Geometry_SAUID"
ALTER TABLE results_canada_exposure.canada_exposure_settled_area_sauid_t DROP CONSTRAINT IF EXISTS fk_canada_exposure_settled_area_sauid_t_sauid_geometry_sauid;
ALTER TABLE results_canada_exposure.canada_exposure_settled_area_sauid_t ADD CONSTRAINT fk_canada_exposure_settled_area_sauid_t_sauid_geometry_sauid FOREIGN KEY ("Sauid") REFERENCES boundaries."Geometry_SAUID"("SAUIDt");



-- results_canada_exposure.canada_exposure_building_function_sauid_t
-- add pkey
ALTER TABLE results_canada_exposure.canada_exposure_building_function_sauid_t DROP CONSTRAINT IF EXISTS canada_exposure_building_function_sauid_t_pkey;
ALTER TABLE results_canada_exposure.canada_exposure_building_function_sauid_t ADD PRIMARY KEY("Sauid");

-- exposure.canada_exposure
ALTER TABLE exposure.canada_exposure DROP CONSTRAINT IF EXISTS fk_canada_exposure_sauid_canada_exposure_building_function_sauid_t;
ALTER TABLE exposure.canada_exposure ADD CONSTRAINT fk_canada_exposure_sauid_canada_exposure_building_function_sauid_t FOREIGN KEY (sauid) REFERENCES results_canada_exposure.canada_exposure_building_function_sauid_t("Sauid");

-- census.census_2016_canada
ALTER TABLE results_canada_exposure.canada_exposure_building_function_sauid_t DROP CONSTRAINT IF EXISTS fk_canada_exposure_building_function_sauid_t_sauid_census_2016_canada;
ALTER TABLE results_canada_exposure.canada_exposure_building_function_sauid_t ADD CONSTRAINT fk_canada_exposure_building_function_sauid_t_sauid_census_2016_canada FOREIGN KEY ("Sauid") REFERENCES census.census_2016_canada(sauidt);

-- boundaries."Geometry_SAUID"
ALTER TABLE results_canada_exposure.canada_exposure_building_function_sauid_t DROP CONSTRAINT IF EXISTS fk_canada_exposure_building_function_sauid_t_sauid_geometry_sauid;
ALTER TABLE results_canada_exposure.canada_exposure_building_function_sauid_t ADD CONSTRAINT fk_canada_exposure_assets_sauid_t_sauid_geometry_sauid FOREIGN KEY ("Sauid") REFERENCES boundaries."Geometry_SAUID"("SAUIDt");



-- results_canada_exposure.canada_exposure_building_type_sauid_t
-- add pkey
ALTER TABLE results_canada_exposure.canada_exposure_building_type_sauid_t DROP CONSTRAINT IF EXISTS canada_exposure_building_type_sauid_t_pkey;
ALTER TABLE results_canada_exposure.canada_exposure_building_type_sauid_t ADD PRIMARY KEY("Sauid");

-- exposure.canada_exposure
ALTER TABLE exposure.canada_exposure DROP CONSTRAINT IF EXISTS fk_canada_exposure_sauid_canada_exposure_building_type_sauid_t;
ALTER TABLE exposure.canada_exposure ADD CONSTRAINT fk_canada_exposure_sauid_canada_exposure_building_type_sauid_t FOREIGN KEY (sauid) REFERENCES results_canada_exposure.canada_exposure_building_type_sauid_t("Sauid");

-- boundaries."Geometry_SAUID"
ALTER TABLE results_canada_exposure.canada_exposure_building_type_sauid_t DROP CONSTRAINT IF EXISTS fk_canada_exposure_building_type_sauid_t_sauid_geometry_sauid;
ALTER TABLE results_canada_exposure.canada_exposure_building_type_sauid_t ADD CONSTRAINT fk_canada_exposure_building_type_sauid_t_sauid_geometry_sauid FOREIGN KEY ("Sauid") REFERENCES boundaries."Geometry_SAUID"("SAUIDt");



-- results_canada_exposure.canada_exposure_people_sauid_t
-- add pkey
ALTER TABLE results_canada_exposure.canada_exposure_people_sauid_t DROP CONSTRAINT IF EXISTS canada_exposure_people_sauid_t_pkey;
ALTER TABLE results_canada_exposure.canada_exposure_people_sauid_t ADD PRIMARY KEY("Sauid");

-- exposure.canada_exposure
ALTER TABLE exposure.canada_exposure DROP CONSTRAINT IF EXISTS fk_canada_exposure_sauid_canada_exposure_people_sauid_t;
ALTER TABLE exposure.canada_exposure ADD CONSTRAINT fk_canada_exposure_sauid_canada_exposure_people_sauid_t FOREIGN KEY (sauid) REFERENCES results_canada_exposure.canada_exposure_people_sauid_t("Sauid");

-- boundaries."Geometry_SAUID"
ALTER TABLE results_canada_exposure.canada_exposure_people_sauid_t DROP CONSTRAINT IF EXISTS fk_canada_exposure_people_sauid_t_sauid_geometry_sauid;
ALTER TABLE results_canada_exposure.canada_exposure_people_sauid_t ADD CONSTRAINT fk_canada_exposure_people_sauid_t_sauid_geometry_sauid FOREIGN KEY ("Sauid") REFERENCES boundaries."Geometry_SAUID"("SAUIDt");



-- results_canada_exposure.canada_exposure_assets_sauid_t
-- results_canada_exposure.canada_exposure_assets_sauid_t
-- add pkey
ALTER TABLE results_canada_exposure.canada_exposure_assets_sauid_t DROP CONSTRAINT IF EXISTS canada_exposure_assets_sauid_t_pkey;
ALTER TABLE results_canada_exposure.canada_exposure_assets_sauid_t ADD PRIMARY KEY("Sauid");

-- exposure.canada_exposure
ALTER TABLE exposure.canada_exposure DROP CONSTRAINT IF EXISTS fk_canada_exposure_sauid_canada_exposure_assets_sauid_t;
ALTER TABLE exposure.canada_exposure ADD CONSTRAINT fk_canada_exposure_sauid_canada_exposure_assets_sauid_t FOREIGN KEY (sauid) REFERENCES results_canada_exposure.canada_exposure_assets_sauid_t("Sauid");

-- boundaries."Geometry_SAUID"
ALTER TABLE results_canada_exposure.canada_exposure_assets_sauid_t DROP CONSTRAINT IF EXISTS fk_canada_exposure_assets_sauid_t_sauid_geometry_sauid;
ALTER TABLE results_canada_exposure.canada_exposure_assets_sauid_t ADD CONSTRAINT fk_canada_exposure_assets_sauid_t_sauid_geometry_sauid FOREIGN KEY ("Sauid") REFERENCES boundaries."Geometry_SAUID"("SAUIDt");