-- test hexbin aggregation for psra national level

-- 5km
DROP TABLE IF EXISTS results_psra_national.psra_all_indicators_s_hexbin_5km CASCADE;
CREATE TABLE results_psra_national.psra_all_indicators_s_hexbin_5km AS
SELECT 
b.gridid_5,
AVG("pH500_PGA") AS "pH500_PGA",
AVG("pH500_SA0p1") AS "pH500_SA0p1",
AVG("pH500_SA0p2") AS "pH500_SA0p2",
AVG("pH500_SA0p3") AS "pH500_SA0p3",
AVG("pH500_SA0p5") AS "pH500_SA0p5",
AVG("pH500_SA0p6") AS "pH500_SA0p6",
AVG("pH500_SA1p0") AS "pH500_SA1p0",
AVG("pH500_SA2p0") AS "pH500_SA2p0",
AVG("pH2500_PGA") AS "pH2500_PGA",
AVG("pH2500_SA0p1") AS "pH2500_SA0p1",
AVG("pH2500_SA0p2") AS "pH2500_SA0p2",
AVG("pH2500_SA0p3") AS "pH2500_SA0p3",
AVG("pH2500_SA0p5") AS "pH2500_SA0p5",
AVG("pH2500_SA0p6") AS "pH2500_SA0p6",
AVG("pH2500_SA1p0") AS "pH2500_SA1p0",
AVG("pH2500_SA2p0") AS "pH2500_SA2p0",
AVG("pH_Vs30") AS "pH_Vs30",
AVG("pH_Vs1p0") AS "pH_Vs1p0",
AVG("pH_Vs2p5") AS "pH_Vs2p5",
AVG("cDtr_None_b0") AS "cDtr_None_b0",
AVG("cDtr_Slight_b0") AS "cDtr_Slight_b0",
AVG("cDtr_Moderate_b0") AS "cDtr_Moderate_b0",
AVG("cDtr_Extensive_b0") AS "cDtr_Extensive_b0",
AVG("cDtr_Complete_b0") AS "cDtr_Complete_b0",
AVG("cDtr_Collapse_b0") AS "cDtr_Collapse_b0",
AVG("cDtr_None_r1") AS "cDtr_None_r1",
AVG("cDtr_Slight_r1") AS "cDtr_Slight_r1",
AVG("cDtr_Moderate_r1") AS "cDtr_Moderate_r1",
AVG("cDtr_Extensive_r1") AS "cDtr_Extensive_r1",
AVG("cDtr_Complete_r1") AS "cDtr_Complete_r1",
AVG("cDtr_Collapse_r1") AS "cDtr_Collapse_r1",
SUM("eDt_None_b0") AS "eDt_None_b0",
AVG("eDtr_None_b0") AS "eDtr_None_b0",
SUM("eDt_Slight_b0") AS "eDt_Slight_b0",
AVG("eDtr_Slight_b0") AS "eDtr_Slight_b0",
SUM("eDt_Moderate_b0") AS "eDt_Moderate_b0",
AVG("eDtr_Moderate_b0") AS "eDtr_Moderate_b0",
SUM("eDt_Extensive_b0") AS "eDt_Extensive_b0",
AVG("eDtr_Extensive_b0") AS "eDtr_Extensive_b0",
SUM("eDt_Complete_b0") AS "eDt_Complete_b0",
AVG("eDtr_Complete_b0") AS "eDtr_Complete_b0",
SUM("eDt_Collapse_b0") AS "eDt_Collapse_b0",
AVG("eDtr_Collapse_b0") AS "eDtr_Collapse_b0",
SUM("eDt_None_r1") AS "eDt_None_r1",
AVG("eDtr_None_r1") AS "eDtr_None_r1",
SUM("eDt_Slight_r1") AS "eDt_Slight_r1",
AVG("eDtr_Slight_r1") AS "eDtr_Slight_r1",
SUM("eDt_Moderate_r1") AS "eDt_Moderate_r1",
AVG("eDtr_Moderate_r1") AS "eDtr_Moderate_r1",
SUM("eDt_Extensive_r1") AS "eDt_Extensive_r1",
AVG("eDtr_Extensive_r1") AS "eDtr_Extensive_r1",
SUM("eDt_Complete_r1") AS "eDt_Complete_r1",
AVG("eDtr_Complete_r1") AS "eDtr_Complete_r1",
SUM("eDt_Collapse_r1") AS "eDt_Collapse_r1",
AVG("eDtr_Collapse_r1") AS "eDtr_Collapse_r1",
SUM("eAALt_Asset_b0") AS "eAALt_Asset_b0",
AVG("eAALm_Asset_b0") AS "eAALm_Asset_b0",
SUM("eAALt_Bldg_b0") AS "eAALt_Bldg_b0",
AVG("eAALm_Bldg_b0") AS "eAALm_Bldg_b0",
SUM("eAALt_Str_b0") AS "eAALt_Str_b0",
SUM("eAALt_NStr_b0") AS "eAALt_NStr_b0",
SUM("eAALt_Cont_b0") AS "eAALt_Cont_b0",
SUM("eAALt_Asset_r1") AS "eAALt_Asset_r1",
AVG("eAALm_Asset_r1") AS "eAALm_Asset_r1",
SUM("eAALt_Bldg_r1") AS "eAALt_Bldg_r1",
AVG("eAALm_Bldg_r1") AS "eAALm_Bldg_r1",
SUM("eAALt_Str_r1") AS "eAALt_Str_r1",
SUM("eAALt_NStr_r1") AS "eAALt_NStr_r1",
SUM("eAALt_Cont_r1") AS "eAALt_Cont_r1",
c.geom

FROM results_psra_national.psra_all_indicators_s_tbl a
LEFT JOIN boundaries."SAUID_HexGrid_v1" b ON a."Sauid" = b.sauid
LEFT JOIN boundaries."HexGrid_5km_v1" c ON b.gridid_5 = c.gridid_5
GROUP BY b.gridid_5,c.geom;



-- test hexbin aggregation for psra national level

-- 10km
DROP TABLE IF EXISTS results_psra_national.psra_all_indicators_s_hexbin_10km CASCADE;
CREATE TABLE results_psra_national.psra_all_indicators_s_hexbin_10km AS
SELECT 
b.gridid_10,
AVG("pH500_PGA") AS "pH500_PGA",
AVG("pH500_SA0p1") AS "pH500_SA0p1",
AVG("pH500_SA0p2") AS "pH500_SA0p2",
AVG("pH500_SA0p3") AS "pH500_SA0p3",
AVG("pH500_SA0p5") AS "pH500_SA0p5",
AVG("pH500_SA0p6") AS "pH500_SA0p6",
AVG("pH500_SA1p0") AS "pH500_SA1p0",
AVG("pH500_SA2p0") AS "pH500_SA2p0",
AVG("pH2500_PGA") AS "pH2500_PGA",
AVG("pH2500_SA0p1") AS "pH2500_SA0p1",
AVG("pH2500_SA0p2") AS "pH2500_SA0p2",
AVG("pH2500_SA0p3") AS "pH2500_SA0p3",
AVG("pH2500_SA0p5") AS "pH2500_SA0p5",
AVG("pH2500_SA0p6") AS "pH2500_SA0p6",
AVG("pH2500_SA1p0") AS "pH2500_SA1p0",
AVG("pH2500_SA2p0") AS "pH2500_SA2p0",
AVG("pH_Vs30") AS "pH_Vs30",
AVG("pH_Vs1p0") AS "pH_Vs1p0",
AVG("pH_Vs2p5") AS "pH_Vs2p5",
AVG("cDtr_None_b0") AS "cDtr_None_b0",
AVG("cDtr_Slight_b0") AS "cDtr_Slight_b0",
AVG("cDtr_Moderate_b0") AS "cDtr_Moderate_b0",
AVG("cDtr_Extensive_b0") AS "cDtr_Extensive_b0",
AVG("cDtr_Complete_b0") AS "cDtr_Complete_b0",
AVG("cDtr_Collapse_b0") AS "cDtr_Collapse_b0",
AVG("cDtr_None_r1") AS "cDtr_None_r1",
AVG("cDtr_Slight_r1") AS "cDtr_Slight_r1",
AVG("cDtr_Moderate_r1") AS "cDtr_Moderate_r1",
AVG("cDtr_Extensive_r1") AS "cDtr_Extensive_r1",
AVG("cDtr_Complete_r1") AS "cDtr_Complete_r1",
AVG("cDtr_Collapse_r1") AS "cDtr_Collapse_r1",
SUM("eDt_None_b0") AS "eDt_None_b0",
AVG("eDtr_None_b0") AS "eDtr_None_b0",
SUM("eDt_Slight_b0") AS "eDt_Slight_b0",
AVG("eDtr_Slight_b0") AS "eDtr_Slight_b0",
SUM("eDt_Moderate_b0") AS "eDt_Moderate_b0",
AVG("eDtr_Moderate_b0") AS "eDtr_Moderate_b0",
SUM("eDt_Extensive_b0") AS "eDt_Extensive_b0",
AVG("eDtr_Extensive_b0") AS "eDtr_Extensive_b0",
SUM("eDt_Complete_b0") AS "eDt_Complete_b0",
AVG("eDtr_Complete_b0") AS "eDtr_Complete_b0",
SUM("eDt_Collapse_b0") AS "eDt_Collapse_b0",
AVG("eDtr_Collapse_b0") AS "eDtr_Collapse_b0",
SUM("eDt_None_r1") AS "eDt_None_r1",
AVG("eDtr_None_r1") AS "eDtr_None_r1",
SUM("eDt_Slight_r1") AS "eDt_Slight_r1",
AVG("eDtr_Slight_r1") AS "eDtr_Slight_r1",
SUM("eDt_Moderate_r1") AS "eDt_Moderate_r1",
AVG("eDtr_Moderate_r1") AS "eDtr_Moderate_r1",
SUM("eDt_Extensive_r1") AS "eDt_Extensive_r1",
AVG("eDtr_Extensive_r1") AS "eDtr_Extensive_r1",
SUM("eDt_Complete_r1") AS "eDt_Complete_r1",
AVG("eDtr_Complete_r1") AS "eDtr_Complete_r1",
SUM("eDt_Collapse_r1") AS "eDt_Collapse_r1",
AVG("eDtr_Collapse_r1") AS "eDtr_Collapse_r1",
SUM("eAALt_Asset_b0") AS "eAALt_Asset_b0",
AVG("eAALm_Asset_b0") AS "eAALm_Asset_b0",
SUM("eAALt_Bldg_b0") AS "eAALt_Bldg_b0",
AVG("eAALm_Bldg_b0") AS "eAALm_Bldg_b0",
SUM("eAALt_Str_b0") AS "eAALt_Str_b0",
SUM("eAALt_NStr_b0") AS "eAALt_NStr_b0",
SUM("eAALt_Cont_b0") AS "eAALt_Cont_b0",
SUM("eAALt_Asset_r1") AS "eAALt_Asset_r1",
AVG("eAALm_Asset_r1") AS "eAALm_Asset_r1",
SUM("eAALt_Bldg_r1") AS "eAALt_Bldg_r1",
AVG("eAALm_Bldg_r1") AS "eAALm_Bldg_r1",
SUM("eAALt_Str_r1") AS "eAALt_Str_r1",
SUM("eAALt_NStr_r1") AS "eAALt_NStr_r1",
SUM("eAALt_Cont_r1") AS "eAALt_Cont_r1",
c.geom

FROM results_psra_national.psra_all_indicators_s_tbl a
LEFT JOIN boundaries."SAUID_HexGrid_v1" b ON a."Sauid" = b.sauid
LEFT JOIN boundaries."HexGrid_10km_v1" c ON b.gridid_10 = c.gridid_10
GROUP BY b.gridid_10,c.geom;



-- test hexbin aggregation for psra national level

-- 25km
DROP TABLE IF EXISTS results_psra_national.psra_all_indicators_s_hexbin_25km CASCADE;
CREATE TABLE results_psra_national.psra_all_indicators_s_hexbin_25km AS
SELECT 
b.gridid_25,
AVG("pH500_PGA") AS "pH500_PGA",
AVG("pH500_SA0p1") AS "pH500_SA0p1",
AVG("pH500_SA0p2") AS "pH500_SA0p2",
AVG("pH500_SA0p3") AS "pH500_SA0p3",
AVG("pH500_SA0p5") AS "pH500_SA0p5",
AVG("pH500_SA0p6") AS "pH500_SA0p6",
AVG("pH500_SA1p0") AS "pH500_SA1p0",
AVG("pH500_SA2p0") AS "pH500_SA2p0",
AVG("pH2500_PGA") AS "pH2500_PGA",
AVG("pH2500_SA0p1") AS "pH2500_SA0p1",
AVG("pH2500_SA0p2") AS "pH2500_SA0p2",
AVG("pH2500_SA0p3") AS "pH2500_SA0p3",
AVG("pH2500_SA0p5") AS "pH2500_SA0p5",
AVG("pH2500_SA0p6") AS "pH2500_SA0p6",
AVG("pH2500_SA1p0") AS "pH2500_SA1p0",
AVG("pH2500_SA2p0") AS "pH2500_SA2p0",
AVG("pH_Vs30") AS "pH_Vs30",
AVG("pH_Vs1p0") AS "pH_Vs1p0",
AVG("pH_Vs2p5") AS "pH_Vs2p5",
AVG("cDtr_None_b0") AS "cDtr_None_b0",
AVG("cDtr_Slight_b0") AS "cDtr_Slight_b0",
AVG("cDtr_Moderate_b0") AS "cDtr_Moderate_b0",
AVG("cDtr_Extensive_b0") AS "cDtr_Extensive_b0",
AVG("cDtr_Complete_b0") AS "cDtr_Complete_b0",
AVG("cDtr_Collapse_b0") AS "cDtr_Collapse_b0",
AVG("cDtr_None_r1") AS "cDtr_None_r1",
AVG("cDtr_Slight_r1") AS "cDtr_Slight_r1",
AVG("cDtr_Moderate_r1") AS "cDtr_Moderate_r1",
AVG("cDtr_Extensive_r1") AS "cDtr_Extensive_r1",
AVG("cDtr_Complete_r1") AS "cDtr_Complete_r1",
AVG("cDtr_Collapse_r1") AS "cDtr_Collapse_r1",
SUM("eDt_None_b0") AS "eDt_None_b0",
AVG("eDtr_None_b0") AS "eDtr_None_b0",
SUM("eDt_Slight_b0") AS "eDt_Slight_b0",
AVG("eDtr_Slight_b0") AS "eDtr_Slight_b0",
SUM("eDt_Moderate_b0") AS "eDt_Moderate_b0",
AVG("eDtr_Moderate_b0") AS "eDtr_Moderate_b0",
SUM("eDt_Extensive_b0") AS "eDt_Extensive_b0",
AVG("eDtr_Extensive_b0") AS "eDtr_Extensive_b0",
SUM("eDt_Complete_b0") AS "eDt_Complete_b0",
AVG("eDtr_Complete_b0") AS "eDtr_Complete_b0",
SUM("eDt_Collapse_b0") AS "eDt_Collapse_b0",
AVG("eDtr_Collapse_b0") AS "eDtr_Collapse_b0",
SUM("eDt_None_r1") AS "eDt_None_r1",
AVG("eDtr_None_r1") AS "eDtr_None_r1",
SUM("eDt_Slight_r1") AS "eDt_Slight_r1",
AVG("eDtr_Slight_r1") AS "eDtr_Slight_r1",
SUM("eDt_Moderate_r1") AS "eDt_Moderate_r1",
AVG("eDtr_Moderate_r1") AS "eDtr_Moderate_r1",
SUM("eDt_Extensive_r1") AS "eDt_Extensive_r1",
AVG("eDtr_Extensive_r1") AS "eDtr_Extensive_r1",
SUM("eDt_Complete_r1") AS "eDt_Complete_r1",
AVG("eDtr_Complete_r1") AS "eDtr_Complete_r1",
SUM("eDt_Collapse_r1") AS "eDt_Collapse_r1",
AVG("eDtr_Collapse_r1") AS "eDtr_Collapse_r1",
SUM("eAALt_Asset_b0") AS "eAALt_Asset_b0",
AVG("eAALm_Asset_b0") AS "eAALm_Asset_b0",
SUM("eAALt_Bldg_b0") AS "eAALt_Bldg_b0",
AVG("eAALm_Bldg_b0") AS "eAALm_Bldg_b0",
SUM("eAALt_Str_b0") AS "eAALt_Str_b0",
SUM("eAALt_NStr_b0") AS "eAALt_NStr_b0",
SUM("eAALt_Cont_b0") AS "eAALt_Cont_b0",
SUM("eAALt_Asset_r1") AS "eAALt_Asset_r1",
AVG("eAALm_Asset_r1") AS "eAALm_Asset_r1",
SUM("eAALt_Bldg_r1") AS "eAALt_Bldg_r1",
AVG("eAALm_Bldg_r1") AS "eAALm_Bldg_r1",
SUM("eAALt_Str_r1") AS "eAALt_Str_r1",
SUM("eAALt_NStr_r1") AS "eAALt_NStr_r1",
SUM("eAALt_Cont_r1") AS "eAALt_Cont_r1",
c.geom

FROM results_psra_national.psra_all_indicators_s_tbl a
LEFT JOIN boundaries."SAUID_HexGrid_v1" b ON a."Sauid" = b.sauid
LEFT JOIN boundaries."HexGrid_25km_v1" c ON b.gridid_25 = c.gridid_25
GROUP BY b.gridid_25,c.geom;



-- test hexbin aggregation for psra national level

-- 50km
DROP TABLE IF EXISTS results_psra_national.psra_all_indicators_s_hexbin_50km CASCADE;
CREATE TABLE results_psra_national.psra_all_indicators_s_hexbin_50km AS
SELECT 
b.gridid_50,
AVG("pH500_PGA") AS "pH500_PGA",
AVG("pH500_SA0p1") AS "pH500_SA0p1",
AVG("pH500_SA0p2") AS "pH500_SA0p2",
AVG("pH500_SA0p3") AS "pH500_SA0p3",
AVG("pH500_SA0p5") AS "pH500_SA0p5",
AVG("pH500_SA0p6") AS "pH500_SA0p6",
AVG("pH500_SA1p0") AS "pH500_SA1p0",
AVG("pH500_SA2p0") AS "pH500_SA2p0",
AVG("pH2500_PGA") AS "pH2500_PGA",
AVG("pH2500_SA0p1") AS "pH2500_SA0p1",
AVG("pH2500_SA0p2") AS "pH2500_SA0p2",
AVG("pH2500_SA0p3") AS "pH2500_SA0p3",
AVG("pH2500_SA0p5") AS "pH2500_SA0p5",
AVG("pH2500_SA0p6") AS "pH2500_SA0p6",
AVG("pH2500_SA1p0") AS "pH2500_SA1p0",
AVG("pH2500_SA2p0") AS "pH2500_SA2p0",
AVG("pH_Vs30") AS "pH_Vs30",
AVG("pH_Vs1p0") AS "pH_Vs1p0",
AVG("pH_Vs2p5") AS "pH_Vs2p5",
AVG("cDtr_None_b0") AS "cDtr_None_b0",
AVG("cDtr_Slight_b0") AS "cDtr_Slight_b0",
AVG("cDtr_Moderate_b0") AS "cDtr_Moderate_b0",
AVG("cDtr_Extensive_b0") AS "cDtr_Extensive_b0",
AVG("cDtr_Complete_b0") AS "cDtr_Complete_b0",
AVG("cDtr_Collapse_b0") AS "cDtr_Collapse_b0",
AVG("cDtr_None_r1") AS "cDtr_None_r1",
AVG("cDtr_Slight_r1") AS "cDtr_Slight_r1",
AVG("cDtr_Moderate_r1") AS "cDtr_Moderate_r1",
AVG("cDtr_Extensive_r1") AS "cDtr_Extensive_r1",
AVG("cDtr_Complete_r1") AS "cDtr_Complete_r1",
AVG("cDtr_Collapse_r1") AS "cDtr_Collapse_r1",
SUM("eDt_None_b0") AS "eDt_None_b0",
AVG("eDtr_None_b0") AS "eDtr_None_b0",
SUM("eDt_Slight_b0") AS "eDt_Slight_b0",
AVG("eDtr_Slight_b0") AS "eDtr_Slight_b0",
SUM("eDt_Moderate_b0") AS "eDt_Moderate_b0",
AVG("eDtr_Moderate_b0") AS "eDtr_Moderate_b0",
SUM("eDt_Extensive_b0") AS "eDt_Extensive_b0",
AVG("eDtr_Extensive_b0") AS "eDtr_Extensive_b0",
SUM("eDt_Complete_b0") AS "eDt_Complete_b0",
AVG("eDtr_Complete_b0") AS "eDtr_Complete_b0",
SUM("eDt_Collapse_b0") AS "eDt_Collapse_b0",
AVG("eDtr_Collapse_b0") AS "eDtr_Collapse_b0",
SUM("eDt_None_r1") AS "eDt_None_r1",
AVG("eDtr_None_r1") AS "eDtr_None_r1",
SUM("eDt_Slight_r1") AS "eDt_Slight_r1",
AVG("eDtr_Slight_r1") AS "eDtr_Slight_r1",
SUM("eDt_Moderate_r1") AS "eDt_Moderate_r1",
AVG("eDtr_Moderate_r1") AS "eDtr_Moderate_r1",
SUM("eDt_Extensive_r1") AS "eDt_Extensive_r1",
AVG("eDtr_Extensive_r1") AS "eDtr_Extensive_r1",
SUM("eDt_Complete_r1") AS "eDt_Complete_r1",
AVG("eDtr_Complete_r1") AS "eDtr_Complete_r1",
SUM("eDt_Collapse_r1") AS "eDt_Collapse_r1",
AVG("eDtr_Collapse_r1") AS "eDtr_Collapse_r1",
SUM("eAALt_Asset_b0") AS "eAALt_Asset_b0",
AVG("eAALm_Asset_b0") AS "eAALm_Asset_b0",
SUM("eAALt_Bldg_b0") AS "eAALt_Bldg_b0",
AVG("eAALm_Bldg_b0") AS "eAALm_Bldg_b0",
SUM("eAALt_Str_b0") AS "eAALt_Str_b0",
SUM("eAALt_NStr_b0") AS "eAALt_NStr_b0",
SUM("eAALt_Cont_b0") AS "eAALt_Cont_b0",
SUM("eAALt_Asset_r1") AS "eAALt_Asset_r1",
AVG("eAALm_Asset_r1") AS "eAALm_Asset_r1",
SUM("eAALt_Bldg_r1") AS "eAALt_Bldg_r1",
AVG("eAALm_Bldg_r1") AS "eAALm_Bldg_r1",
SUM("eAALt_Str_r1") AS "eAALt_Str_r1",
SUM("eAALt_NStr_r1") AS "eAALt_NStr_r1",
SUM("eAALt_Cont_r1") AS "eAALt_Cont_r1",
c.geom

FROM results_psra_national.psra_all_indicators_s_tbl a
LEFT JOIN boundaries."SAUID_HexGrid_v1" b ON a."Sauid" = b.sauid
LEFT JOIN boundaries."HexGrid_50km_v1" c ON b.gridid_50 = c.gridid_50
GROUP BY b.gridid_50,c.geom;



-- test hexbin aggregation for psra national level

-- 100km
DROP TABLE IF EXISTS results_psra_national.psra_all_indicators_s_hexbin_100km CASCADE;
CREATE TABLE results_psra_national.psra_all_indicators_s_hexbin_100km AS
SELECT 
b.gridid_100,
AVG("pH500_PGA") AS "pH500_PGA",
AVG("pH500_SA0p1") AS "pH500_SA0p1",
AVG("pH500_SA0p2") AS "pH500_SA0p2",
AVG("pH500_SA0p3") AS "pH500_SA0p3",
AVG("pH500_SA0p5") AS "pH500_SA0p5",
AVG("pH500_SA0p6") AS "pH500_SA0p6",
AVG("pH500_SA1p0") AS "pH500_SA1p0",
AVG("pH500_SA2p0") AS "pH500_SA2p0",
AVG("pH2500_PGA") AS "pH2500_PGA",
AVG("pH2500_SA0p1") AS "pH2500_SA0p1",
AVG("pH2500_SA0p2") AS "pH2500_SA0p2",
AVG("pH2500_SA0p3") AS "pH2500_SA0p3",
AVG("pH2500_SA0p5") AS "pH2500_SA0p5",
AVG("pH2500_SA0p6") AS "pH2500_SA0p6",
AVG("pH2500_SA1p0") AS "pH2500_SA1p0",
AVG("pH2500_SA2p0") AS "pH2500_SA2p0",
AVG("pH_Vs30") AS "pH_Vs30",
AVG("pH_Vs1p0") AS "pH_Vs1p0",
AVG("pH_Vs2p5") AS "pH_Vs2p5",
AVG("cDtr_None_b0") AS "cDtr_None_b0",
AVG("cDtr_Slight_b0") AS "cDtr_Slight_b0",
AVG("cDtr_Moderate_b0") AS "cDtr_Moderate_b0",
AVG("cDtr_Extensive_b0") AS "cDtr_Extensive_b0",
AVG("cDtr_Complete_b0") AS "cDtr_Complete_b0",
AVG("cDtr_Collapse_b0") AS "cDtr_Collapse_b0",
AVG("cDtr_None_r1") AS "cDtr_None_r1",
AVG("cDtr_Slight_r1") AS "cDtr_Slight_r1",
AVG("cDtr_Moderate_r1") AS "cDtr_Moderate_r1",
AVG("cDtr_Extensive_r1") AS "cDtr_Extensive_r1",
AVG("cDtr_Complete_r1") AS "cDtr_Complete_r1",
AVG("cDtr_Collapse_r1") AS "cDtr_Collapse_r1",
SUM("eDt_None_b0") AS "eDt_None_b0",
AVG("eDtr_None_b0") AS "eDtr_None_b0",
SUM("eDt_Slight_b0") AS "eDt_Slight_b0",
AVG("eDtr_Slight_b0") AS "eDtr_Slight_b0",
SUM("eDt_Moderate_b0") AS "eDt_Moderate_b0",
AVG("eDtr_Moderate_b0") AS "eDtr_Moderate_b0",
SUM("eDt_Extensive_b0") AS "eDt_Extensive_b0",
AVG("eDtr_Extensive_b0") AS "eDtr_Extensive_b0",
SUM("eDt_Complete_b0") AS "eDt_Complete_b0",
AVG("eDtr_Complete_b0") AS "eDtr_Complete_b0",
SUM("eDt_Collapse_b0") AS "eDt_Collapse_b0",
AVG("eDtr_Collapse_b0") AS "eDtr_Collapse_b0",
SUM("eDt_None_r1") AS "eDt_None_r1",
AVG("eDtr_None_r1") AS "eDtr_None_r1",
SUM("eDt_Slight_r1") AS "eDt_Slight_r1",
AVG("eDtr_Slight_r1") AS "eDtr_Slight_r1",
SUM("eDt_Moderate_r1") AS "eDt_Moderate_r1",
AVG("eDtr_Moderate_r1") AS "eDtr_Moderate_r1",
SUM("eDt_Extensive_r1") AS "eDt_Extensive_r1",
AVG("eDtr_Extensive_r1") AS "eDtr_Extensive_r1",
SUM("eDt_Complete_r1") AS "eDt_Complete_r1",
AVG("eDtr_Complete_r1") AS "eDtr_Complete_r1",
SUM("eDt_Collapse_r1") AS "eDt_Collapse_r1",
AVG("eDtr_Collapse_r1") AS "eDtr_Collapse_r1",
SUM("eAALt_Asset_b0") AS "eAALt_Asset_b0",
AVG("eAALm_Asset_b0") AS "eAALm_Asset_b0",
SUM("eAALt_Bldg_b0") AS "eAALt_Bldg_b0",
AVG("eAALm_Bldg_b0") AS "eAALm_Bldg_b0",
SUM("eAALt_Str_b0") AS "eAALt_Str_b0",
SUM("eAALt_NStr_b0") AS "eAALt_NStr_b0",
SUM("eAALt_Cont_b0") AS "eAALt_Cont_b0",
SUM("eAALt_Asset_r1") AS "eAALt_Asset_r1",
AVG("eAALm_Asset_r1") AS "eAALm_Asset_r1",
SUM("eAALt_Bldg_r1") AS "eAALt_Bldg_r1",
AVG("eAALm_Bldg_r1") AS "eAALm_Bldg_r1",
SUM("eAALt_Str_r1") AS "eAALt_Str_r1",
SUM("eAALt_NStr_r1") AS "eAALt_NStr_r1",
SUM("eAALt_Cont_r1") AS "eAALt_Cont_r1",
c.geom

FROM results_psra_national.psra_all_indicators_s_tbl a
LEFT JOIN boundaries."SAUID_HexGrid_v1" b ON a."Sauid" = b.sauid
LEFT JOIN boundaries."HexGrid_100km_v1" c ON b.gridid_100 = c.gridid_100
GROUP BY b.gridid_100,c.geom;