-- create physical exposure indicators
DROP VIEW IF EXISTS results_all.canada_exposure_all CASCADE;
CREATE VIEW results_all.canada_exposure_all AS 

SELECT 
a.id AS "AssetID",
a.sauid AS "Sauid",
CAST(a.lon AS NUMERIC) AS "Asset_Lon",
CAST(a.lat AS NUMERIC)AS "Asset_Lat",
CAST(a.number AS NUMERIC) AS "BldNum",
CAST(b."BldgArea_ft2" AS NUMERIC) AS "BldgArea_ft2",
a.landusetyp AS "LandUse",
a.genocc AS "Occ_General",
a.eqocctype AS "Occ_Specific",
a.bldggen AS "Type_General",
a.eqbldgtype AS "Type_Specific",
a.eqdeslev AS "Design_Level",
CAST(a.structural AS NUMERIC) AS "StrCost",
CAST(a.nonstructural AS NUMERIC) AS "NStrCost",
CAST(a.contents AS NUMERIC) AS "ContCost",
CAST(a.structural + a.nonstructural + a.contents AS NUMERIC) AS "AssetCost",
CAST(a.structural + a.nonstructural AS NUMERIC) AS "BldgCost",
CAST(b."CAD_RetrofitCost_Bldg" AS NUMERIC) AS "RetrofitCost",
CAST(a.day AS NUMERIC) AS "DayPop",
CAST(a.night AS NUMERIC) AS "NightPop",
CAST(a.transit AS NUMERIC) AS "TransitPop",
a.geom

FROM psra.canada_exposure a
LEFT JOIN lut.retrofit_costs b ON a.eqbldgtype = b."Eq_BldgType";