-- create multi hazard indicators
DROP VIEW IF EXISTS results.mh_threat_cyclone_hazard_threat_assets_view CASCADE;
CREATE VIEW results.mh_threat_cyclone_hazard_threat_assets_view AS 

-- 9.1 Cyclone Hazard
-- 9.1.2 Cyclone Hazard Threat
-- 9.1.2.4 Assets
SELECT 
a.sauid,
COALESCE(CAST((c.cy500 - (SELECT cy500_min FROM lut.mh_intensity_canada_minmax))/NULLIF((SELECT cy500_max FROM lut.mh_intensity_canada_minmax) - (SELECT cy500_min FROM lut.mh_intensity_canada_minmax),0) AS NUMERIC),0) AS "Cy500n",
177 AS "Cy500t", -- 500yr Cyclone Hazard Threat

COALESCE(CAST(CASE WHEN c.cy500 >= 177 THEN SUM(a.structural + a.nonstructural + a.contents) ELSE 0 END AS NUMERIC),0) AS "AssetCostT_Cyt",

COALESCE(CAST(CASE WHEN c.cy500 >= 177 THEN SUM(a.structural + a.nonstructural) ELSE 0 END AS NUMERIC),0) AS "BldgCostT_Cyt",

COALESCE(CAST(CASE WHEN c.cy500 >= 177 THEN SUM(a.structural) ELSE 0 END AS NUMERIC),0) AS "StrCostT_Cyt",

COALESCE(CAST(CASE WHEN c.cy500 >= 177 THEN SUM(a.nonstructural) ELSE 0 END AS NUMERIC),0) AS "NStrCostT_Cyt",

COALESCE(CAST(CASE WHEN c.cy500 >= 177 THEN SUM(a.contents) ELSE 0 END AS NUMERIC),0) AS "ContCostT_Cyt",

d.geom AS "geom_poly",
d.geompoint AS "geom_point"

FROM psra.canada_exposure a
--LEFT JOIN lut.mh_intensity_canada_mhsum b ON a.sauid = b.sauidt
LEFT JOIN lut.mh_intensity_canada c on a.sauid = c.sauidt
LEFT JOIN boundaries."Geometry SAUID" d on a.sauid = d."SAUIDt"
LEFT JOIN lut.census_2016_canada e ON a.sauid = e.sauidt
GROUP BY a.sauid,c.cy500,e.censuspop,e.people_du,d.geom,d.geompoint;