-- create multi hazard indicators
DROP VIEW IF EXISTS results.mh_threat_cyclone_hazard_threat_building_construction_view CASCADE;
CREATE VIEW results.mh_threat_cyclone_hazard_threat_building_construction_view AS 

-- 9.1 Cyclone Hazard
-- 9.1.2 Cyclone Hazard Threat
-- 9.1.2.2 Building Construction
SELECT 
a.sauid,
COALESCE(CAST((c.cy500 - (SELECT cy500_min FROM lut.mh_intensity_canada_minmax))/NULLIF((SELECT cy500_max FROM lut.mh_intensity_canada_minmax) - (SELECT cy500_min FROM lut.mh_intensity_canada_minmax),0) AS NUMERIC),0) AS "Cy500n",
177 AS "Cy500t", -- 500yr Cyclone Hazard Threat

COALESCE(CAST(CASE WHEN c.cy500 >= 177 THEN SUM(a.number) ELSE 0 END AS NUMERIC),0) AS "BldgNumT_Cyt",

COALESCE(CAST(CASE WHEN c.cy500 >= 177 THEN SUM(CASE WHEN a.bldggen ='Wood' THEN a.number ELSE 0 END) ELSE 0 END AS NUMERIC),0) AS "Wood_Cyt",

COALESCE(CAST(CASE WHEN c.cy500 >= 177 THEN SUM(CASE WHEN a.bldggen ='Concrete' THEN a.number ELSE 0 END) ELSE 0 END AS NUMERIC),0) AS "Concrete_Cyt",

COALESCE(CAST(CASE WHEN c.cy500 >= 177 THEN SUM(CASE WHEN a.bldggen ='Precast' THEN a.number ELSE 0 END) ELSE 0 END AS NUMERIC),0) AS "PreCast_Cyt",

COALESCE(CAST(CASE WHEN c.cy500 >= 177 THEN SUM(CASE WHEN a.bldggen ='RMasonry' THEN a.number ELSE 0 END) ELSE 0 END AS NUMERIC),0) AS "RMasonry_Cyt",

COALESCE(CAST(CASE WHEN c.cy500 >= 177 THEN SUM(CASE WHEN a.bldggen ='URMasonry' THEN a.number ELSE 0 END) ELSE 0 END AS NUMERIC),0) AS "URMasonry_Cyt",

COALESCE(CAST(CASE WHEN c.cy500 >= 177 THEN SUM(CASE WHEN a.bldggen ='Steel' THEN a.number ELSE 0 END) ELSE 0 END AS NUMERIC),0) AS "Steel_Cyt",

COALESCE(CAST(CASE WHEN c.cy500 >= 177 THEN SUM(CASE WHEN a.bldggen ='Manufactured' THEN a.number ELSE 0 END) ELSE 0 END AS NUMERIC),0) AS "Manufactured_Cyt",

COALESCE(CAST(CASE WHEN c.cy500 >= 177 THEN SUM(CASE WHEN a.eqdeslev ='PC' THEN a.number ELSE 0 END) ELSE 0 END AS NUMERIC),0) AS "PreCode_Cyt",

COALESCE(CAST(CASE WHEN c.cy500 >= 177 THEN SUM(CASE WHEN a.eqdeslev ='LC' THEN a.number ELSE 0 END) ELSE 0 END AS NUMERIC),0) AS "LowCode_Cyt",

COALESCE(CAST(CASE WHEN c.cy500 >= 177 THEN SUM(CASE WHEN a.eqdeslev ='MC' THEN a.number ELSE 0 END) ELSE 0 END AS NUMERIC),0) AS "ModCode_Cyt",

COALESCE(CAST(CASE WHEN c.cy500 >= 177 THEN SUM(CASE WHEN a.eqdeslev ='HC' THEN a.number ELSE 0 END) ELSE 0 END AS NUMERIC),0) AS "HiCode_Cyt",

d.geom AS "geom_poly",
d.geompoint AS "geom_point"

FROM psra.canada_exposure a
LEFT JOIN lut.mh_intensity_canada_mhsum b ON a.sauid = b.sauidt
LEFT JOIN lut.mh_intensity_canada c on a.sauid = c.sauidt
LEFT JOIN boundaries."Geometry SAUID" d on a.sauid = d."SAUIDt"
GROUP BY a.sauid,c.cy500,d.geom,d.geompoint;