-- create scenario risk building indicators
DROP VIEW IF EXISTS results.dsra_sim6p8_cr2022_rlz_0_b0_social_disruption_agg;
CREATE VIEW results.dsra_sim6p8_cr2022_rlz_0_b0_social_disruption_agg AS 

-- 4.0 Earthquake Risk
-- 4.3 Afected People
-- 4.3.2 Social Disruption
SELECT
b.sauid AS "Sauid",
CAST(SUM(a."sC_DisplRes_3_b0")/h.people_du AS NUMERIC) AS "sC_DisplHshld_3T",
CAST(SUM(a."sC_DisplRes_30_b0")/h.people_du AS NUMERIC) AS "sC_DisplHshld_30T",
CAST(SUM(a."sC_DisplRes_90_b0")/h.people_du AS NUMERIC) AS "sC_DisplHshld_90T",
CAST(SUM(a."sC_DisplRes_180_b0")/h.people_du AS NUMERIC) AS "sC_DisplHshld_180T",
CAST(SUM(a."sC_DisplRes_360_b0")/h.people_du AS NUMERIC) AS "sC_DisplHshld_360T",
CAST(SUM(a."sC_DisrupEmpl_30_b0") AS NUMERIC) AS "sC_DisrupEmpl_30T",
CAST(SUM(a."sC_DisrupEmpl_90_b0") AS NUMERIC) AS "sC_DisrupEmpl_90T",
CAST(SUM(a."sC_DisrupEmpl_180_b0") AS NUMERIC) AS "sC_DisrupEmpl_180T",
CAST(SUM(a."sC_DisrupEmpl_360_b0") AS NUMERIC) AS "sC_DisrupEmpl_360T",
g.geom AS "geom_poly",
g.geompoint AS "geom_point"

FROM dsra.dsra_sim6p8_cr2022_rlz_0 a
LEFT JOIN psra.canada_exposure b ON a."AssetID" = b.id 
--LEFT JOIN lut.retrofit_costs c ON b.eqbldgtype = c."Eq_BldgType"
--LEFT JOIN lut.vs30_bc_site_model_xref d ON a."AssetID" = d.id
--LEFT JOIN lut.gmfdata_sitemesh_sim6p8_cr2022_37_xref e on b.id = e.id
--LEFT JOIN ruptures.rupture_table f on f.rupture_name = a."Rupture_Abbr"
LEFT JOIN boundaries."Geometry SAUID" g on b.sauid = g."SAUIDt"
LEFT JOIN lut.census_2016_canada h on b.sauid = h.sauidt
GROUP BY b.sauid, g.geom, g.geompoint, h.people_du;