-- create multi hazard indicators
DROP VIEW IF EXISTS results.mh_threat_seismic_hazard_intensity_mmi_likelihood CASCADE;
CREATE VIEW results.mh_threat_seismic_hazard_intensity_mmi_likelihood AS 

-- 4.1 Seismic Hazard
-- 4.1.1 Seismic Hazard Intensity
-- 4.1.1.2 MMI Likelihood (50yr)
SELECT 
a.sauid,
COALESCE(CAST((c.pga - (SELECT pga_min FROM lut.mh_intensity_canada_minmax))/NULLIF((SELECT pga_max FROM lut.mh_intensity_canada_minmax) - (SELECT pga_min FROM lut.mh_intensity_canada_minmax),0) AS NUMERIC),0) AS "PGAn",

CAST(c.mmi6 AS NUMERIC) AS "MMI6",
COALESCE(CAST((c.mmi6 - (SELECT mmi6_min FROM lut.mh_intensity_canada_minmax))/NULLIF((SELECT mmi6_max FROM lut.mh_intensity_canada_minmax) - (SELECT mmi6_min FROM lut.mh_intensity_canada_minmax),0) AS NUMERIC),0) AS "MMI6n",

CAST(c.mmi7 AS NUMERIC) AS "MMI7",
COALESCE(CAST((c.mmi7 - (SELECT mmi7_min FROM lut.mh_intensity_canada_minmax))/NULLIF((SELECT mmi7_max FROM lut.mh_intensity_canada_minmax) - (SELECT mmi7_min FROM lut.mh_intensity_canada_minmax),0) AS NUMERIC),0) AS "MMI7n",
0.05 AS "MMI7t", -- 50yr MMI VII probability score

CAST(c.mmi8 AS NUMERIC) AS "MMI8",
COALESCE(CAST((c.mmi8 - (SELECT mmi8_min FROM lut.mh_intensity_canada_minmax))/NULLIF((SELECT mmi8_max FROM lut.mh_intensity_canada_minmax) - (SELECT mmi8_min FROM lut.mh_intensity_canada_minmax),0) AS NUMERIC),0) AS "MMI8n",

d.geom AS "geom_poly",
d.geompoint AS "geom_point"

FROM psra.canada_exposure a
LEFT JOIN lut.mh_intensity_canada_mhsum b ON a.sauid = b.sauidt
LEFT JOIN lut.mh_intensity_canada c on a.sauid = c.sauidt
LEFT JOIN boundaries."Geometry SAUID" d on a.sauid = d."SAUIDt"
GROUP BY a.sauid,b.mh_sum,c.pga,c.mmi6,c.mmi7,c.mmi8,d.geom,d.geompoint;