-- create multi hazard indicators
DROP VIEW IF EXISTS results.mh_threat_wildfire_threat_building_function CASCADE;
CREATE VIEW results.mh_threat_wildfire_threat_building_function AS 

-- 8.1 Wildfire Hazard
-- 8.1.2 Wildfire Threat
-- 8.1.2.1 Building Function
SELECT 
a.sauid,
COALESCE(CAST((c.fire - (SELECT fire_min FROM lut.mh_intensity_canada_minmax))/NULLIF((SELECT fire_max FROM lut.mh_intensity_canada_minmax) - (SELECT fire_min FROM lut.mh_intensity_canada_minmax),0) AS NUMERIC),0) AS "Firen",
-- 2000 AS "Firet", -- Wildfire Intensity Threshold

COALESCE(CAST(CASE WHEN c.fire >= 2000 THEN SUM(a.number) ELSE 0 END AS NUMERIC),0) AS "BldgNumT_Fit",

COALESCE(CAST(CASE WHEN c.fire >= 2000 THEN SUM(CASE WHEN a.genocc ='Residential-LD' THEN a.number ELSE 0 END) ELSE 0 END AS NUMERIC),0) AS "RES_LD_Fit",

COALESCE(CAST(CASE WHEN c.fire >= 2000 THEN SUM(CASE WHEN a.genocc ='Residential-MD' THEN a.number ELSE 0 END) ELSE 0 END AS NUMERIC),0) AS "RES_MD_Fit",

COALESCE(CAST(CASE WHEN c.fire >= 2000 THEN SUM(CASE WHEN a.genocc ='Residential-HD' THEN a.number ELSE 0 END) ELSE 0 END AS NUMERIC),0) AS "RES_HD_Fit",

COALESCE(CAST(CASE WHEN c.fire >= 2000 THEN SUM(CASE WHEN a.genocc ='Commercial' THEN a.number ELSE 0 END) ELSE 0 END AS NUMERIC),0) AS "Comm_Fit",

COALESCE(CAST(CASE WHEN c.fire >= 2000 THEN SUM(CASE WHEN a.genocc ='Industrial' THEN a.number ELSE 0 END) ELSE 0 END AS NUMERIC),0) AS "Ind_Fit",

COALESCE(CAST(CASE WHEN c.fire >= 2000 THEN SUM(CASE WHEN a.genocc ='Civic' THEN a.number ELSE 0 END) ELSE 0 END AS NUMERIC),0) AS "Civic_Fit",

COALESCE(CAST(CASE WHEN c.fire >= 2000 THEN SUM(CASE WHEN a.genocc ='Agr' THEN a.number ELSE 0 END) ELSE 0 END AS NUMERIC),0) AS "Agr_Fit",

d.geom AS "geom_poly",
d.geompoint AS "geom_point"

FROM psra.canada_exposure a
LEFT JOIN lut.mh_intensity_canada_mhsum b ON a.sauid = b.sauidt
LEFT JOIN lut.mh_intensity_canada c on a.sauid = c.sauidt
LEFT JOIN boundaries."Geometry SAUID" d on a.sauid = d."SAUIDt"
GROUP BY a.sauid,c.fire,d.geom,d.geompoint;