-- create multi hazard indicators
DROP VIEW IF EXISTS results.mh_threat_wildfire_threat_building_construction CASCADE;
CREATE VIEW results.mh_threat_wildfire_threat_building_construction AS 

-- 8.1 Wildfire Hazard
-- 8.1.2 Wildfire Threat
-- 8.1.2.2 Building Construction
SELECT 
a.sauid,
COALESCE(CAST((c.fire - (SELECT fire_min FROM lut.mh_intensity_canada_minmax))/NULLIF((SELECT fire_max FROM lut.mh_intensity_canada_minmax) - (SELECT fire_min FROM lut.mh_intensity_canada_minmax),0) AS NUMERIC),0) AS "Firen",
-- 2000 AS "Firet", -- Wildfire Intensity Threshold

COALESCE(CAST(CASE WHEN c.fire >= 2000 THEN SUM(a.number) ELSE 0 END AS NUMERIC),0) AS "BldgNumT_Fit",

COALESCE(CAST(CASE WHEN c.fire >= 2000 THEN SUM(CASE WHEN a.bldggen ='Wood' THEN a.number ELSE 0 END) ELSE 0 END AS NUMERIC),0) AS "Wood_Fit",

COALESCE(CAST(CASE WHEN c.fire >= 2000 THEN SUM(CASE WHEN a.bldggen ='Concrete' THEN a.number ELSE 0 END) ELSE 0 END AS NUMERIC),0) AS "Concrete_Fit",

COALESCE(CAST(CASE WHEN c.fire >= 2000 THEN SUM(CASE WHEN a.bldggen ='Precast' THEN a.number ELSE 0 END) ELSE 0 END AS NUMERIC),0) AS "PreCast_Fit",

COALESCE(CAST(CASE WHEN c.fire >= 2000 THEN SUM(CASE WHEN a.bldggen ='RMasonry' THEN a.number ELSE 0 END) ELSE 0 END AS NUMERIC),0) AS "RMasonry_Fit",

COALESCE(CAST(CASE WHEN c.fire >= 2000 THEN SUM(CASE WHEN a.bldggen ='URMasonry' THEN a.number ELSE 0 END) ELSE 0 END AS NUMERIC),0) AS "URMasonry_Fit",

COALESCE(CAST(CASE WHEN c.fire >= 2000 THEN SUM(CASE WHEN a.bldggen ='Steel' THEN a.number ELSE 0 END) ELSE 0 END AS NUMERIC),0) AS "Steel_Fit",

COALESCE(CAST(CASE WHEN c.fire >= 2000 THEN SUM(CASE WHEN a.bldggen ='Manufactured' THEN a.number ELSE 0 END) ELSE 0 END AS NUMERIC),0) AS "Manufactured_Fit",

COALESCE(CAST(CASE WHEN c.fire >= 2000 THEN SUM(CASE WHEN a.eqdeslev ='PC' THEN a.number ELSE 0 END) ELSE 0 END AS NUMERIC),0) AS "PreCode_Fit",

COALESCE(CAST(CASE WHEN c.fire >= 2000 THEN SUM(CASE WHEN a.eqdeslev ='LC' THEN a.number ELSE 0 END) ELSE 0 END AS NUMERIC),0) AS "LowCode_Fit",

COALESCE(CAST(CASE WHEN c.fire >= 2000 THEN SUM(CASE WHEN a.eqdeslev ='MC' THEN a.number ELSE 0 END) ELSE 0 END AS NUMERIC),0) AS "ModCode_Fit",

COALESCE(CAST(CASE WHEN c.fire >= 2000 THEN SUM(CASE WHEN a.eqdeslev ='HC' THEN a.number ELSE 0 END) ELSE 0 END AS NUMERIC),0) AS "HiCode_Fit",

d.geom AS "geom_poly",
d.geompoint AS "geom_point"

FROM psra.canada_exposure a
LEFT JOIN lut.mh_intensity_canada_mhsum b ON a.sauid = b.sauidt
LEFT JOIN lut.mh_intensity_canada c on a.sauid = c.sauidt
LEFT JOIN boundaries."Geometry SAUID" d on a.sauid = d."SAUIDt"
GROUP BY a.sauid,c.fire,d.geom,d.geompoint;