-- script to generate relationships for sovi

-- results_sovi.social_vulnerability_family_structure_sauid_t
-- add pkey
ALTER TABLE results_sovi.social_vulnerability_family_structure_sauid_t DROP CONSTRAINT IF EXISTS social_vulnerability_family_structure_sauid_t_pkey;
ALTER TABLE results_sovi.social_vulnerability_family_structure_sauid_t ADD PRIMARY KEY("Sauid");

-- add fkey to exposure.canada_exposure
ALTER TABLE exposure.canada_exposure DROP CONSTRAINT IF EXISTS canada_exposure_sovi_fkey;
ALTER TABLE exposure.canada_exposure ADD CONSTRAINT canada_exposure_sovi_fkey FOREIGN KEY (sauid) REFERENCES results_sovi.social_vulnerability_family_structure_sauid_t("Sauid");

-- add fkey from sovi.sovi_census_canada
ALTER TABLE results_sovi.social_vulnerability_family_structure_sauid_t DROP CONSTRAINT IF EXISTS social_vulnerability_family_structure_sauid_t_fkey;
ALTER TABLE results_sovi.social_vulnerability_family_structure_sauid_t ADD CONSTRAINT social_vulnerability_family_structure_sauid_t_fkey FOREIGN KEY ("Sauid") REFERENCES sovi.sovi_census_canada(sauidt);

-- add fkey from sovi.sovi_index_canada
ALTER TABLE results_sovi.social_vulnerability_family_structure_sauid_t DROP CONSTRAINT IF EXISTS social_vulnerability_family_structure_sauid_t_fkey2;
ALTER TABLE results_sovi.social_vulnerability_family_structure_sauid_t ADD CONSTRAINT social_vulnerability_family_structure_sauid_t_fkey2 FOREIGN KEY ("Sauid") REFERENCES sovi.sovi_index_canada(sauidt);

-- add fkey from boundaries."Geometry_SAUID"
ALTER TABLE results_sovi.social_vulnerability_family_structure_sauid_t DROP CONSTRAINT IF EXISTS social_vulnerability_family_structure_sauid_t_fkey3;
ALTER TABLE results_sovi.social_vulnerability_family_structure_sauid_t ADD CONSTRAINT social_vulnerability_family_structure_sauid_t_fkey3 FOREIGN KEY ("Sauid") REFERENCES boundaries."Geometry_SAUID"("SAUIDt");



-- results_sovi.social_vulnerability_financial_agency_sauid_t
-- add pkey
ALTER TABLE results_sovi.social_vulnerability_financial_agency_sauid_t DROP CONSTRAINT IF EXISTS social_vulnerability_financial_agency_sauid_t_pkey;
ALTER TABLE results_sovi.social_vulnerability_financial_agency_sauid_t ADD PRIMARY KEY("Sauid");

-- add fkey to exposure.canada_exposure
ALTER TABLE exposure.canada_exposure DROP CONSTRAINT IF EXISTS canada_exposure_sovi_fkey2;
ALTER TABLE exposure.canada_exposure ADD CONSTRAINT canada_exposure_sovi_fkey2 FOREIGN KEY (sauid) REFERENCES results_sovi.social_vulnerability_financial_agency_sauid_t("Sauid");

-- add fkey from sovi.sovi_census_canada
ALTER TABLE results_sovi.social_vulnerability_financial_agency_sauid_t DROP CONSTRAINT IF EXISTS social_vulnerability_financial_agency_sauid_t_fkey;
ALTER TABLE results_sovi.social_vulnerability_financial_agency_sauid_t ADD CONSTRAINT social_vulnerability_financial_agency_sauid_t_fkey FOREIGN KEY ("Sauid") REFERENCES sovi.sovi_census_canada(sauidt);

-- add fkey from sovi.sovi_index_canada
ALTER TABLE results_sovi.social_vulnerability_financial_agency_sauid_t DROP CONSTRAINT IF EXISTS social_vulnerability_financial_agency_sauid_t_fkey2;
ALTER TABLE results_sovi.social_vulnerability_financial_agency_sauid_t ADD CONSTRAINT social_vulnerability_financial_agency_sauid_t_fkey2 FOREIGN KEY ("Sauid") REFERENCES sovi.sovi_index_canada(sauidt);

-- add fkey from boundaries."Geometry_SAUID"
ALTER TABLE results_sovi.social_vulnerability_financial_agency_sauid_t DROP CONSTRAINT IF EXISTS social_vulnerability_financial_agency_sauid_t_fkey3;
ALTER TABLE results_sovi.social_vulnerability_financial_agency_sauid_t ADD CONSTRAINT social_vulnerability_financial_agency_sauid_t_fkey3 FOREIGN KEY ("Sauid") REFERENCES boundaries."Geometry_SAUID"("SAUIDt");

-- results_sovi.social_vulnerability_housing_conditions_sauid_t
-- add pkey
ALTER TABLE results_sovi.social_vulnerability_housing_conditions_sauid_t DROP CONSTRAINT IF EXISTS social_vulnerability_housing_conditions_sauid_t_pkey;
ALTER TABLE results_sovi.social_vulnerability_housing_conditions_sauid_t ADD PRIMARY KEY("Sauid");

-- add fkey to exposure.canada_exposure
ALTER TABLE exposure.canada_exposure DROP CONSTRAINT IF EXISTS canada_exposure_sovi_fkey3;
ALTER TABLE exposure.canada_exposure ADD CONSTRAINT canada_exposure_sovi_fkey3 FOREIGN KEY (sauid) REFERENCES results_sovi.social_vulnerability_housing_conditions_sauid_t("Sauid");

-- add fkey from sovi.sovi_census_canada
ALTER TABLE results_sovi.social_vulnerability_housing_conditions_sauid_t DROP CONSTRAINT IF EXISTS social_vulnerability_housing_conditions_sauid_t_fkey;
ALTER TABLE results_sovi.social_vulnerability_housing_conditions_sauid_t ADD CONSTRAINT social_vulnerability_housing_conditions_sauid_t_fkey FOREIGN KEY ("Sauid") REFERENCES sovi.sovi_census_canada(sauidt);

-- add fkey from sovi.sovi_index_canada
ALTER TABLE results_sovi.social_vulnerability_housing_conditions_sauid_t DROP CONSTRAINT IF EXISTS social_vulnerability_housing_conditions_sauid_t_fkey2;
ALTER TABLE results_sovi.social_vulnerability_housing_conditions_sauid_t ADD CONSTRAINT social_vulnerability_housing_conditions_sauid_t_fkey2 FOREIGN KEY ("Sauid") REFERENCES sovi.sovi_index_canada(sauidt);

-- add fkey from boundaries."Geometry_SAUID"
ALTER TABLE results_sovi.social_vulnerability_housing_conditions_sauid_t DROP CONSTRAINT IF EXISTS social_vulnerability_housing_conditions_sauid_t_fkey3;
ALTER TABLE results_sovi.social_vulnerability_housing_conditions_sauid_t ADD CONSTRAINT social_vulnerability_housing_conditions_sauid_t_fkey3 FOREIGN KEY ("Sauid") REFERENCES boundaries."Geometry_SAUID"("SAUIDt");


-- results_sovi.social_vulnerability_individual_autonomy_sauid_t
-- add pkey
ALTER TABLE results_sovi.social_vulnerability_individual_autonomy_sauid_t DROP CONSTRAINT IF EXISTS social_vulnerability_individual_autonomy_sauid_t_pkey;
ALTER TABLE results_sovi.social_vulnerability_individual_autonomy_sauid_t ADD PRIMARY KEY("Sauid");

-- add fkey to exposure.canada_exposure
ALTER TABLE exposure.canada_exposure DROP CONSTRAINT IF EXISTS canada_exposure_sovi_fkey4;
ALTER TABLE exposure.canada_exposure ADD CONSTRAINT canada_exposure_sovi_fkey4 FOREIGN KEY (sauid) REFERENCES results_sovi.social_vulnerability_individual_autonomy_sauid_t("Sauid");

-- add fkey from sovi.sovi_census_canada
ALTER TABLE results_sovi.social_vulnerability_individual_autonomy_sauid_t DROP CONSTRAINT IF EXISTS social_vulnerability_individual_autonomy_sauid_t_fkey;
ALTER TABLE results_sovi.social_vulnerability_individual_autonomy_sauid_t ADD CONSTRAINT social_vulnerability_individual_autonomy_sauid_t_fkey FOREIGN KEY ("Sauid") REFERENCES sovi.sovi_census_canada(sauidt);

-- add fkey from sovi.sovi_index_canada
ALTER TABLE results_sovi.social_vulnerability_individual_autonomy_sauid_t DROP CONSTRAINT IF EXISTS social_vulnerability_individual_autonomy_sauid_t_fkey2;
ALTER TABLE results_sovi.social_vulnerability_individual_autonomy_sauid_t ADD CONSTRAINT social_vulnerability_individual_autonomy_sauid_t_fkey2 FOREIGN KEY ("Sauid") REFERENCES sovi.sovi_index_canada(sauidt);

-- add fkey from boundaries."Geometry_SAUID"
ALTER TABLE results_sovi.social_vulnerability_individual_autonomy_sauid_t DROP CONSTRAINT IF EXISTS social_vulnerability_individual_autonomy_sauid_t_fkey3;
ALTER TABLE results_sovi.social_vulnerability_individual_autonomy_sauid_t ADD CONSTRAINT social_vulnerability_individual_autonomy_sauid_t_fkey3 FOREIGN KEY ("Sauid") REFERENCES boundaries."Geometry_SAUID"("SAUIDt");