-- create multi hazard indicators

-- obtain min/max values FOR mh intensity calculations
DROP TABLE IF EXISTS lut.mh_intensity_canada_minmax CASCADE;

SELECT
MIN(pgv) AS "pgv_min",
MAX(pgv) AS "pgv_max",
MIN(pga) AS "pga_min",
MAX(pga) AS "pga_max",
MIN(mmi6) AS "mmi6_min",
MAX(mmi6) AS "mmi6_max",
MIN(mmi7) AS "mmi7_min",
MAX(mmi7) AS "mmi7_max",
MIN(mmi8) AS "mmi8_min",
MAX(mmi8) AS "mmi8_max",
MIN(tsun_ha) AS "tsun_min",
MAX(tsun_ha) AS "tsun_max",
MIN(fl200) AS "fl200_min",
MAX(fl200) AS "fl200_max",
MIN(fl500) AS "fl500_min",
MAX(fl500) AS "fl500_max",
MIN(fl1000) AS "fl1000_min",
MAX(fl1000) AS "fl1000_max",
MIN(lndsus) AS "lndsus_min",
MAX(lndsus) AS "lndsus_max",
MAX(fire) AS "fire_min",
MAX(fire) AS "fire_max",
MAX(cy100) AS "cy100_min",
MAX(cy100) AS "cy100_max",
MAX(cy250) AS "cy250_min",
MAX(cy250) AS "cy250_max",
MAX(cy500) AS "cy500_min",
MAX(cy500) AS "cy500_max",
MAX(cy1000) AS "cy1000_min",
MAX(cy1000) AS "cy1000_max"

INTO lut.mh_intensity_canada_minmax

FROM lut.mh_intensity_canada;



DROP VIEW IF EXISTS results.mh_intensity_multi_hazard_potential CASCADE;
CREATE VIEW results.mh_intensity_multi_hazard_potential AS 

-- 3.0 Natural Hazards
-- 3.1 Multi-Hazard
-- 3.1.1 Multi-Hazard Potential
SELECT 
a.sauidt AS "Sauid",
CAST(a.lon AS NUMERIC) AS "lon",
CAST(a.lat AS NUMERIC) AS "lat",

CAST(a.pgv AS NUMERIC) AS "PGV",
COALESCE(CAST((a.pgv - (SELECT pgv_min FROM lut.mh_intensity_canada_minmax))/NULLIF((SELECT pgv_max FROM lut.mh_intensity_canada_minmax) - (SELECT pgv_min FROM lut.mh_intensity_canada_minmax),0) AS NUMERIC),0) AS "PGVn",
CAST(a.pga AS NUMERIC) AS "PGA",
COALESCE(CAST((a.pga - (SELECT pga_min FROM lut.mh_intensity_canada_minmax))/NULLIF((SELECT pga_max FROM lut.mh_intensity_canada_minmax) - (SELECT pga_min FROM lut.mh_intensity_canada_minmax),0) AS NUMERIC),0) AS "PGAn",
CAST(a.mmi6 AS NUMERIC) AS "MMI6",
COALESCE(CAST((a.mmi6 - (SELECT mmi6_min FROM lut.mh_intensity_canada_minmax))/NULLIF((SELECT mmi6_max FROM lut.mh_intensity_canada_minmax) - (SELECT mmi6_min FROM lut.mh_intensity_canada_minmax),0) AS NUMERIC),0) AS "MMI6n",
CAST(a.mmi7 AS NUMERIC) AS "MMI7",
COALESCE(CAST((a.mmi7 - (SELECT mmi7_min FROM lut.mh_intensity_canada_minmax))/NULLIF((SELECT mmi7_max FROM lut.mh_intensity_canada_minmax) - (SELECT mmi7_min FROM lut.mh_intensity_canada_minmax),0) AS NUMERIC),0) AS "MMI7n",
CAST(a.mmi8 AS NUMERIC) AS "MMI8",
COALESCE(CAST((a.mmi8 - (SELECT mmi8_min FROM lut.mh_intensity_canada_minmax))/NULLIF((SELECT mmi8_max FROM lut.mh_intensity_canada_minmax) - (SELECT mmi8_min FROM lut.mh_intensity_canada_minmax),0) AS NUMERIC),0) AS "MMI8n",

CAST(a.tsun_ha AS NUMERIC) AS "Tsun",
COALESCE(CAST((a.tsun_ha - (SELECT tsun_min FROM lut.mh_intensity_canada_minmax))/NULLIF((SELECT tsun_max FROM lut.mh_intensity_canada_minmax) - (SELECT tsun_min FROM lut.mh_intensity_canada_minmax),0) AS NUMERIC),0) AS "Tsun_n",

CAST(a.fl200 AS NUMERIC) AS "Fl200",
COALESCE(CAST((a.fl200 - (SELECT fl200_min FROM lut.mh_intensity_canada_minmax))/NULLIF((SELECT fl200_max FROM lut.mh_intensity_canada_minmax) - (SELECT fl200_min FROM lut.mh_intensity_canada_minmax),0) AS NUMERIC),0) AS "Fl200_n",
CAST(a.fl500 AS NUMERIC) AS "Fl500",
COALESCE(CAST((a.fl500 - (SELECT fl500_min FROM lut.mh_intensity_canada_minmax))/NULLIF((SELECT fl500_max FROM lut.mh_intensity_canada_minmax) - (SELECT fl500_min FROM lut.mh_intensity_canada_minmax),0) AS NUMERIC),0) AS "Fl500_n",
CAST(a.fl1000 AS NUMERIC) AS "Fl1000",
COALESCE(CAST((a.fl1000 - (SELECT fl1000_min FROM lut.mh_intensity_canada_minmax))/NULLIF((SELECT fl1000_max FROM lut.mh_intensity_canada_minmax) - (SELECT fl1000_min FROM lut.mh_intensity_canada_minmax),0) AS NUMERIC),0) AS "Fl1000_n",

CAST(a.lndsus AS NUMERIC) AS "LndSus",
COALESCE(CAST((a.lndsus - (SELECT lndsus_min FROM lut.mh_intensity_canada_minmax))/NULLIF((SELECT lndsus_max FROM lut.mh_intensity_canada_minmax) - (SELECT lndsus_min FROM lut.mh_intensity_canada_minmax),0) AS NUMERIC),0) AS "LndSusn",

CAST(a.fire AS NUMERIC) AS "Fire",
COALESCE(CAST((a.fire - (SELECT fire_min FROM lut.mh_intensity_canada_minmax))/NULLIF((SELECT fire_max FROM lut.mh_intensity_canada_minmax) - (SELECT fire_min FROM lut.mh_intensity_canada_minmax),0) AS NUMERIC),0) AS "Firen",

CAST(a.cy100 AS NUMERIC) AS "Cy100",
COALESCE(CAST((a.cy100 - (SELECT cy100_min FROM lut.mh_intensity_canada_minmax))/NULLIF((SELECT cy100_max FROM lut.mh_intensity_canada_minmax) - (SELECT cy100_min FROM lut.mh_intensity_canada_minmax),0) AS NUMERIC),0) AS "Cy100n",
CAST(a.cy250 AS NUMERIC) AS "Cy250",
COALESCE(CAST((a.cy250 - (SELECT cy250_min FROM lut.mh_intensity_canada_minmax))/NULLIF((SELECT cy250_max FROM lut.mh_intensity_canada_minmax) - (SELECT cy250_min FROM lut.mh_intensity_canada_minmax),0) AS NUMERIC),0) AS "Cy250n",
CAST(a.cy500 AS NUMERIC) AS "Cy500",
COALESCE(CAST((a.cy500 - (SELECT cy500_min FROM lut.mh_intensity_canada_minmax))/NULLIF((SELECT cy500_max FROM lut.mh_intensity_canada_minmax) - (SELECT cy500_min FROM lut.mh_intensity_canada_minmax),0) AS NUMERIC),0) AS "Cy500n",
CAST(a.cy1000 AS NUMERIC) AS "Cy1000",
COALESCE(CAST((a.cy1000 - (SELECT cy1000_min FROM lut.mh_intensity_canada_minmax))/NULLIF((SELECT cy1000_max FROM lut.mh_intensity_canada_minmax) - (SELECT cy1000_min FROM lut.mh_intensity_canada_minmax),0) AS NUMERIC),0) AS "Cy1000n",

b.geom AS "geom_poly",
b.geompoint AS "geom_point"

FROM lut.mh_intensity_canada a
LEFT JOIN boundaries."Geometry SAUID" b on a.sauidt = b."SAUIDt"