-- create scenario risk building indicators
DROP VIEW IF EXISTS results_cast_text.dsra_sim6p8_cr2022_rlz_1_b0_scenario_rupture CASCADE;
CREATE VIEW results_cast_text.dsra_sim6p8_cr2022_rlz_1_b0_scenario_rupture AS 

-- 4.0 Earthquake Risk
-- 4.1 Scenario Hazard
-- 4.1.1 Scenario Rupture
SELECT 
a."AssetID",
f.source_type AS "Source_Type",
f.rupture_name AS "Rupture_Name",
f.magnitude AS "Magnitude",
f.rake AS "Rake",
CAST(CAST(f.lon AS NUMERIC) AS TEXT) AS "Hypo_Lon",
CAST(CAST(f.lat AS NUMERIC) AS TEXT) AS "Hypo_Lat",
CAST(CAST(f.depth AS NUMERIC) AS TEXT) AS "Hypo_Depth",
CAST(CAST(d."vs_lon" AS NUMERIC) AS TEXT) AS "vs30_Lon",
CAST(CAST(d."vs_lat" AS NUMERIC) AS TEXT) AS "vs30_Lat",
CAST(CAST(d.vs30 AS NUMERIC) AS TEXT) AS "vs30",
e.site_id AS "SiteID",
CAST(CAST(e.lon AS NUMERIC) AS TEXT) AS "SiteID_Lon",
CAST(CAST(e.lat AS NUMERIC) AS TEXT) AS "SiteID_Lat",
a."Realization" AS "Realization",
a."gmpe_Model" AS "gmpe_Model",
CAST(CAST(a."Weight" AS NUMERIC) AS TEXT) AS "Weight",
b.geom

FROM dsra.dsra_sim6p8_cr2022_rlz_1 a
LEFT JOIN psra.canada_exposure b ON a."AssetID" = b.id 
--LEFT JOIN lut.retrofit_costs c ON b.eqbldgtype = c."Eq_BldgType"
LEFT JOIN lut.vs30_bc_site_model_xref d ON a."AssetID" = d.id
LEFT JOIN lut.gmfdata_sitemesh_sim6p8_cr2022_37_xref e on b.id = e.id
LEFT JOIN ruptures.rupture_table f on f.rupture_name = a."Rupture_Abbr";


-- create scenario risk building indicators
DROP VIEW IF EXISTS results_cast_text.dsra_sim6p8_cr2022_rlz_1_b0_scenario_hazard CASCADE;
CREATE VIEW results_cast_text.dsra_sim6p8_cr2022_rlz_1_b0_scenario_hazard AS 

-- 4.0 Earthquake Risk
-- 4.1 Scenario Hazard
-- 4.1.2 Scenario Hazard
SELECT 
a."AssetID",
e."event_id" AS "EventID",
CAST(CAST(e."gmv_pgv" AS NUMERIC) AS TEXT) AS "PGV",
CAST(CAST(e."gmv_pga" AS NUMERIC) AS TEXT) AS "PGA",
CAST(CAST(e."gmv_SA(0.2)" AS NUMERIC) AS TEXT) AS "SA_0p2",
CAST(CAST(e."gmv_SA(0.3)" AS NUMERIC) AS TEXT) AS "SA_0p3",
CAST(CAST(e."gmv_SA(0.6)" AS NUMERIC) AS TEXT) AS "SA_0p6",
CAST(CAST(e."gmv_SA(1.0)" AS NUMERIC) AS TEXT) AS "SA_1p0",
CAST(CAST(0 AS NUMERIC) AS TEXT)AS "SA_2p0",  --"Spectral Acceleration (2.0s)" - change source to reflect 2.0 later
b.geom

FROM dsra.dsra_sim6p8_cr2022_rlz_1 a
LEFT JOIN psra.canada_exposure b ON a."AssetID" = b.id 
--LEFT JOIN lut.retrofit_costs c ON b.eqbldgtype = c."Eq_BldgType"
--LEFT JOIN lut.vs30_bc_site_model_xref d ON a."AssetID" = d.id
LEFT JOIN lut.gmfdata_sitemesh_sim6p8_cr2022_37_xref e on b.id = e.id;
--LEFT JOIN ruptures.rupture_table f on f.rupture_name = a."Rupture_Abbr";


-- create scenario risk building indicators
DROP VIEW IF EXISTS results_cast_text.dsra_sim6p8_cr2022_rlz_1_b0_damage_state CASCADE;
CREATE VIEW results_cast_text.dsra_sim6p8_cr2022_rlz_1_b0_damage_state AS 

-- 4.0 Earthquake Risk
-- 4.2 Building Performance
-- 4.2.1 Damage State
SELECT 
a."AssetID",
a."Rupture_Abbr",
f.magnitude AS "Source_Mag",
'b0' AS "Retrofit_Level",
a."Realization" AS "RealizationID", 
CAST(CAST(a."sD_None_b0" AS NUMERIC) AS TEXT) AS "sD_None",
CAST(CAST(a."sD_None_stdv_b0" AS NUMERIC) AS TEXT) AS "sD_None_stdv",
CAST(CAST(a."sD_Slight_b0" AS NUMERIC) AS TEXT) AS "sD_Slight",
CAST(CAST(a."sD_Slight_stdv_b0" AS NUMERIC) AS TEXT) AS "sD_Slight_stdv",
CAST(CAST(a."sD_Moderate_b0" AS NUMERIC) AS TEXT) AS "sD_Moderate",
CAST(CAST(a."sD_Moderate_stdv_b0" AS NUMERIC) AS TEXT) AS "sD_Moderate_stdv",
CAST(CAST(a."sD_Extensive_b0" AS NUMERIC) AS TEXT) AS "sD_Extensive",
CAST(CAST(a."sD_Extensive_stdv_b0" AS NUMERIC) AS TEXT) AS "sD_Extensive_stdv",
CAST(CAST(a."sD_Complete_b0" AS NUMERIC) AS TEXT) AS "sD_Complete",
CAST(CAST(a."sD_Complete_stdv_b0" AS NUMERIC) AS TEXT) AS "sD_Complete_stdv",
CAST(CAST(a."sD_Collapse_b0" AS NUMERIC) AS TEXT) AS "sD_Collapse",
b.geom

FROM dsra.dsra_sim6p8_cr2022_rlz_1 a
LEFT JOIN psra.canada_exposure b ON a."AssetID" = b.id 
--LEFT JOIN lut.retrofit_costs c ON b.eqbldgtype = c."Eq_BldgType"
--LEFT JOIN lut.vs30_bc_site_model_xref d ON a."AssetID" = d.id
--LEFT JOIN lut.gmfdata_sitemesh_sim6p8_cr2022_37_xref e on b.id = e.id
LEFT JOIN ruptures.rupture_table f on f.rupture_name = a."Rupture_Abbr";


-- create scenario risk building indicators
DROP VIEW IF EXISTS results_cast_text.dsra_sim6p8_cr2022_rlz_1_b0_recovery CASCADE;
CREATE VIEW results_cast_text.dsra_sim6p8_cr2022_rlz_1_b0_recovery AS 

-- 4.0 Earthquake Risk
-- 4.2 Building Performance
-- 4.2.2 Recovery
SELECT 
a."AssetID",
a."Rupture_Abbr",
f.magnitude AS "Source_Mag",
'b0' AS "Retrofit_Level",
a."Realization" AS "RealizationID", 
CAST(CAST(a."sC_Repair_b0" AS NUMERIC) AS TEXT) AS "sC_Repair",
CAST(CAST(a."sC_Construxn_b0" AS NUMERIC) AS TEXT) AS "SC_Construxn",
CAST(CAST(a."sC_Downtime_b0" AS NUMERIC) AS TEXT) AS "sC_Downtime",
b.geom

FROM dsra.dsra_sim6p8_cr2022_rlz_1 a
LEFT JOIN psra.canada_exposure b ON a."AssetID" = b.id 
--LEFT JOIN lut.retrofit_costs c ON b.eqbldgtype = c."Eq_BldgType"
--LEFT JOIN lut.vs30_bc_site_model_xref d ON a."AssetID" = d.id
--LEFT JOIN lut.gmfdata_sitemesh_sim6p8_cr2022_37_xref e on b.id = e.id
LEFT JOIN ruptures.rupture_table f on f.rupture_name = a."Rupture_Abbr";


-- create scenario risk building indicators
DROP VIEW IF EXISTS results_cast_text.dsra_sim6p8_cr2022_rlz_1_b0_casualties CASCADE;
CREATE VIEW results_cast_text.dsra_sim6p8_cr2022_rlz_1_b0_casualties AS 

-- 4.0 Earthquake Risk
-- 4.3 Afected People
-- 4.3.1 Casualties
SELECT
a."AssetID",
a."Rupture_Abbr",
f.magnitude AS "Source_Mag",
'b0' AS "Retrofit_Level",
a."Realization" AS "RealizationID",  
CAST(CAST(a."sC_CasDayL1_b0" AS NUMERIC) AS TEXT) AS "sC_CasDayL1",
CAST(CAST(a."sC_CasDayL2_b0" AS NUMERIC) AS TEXT) AS "sC_CasDayL2",
CAST(CAST(a."sC_CasDayL3_b0" AS NUMERIC) AS TEXT) AS "sC_CasDayL3",
CAST(CAST(a."sC_CasDayL4_b0" AS NUMERIC) AS TEXT) AS "sC_CasDayL4",
CAST(CAST(a."sC_CasNightL1_b0" AS NUMERIC) AS TEXT) AS "sC_CasNightL1",
CAST(CAST(a."sC_CasNightL2_b0" AS NUMERIC) AS TEXT) AS "sC_CasNightL2",
CAST(CAST(a."sC_CasNightL3_b0" AS NUMERIC) AS TEXT) AS "sC_CasNightL3",
CAST(CAST(a."sC_CasNightL4_b0" AS NUMERIC) AS TEXT) AS "sC_CasNightL4",
CAST(CAST(a."sC_CasTransitL1_b0" AS NUMERIC) AS TEXT) AS "sC_CasTransitL1",
CAST(CAST(a."sC_CasTransitL2_b0" AS NUMERIC) AS TEXT) AS "sC_CasTransitL2",
CAST(CAST(a."sC_CasTransitL3_b0" AS NUMERIC) AS TEXT) AS "sC_CasTransitL3",
CAST(CAST(a."sC_CasTransitL4_b0" AS NUMERIC) AS TEXT) AS "sC_CasTransitL4",
b.geom

FROM dsra.dsra_sim6p8_cr2022_rlz_1 a
LEFT JOIN psra.canada_exposure b ON a."AssetID" = b.id 
--LEFT JOIN lut.retrofit_costs c ON b.eqbldgtype = c."Eq_BldgType"
--LEFT JOIN lut.vs30_bc_site_model_xref d ON a."AssetID" = d.id
--LEFT JOIN lut.gmfdata_sitemesh_sim6p8_cr2022_37_xref e on b.id = e.id
LEFT JOIN ruptures.rupture_table f on f.rupture_name = a."Rupture_Abbr";


-- create scenario risk building indicators
DROP VIEW IF EXISTS results_cast_text.dsra_sim6p8_cr2022_rlz_1_b0_social_disruption CASCADE;
CREATE VIEW results_cast_text.dsra_sim6p8_cr2022_rlz_1_b0_social_disruption AS 

-- 4.0 Earthquake Risk
-- 4.3 Afected People
-- 4.3.2 Social Disruption
SELECT
a."AssetID",
a."Rupture_Abbr",
f.magnitude AS "Source_Mag",
'b0' AS "Retrofit_Level",
a."Realization" AS "RealizationID", 
CAST(CAST(a."sC_DisplRes_3_b0" AS NUMERIC) AS TEXT) AS "sC_DisplRes_3",
CAST(CAST(a."sC_DisplRes_30_b0" AS NUMERIC) AS TEXT) AS "sC_DisplRes_30",
CAST(CAST(a."sC_DisplRes_90_b0" AS NUMERIC) AS TEXT) AS "sC_DisplRes_90",
CAST(CAST(a."sC_DisplRes_360_b0" AS NUMERIC) AS TEXT) AS "sC_DisplRes_360",
CAST(CAST(a."sC_DisrupEmpl_30_b0" AS NUMERIC) AS TEXT) AS "sC_DisrupEmpl_30",
CAST(CAST(a."sC_DisrupEmpl_90_b0" AS NUMERIC) AS TEXT) AS "sC_DisrupEmpl_90",
CAST(CAST(a."sC_DisrupEmpl_180_b0" AS NUMERIC) AS TEXT) AS "sC_DisrupEmpl_180",
CAST(CAST(a."sC_DisrupEmpl_360_b0" AS NUMERIC) AS TEXT) AS "sC_DisrupEmpl_360",
CAST(CAST(a."sC_DebrisBW_b0" AS NUMERIC) AS TEXT) AS "sC_DebrisBW",
CAST(CAST(a."sC_DebrisC_b0" AS NUMERIC) AS TEXT) AS "sC_DebrisC",
b.geom

FROM dsra.dsra_sim6p8_cr2022_rlz_1 a
LEFT JOIN psra.canada_exposure b ON a."AssetID" = b.id 
--LEFT JOIN lut.retrofit_costs c ON b.eqbldgtype = c."Eq_BldgType"
--LEFT JOIN lut.vs30_bc_site_model_xref d ON a."AssetID" = d.id
--LEFT JOIN lut.gmfdata_sitemesh_sim6p8_cr2022_37_xref e on b.id = e.id
LEFT JOIN ruptures.rupture_table f on f.rupture_name = a."Rupture_Abbr";


-- create scenario risk building indicators
DROP VIEW IF EXISTS results_cast_text.dsra_sim6p8_cr2022_rlz_1_b0_economic_loss CASCADE;
CREATE VIEW results_cast_text.dsra_sim6p8_cr2022_rlz_1_b0_economic_loss AS 

-- 4.0 Earthquake Risk
-- 4.4 Economic Security
-- 4.4.1 Economic Loss
SELECT
a."AssetID",
a."Rupture_Abbr",
f.magnitude AS "Source_Mag",
'b0' AS "Retrofit_Level",
a."Realization" AS "RealizationID", 
CAST(CAST(a."sL_Str_b0" + a."sL_NStr_b0" + a."sL_Cont_b0" AS NUMERIC) AS TEXT) AS "sL_Asset",
CAST(CAST(a."sL_Str_b0" + a."sL_NStr_b0" AS NUMERIC) AS TEXT) AS "sL_Bldg",
CAST(CAST(COALESCE((a."sL_Str_b0" + a."sL_NStr_b0") / NULLIF((a."sL_Str_b0" + a."sL_NStr_b0" + a."sL_Cont_b0"),0),0) AS NUMERIC) AS TEXT) AS "sL_BldgRatio",
CAST(CAST(a."sL_Str_b0" AS NUMERIC) AS TEXT) AS "sL_Str",
CAST(CAST(a."sL_Str_stdv_b0" AS NUMERIC) AS TEXT) AS "sL_Str_stdv",
CAST(CAST(a."sL_NStr_b0" AS NUMERIC) AS TEXT) AS "sL_NStr",
CAST(CAST(a."sL_NStr_stdv_b0" AS NUMERIC) AS TEXT) AS "sL_NStr_stdv",
CAST(CAST(a."sL_Cont_b0" AS NUMERIC) AS TEXT) AS "sL_Cont",
CAST(CAST(a."sL_Cont_stdv_b0" AS NUMERIC) AS TEXT) AS "sL_Cont_stdv",
CAST(CAST(a."sL_Fatalities_b0" AS NUMERIC) AS TEXT) AS "sL_Fatality",
CAST(CAST(a."sL_Fatalities_stdv_b0" AS NUMERIC) AS TEXT) AS "sL_Fatality_stdv",
b.geom

FROM dsra.dsra_sim6p8_cr2022_rlz_1 a
LEFT JOIN psra.canada_exposure b ON a."AssetID" = b.id 
--LEFT JOIN lut.retrofit_costs c ON b.eqbldgtype = c."Eq_BldgType"
--LEFT JOIN lut.vs30_bc_site_model_xref d ON a."AssetID" = d.id
--LEFT JOIN lut.gmfdata_sitemesh_sim6p8_cr2022_37_xref e on b.id = e.id
LEFT JOIN ruptures.rupture_table f on f.rupture_name = a."Rupture_Abbr";