-- create scenario risk building indicators
DROP VIEW IF EXISTS results.dsra_sim6p8_cr2022_rlz_0_r1_scenario_rupture_agg_view;
CREATE VIEW results.dsra_sim6p8_cr2022_rlz_0_r1_scenario_rupture_agg_view AS 

-- 4.0 Earthquake Risk
-- 4.1 Scenario Hazard
-- 4.1.1 Scenario Rupture
SELECT 
DISTINCT(b.sauid) AS "Sauid",
f.source_type AS "Source_Type",
f.rupture_name AS "Rupture_Name",
f.magnitude AS "Magnitude",
'r1' AS "Retrofit",
g.geom AS "geom_poly",
g.geompoint AS "geom_point"


FROM dsra.dsra_sim6p8_cr2022_rlz_0 a
LEFT JOIN psra.canada_exposure b ON a."AssetID" = b.id 
--LEFT JOIN lut.retrofit_costs c ON b.eqbldgtype = c."Eq_BldgType"
--LEFT JOIN lut.vs30_bc_site_model_xref d ON a."AssetID" = d.id
--LEFT JOIN lut.gmfdata_sitemesh_sim6p8_cr2022_37_xref e on b.id = e.id
LEFT JOIN ruptures.rupture_table f on f.rupture_name = a."Rupture_Abbr"
LEFT JOIN boundaries."Geometry SAUID" g on b.sauid = g."SAUIDt";


-- create scenario risk building indicators
DROP VIEW IF EXISTS results.dsra_sim6p8_cr2022_rlz_0_r1_damage_state_agg;
CREATE VIEW results.dsra_sim6p8_cr2022_rlz_0_r1_damage_state_agg AS 

-- 4.0 Earthquake Risk
-- 4.2 Building Performance
-- 4.2.1 Damage State
SELECT 
b.sauid AS "Sauid",
CAST(SUM(a."sD_None_r1") AS NUMERIC) AS "sD_NoneT",
CAST(AVG(a."sD_None_stdv_r1") AS NUMERIC) AS "sD_NoneA_stdv",
CAST(SUM(a."sD_Slight_r1") AS NUMERIC) AS "sD_SlightT",
CAST(AVG(a."sD_Slight_stdv_r1") AS NUMERIC) AS "sD_SlightA_stdv",
CAST(SUM(a."sD_Moderate_r1") AS NUMERIC) AS "sD_ModerateT",
CAST(AVG(a."sD_Moderate_stdv_r1") AS NUMERIC) AS "sD_ModerateA_stdv",
CAST(SUM(a."sD_Extensive_r1") AS NUMERIC) AS "sD_ExtensiveT",
CAST(AVG(a."sD_Extensive_stdv_r1") AS NUMERIC) AS "sD_ExtensiveA_stdv",
CAST(SUM(a."sD_Complete_r1") AS NUMERIC) AS "sD_CompleteT",
CAST(AVG(a."sD_Complete_stdv_r1") AS NUMERIC) AS "sD_CompleteA_stdv",
CAST(SUM(a."sD_Collapse_r1") AS NUMERIC) AS "sD_CollapseT",
g.geom AS "geom_poly",
g.geompoint AS "geom_point"

FROM dsra.dsra_sim6p8_cr2022_rlz_0 a
LEFT JOIN psra.canada_exposure b ON a."AssetID" = b.id 
--LEFT JOIN lut.retrofit_costs c ON b.eqbldgtype = c."Eq_BldgType"
--LEFT JOIN lut.vs30_bc_site_model_xref d ON a."AssetID" = d.id
--LEFT JOIN lut.gmfdata_sitemesh_sim6p8_cr2022_37_xref e on b.id = e.id
--LEFT JOIN ruptures.rupture_table f on f.rupture_name = a."Rupture_Abbr"
LEFT JOIN boundaries."Geometry SAUID" g on b.sauid = g."SAUIDt"
GROUP BY b.sauid, g.geom, g.geompoint;


-- create scenario risk building indicators
DROP VIEW IF EXISTS results.dsra_sim6p8_cr2022_rlz_0_r1_functional_use_agg;
CREATE VIEW results.dsra_sim6p8_cr2022_rlz_0_r1_functional_use_agg AS 

-- 2.0 Physical Exposure
-- 2.1 Buildings
-- 2.1.1 Functional Use
SELECT 
a.sauid AS "Sauid",
c.landuse AS "LandUse",
CAST(SUM(CASE WHEN a.genocc ='Residential-LD' THEN a.number ELSE 0 END) AS NUMERIC) AS "Res_LD",
CAST(SUM(CASE WHEN a.genocc ='Residential-MD' THEN a.number ELSE 0 END) AS NUMERIC) AS "Res_MD",
CAST(SUM(CASE WHEN a.genocc ='Residential-HD' THEN a.number ELSE 0 END) AS NUMERIC) AS "Res_HD",
CAST(SUM(CASE WHEN a.genocc ='Commercial' THEN a.number ELSE 0 END) AS NUMERIC) AS "Comm",
CAST(SUM(CASE WHEN a.genocc ='Industrial' THEN a.number ELSE 0 END) AS NUMERIC) AS "Ind",
CAST(SUM(CASE WHEN a.genocc ='Civic' THEN a.number ELSE 0 END) AS NUMERIC) AS "Civic",
CAST(SUM(CASE WHEN a.genocc ='Agricultural' THEN a.number ELSE 0 END) AS NUMERIC) AS "Agricultural",
CAST(SUM(CASE WHEN a.genocc ='Residential-LD' THEN a.number ELSE 0 END) / c.people_du AS NUMERIC) AS "SF_Hshlds",
CAST((SUM(CASE WHEN a.genocc ='Residential-MD' THEN a.number ELSE 0 END) + SUM(CASE WHEN a.genocc ='Residential-HD' THEN a.number ELSE 0 END)) / c.people_du AS NUMERIC) AS "MF_Hshlds",
g.geom AS "geom_poly",
g.geompoint AS "geom_point"

FROM psra.canada_exposure a
--LEFT JOIN lut.retrofit_costs b ON a.eqbldgtype = b."Eq_BldgType"
LEFT JOIN lut.census_2016_canada c ON a.sauid = c.sauidt
LEFT JOIN boundaries."Geometry SAUID" g on a.sauid = g."SAUIDt"
GROUP BY a.sauid,c.landuse,c.people_du,g.geom,g.geompoint;


-- create scenario risk building indicators
DROP VIEW IF EXISTS results.dsra_sim6p8_cr2022_rlz_0_r1_casualties_agg;
CREATE VIEW results.dsra_sim6p8_cr2022_rlz_0_r1_casualties_agg AS 

-- 4.0 Earthquake Risk
-- 4.3 Afected People
-- 4.3.1 Casualties
SELECT
b.sauid AS "Sauid",
CAST(SUM(a."sL_Fatalities_r1") AS NUMERIC) AS "sL_FatalityT",
CAST(AVG(a."sL_Fatalities_stdv_r1") AS NUMERIC) AS "sL_FatalityA_stdv",
CAST(SUM(a."sC_CasDayL1_r1") AS NUMERIC) AS "sC_CasDayL1T",
CAST(SUM(a."sC_CasDayL2_r1") AS NUMERIC) AS "sC_CasDayL2T",
CAST(SUM(a."sC_CasDayL3_r1") AS NUMERIC) AS "sC_CasDayL3T",
CAST(SUM(a."sC_CasDayL4_r1") AS NUMERIC) AS "sC_CasDayL4T",
CAST(SUM(a."sC_CasNightL1_r1") AS NUMERIC) AS "sC_CasNightL1T",
CAST(SUM(a."sC_CasNightL2_r1") AS NUMERIC) AS "sC_CasNightL2T",
CAST(SUM(a."sC_CasNightL3_r1") AS NUMERIC) AS "sC_CasNightL3T",
CAST(SUM(a."sC_CasNightL4_r1") AS NUMERIC) AS "sC_CasNightL4T",
CAST(SUM(a."sC_CasTransitL1_r1") AS NUMERIC) AS "sC_CasTransitL1T",
CAST(SUM(a."sC_CasTransitL2_r1") AS NUMERIC) AS "sC_CasTransitL2T",
CAST(SUM(a."sC_CasTransitL3_r1") AS NUMERIC) AS "sC_CasTransitL3T",
CAST(SUM(a."sC_CasTransitL4_r1") AS NUMERIC) AS "sC_CasTransitL4T",
g.geom AS "geom_poly",
g.geompoint AS "geom_point"

FROM dsra.dsra_sim6p8_cr2022_rlz_0 a
LEFT JOIN psra.canada_exposure b ON a."AssetID" = b.id 
--LEFT JOIN lut.retrofit_costs c ON b.eqbldgtype = c."Eq_BldgType"
--LEFT JOIN lut.vs30_bc_site_model_xref d ON a."AssetID" = d.id
--LEFT JOIN lut.gmfdata_sitemesh_sim6p8_cr2022_37_xref e on b.id = e.id
--LEFT JOIN ruptures.rupture_table f on f.rupture_name = a."Rupture_Abbr"
LEFT JOIN boundaries."Geometry SAUID" g on b.sauid = g."SAUIDt"
GROUP BY b.sauid, g.geom, g.geompoint;


-- create scenario risk building indicators
DROP VIEW IF EXISTS results.dsra_sim6p8_cr2022_rlz_0_r1_social_disruption_agg;
CREATE VIEW results.dsra_sim6p8_cr2022_rlz_0_r1_social_disruption_agg AS 

-- 4.0 Earthquake Risk
-- 4.3 Afected People
-- 4.3.2 Social Disruption
SELECT
b.sauid AS "Sauid",
CAST(SUM(a."sC_DisplRes_3_r1")/h.people_du AS NUMERIC) AS "sC_DisplHshld_3T",
CAST(SUM(a."sC_DisplRes_30_r1")/h.people_du AS NUMERIC) AS "sC_DisplHshld_30T",
CAST(SUM(a."sC_DisplRes_90_r1")/h.people_du AS NUMERIC) AS "sC_DisplHshld_90T",
CAST(SUM(a."sC_DisplRes_180_r1")/h.people_du AS NUMERIC) AS "sC_DisplHshld_180T",
CAST(SUM(a."sC_DisplRes_360_r1")/h.people_du AS NUMERIC) AS "sC_DisplHshld_360T",
CAST(SUM(a."sC_DisrupEmpl_30_r1") AS NUMERIC) AS "sC_DisrupEmpl_30T",
CAST(SUM(a."sC_DisrupEmpl_90_r1") AS NUMERIC) AS "sC_DisrupEmpl_90T",
CAST(SUM(a."sC_DisrupEmpl_180_r1") AS NUMERIC) AS "sC_DisrupEmpl_180T",
CAST(SUM(a."sC_DisrupEmpl_360_r1") AS NUMERIC) AS "sC_DisrupEmpl_360T",
g.geom AS "geom_poly",
g.geompoint AS "geom_point"

FROM dsra.dsra_sim6p8_cr2022_rlz_0 a
LEFT JOIN psra.canada_exposure b ON a."AssetID" = b.id 
--LEFT JOIN lut.retrofit_costs c ON b.eqbldgtype = c."Eq_BldgType"
--LEFT JOIN lut.vs30_bc_site_model_xref d ON a."AssetID" = d.id
--LEFT JOIN lut.gmfdata_sitemesh_sim6p8_cr2022_37_xref e on b.id = e.id
--LEFT JOIN ruptures.rupture_table f on f.rupture_name = a."Rupture_Abbr"
LEFT JOIN boundaries."Geometry SAUID" g on b.sauid = g."SAUIDt"
LEFT JOIN lut.census_2016_canada h on b.sauid = h.sauidt
GROUP BY b.sauid, g.geom, g.geompoint, h.people_du;


-- create scenario risk building indicators
DROP VIEW IF EXISTS results.dsra_sim6p8_cr2022_rlz_0_r1_economic_loss_agg;
CREATE VIEW results.dsra_sim6p8_cr2022_rlz_0_r1_economic_loss_agg AS 

-- 4.0 Earthquake Risk
-- 4.4 Economic Security
-- 4.4.1 Economic Loss
SELECT
b.sauid AS "Sauid",
CAST(SUM(a."sL_Str_r1" + a."sL_NStr_r1" + a."sL_Cont_r1") AS NUMERIC) AS "sL_AssetT",
CAST(SUM(a."sL_Str_r1" + a."sL_NStr_r1") AS NUMERIC) AS "sL_BldgT",
CAST((COALESCE((AVG(a."sL_Str_r1" + a."sL_NStr_r1"))/ NULLIF(AVG((a."sL_Str_r1" + a."sL_NStr_r1" + a."sL_Cont_r1")),0),0)) AS NUMERIC) AS "sL_BldgRatioA",
CAST(SUM(a."sL_Str_r1") AS NUMERIC) AS "sL_StrT",
CAST(AVG(a."sL_Str_stdv_r1") AS NUMERIC) AS "sL_StrA_stdv",
CAST(SUM(a."sL_NStr_r1") AS NUMERIC) AS "sL_NStr",
CAST(AVG(a."sL_NStr_stdv_r1") AS NUMERIC) AS "sL_NStrA_stdv",
CAST(SUM(a."sL_Cont_r1") AS NUMERIC) AS "sL_ContT",
CAST(AVG(a."sL_Cont_stdv_r1") AS NUMERIC) AS "sL_ContA_stdv",
g.geom AS "geom_poly",
g.geompoint AS "geom_point"

FROM dsra.dsra_sim6p8_cr2022_rlz_0 a
LEFT JOIN psra.canada_exposure b ON a."AssetID" = b.id 
--LEFT JOIN lut.retrofit_costs c ON b.eqbldgtype = c."Eq_BldgType"
--LEFT JOIN lut.vs30_bc_site_model_xref d ON a."AssetID" = d.id
--LEFT JOIN lut.gmfdata_sitemesh_sim6p8_cr2022_37_xref e on b.id = e.id
--LEFT JOIN ruptures.rupture_table f on f.rupture_name = a."Rupture_Abbr"
LEFT JOIN boundaries."Geometry SAUID" g on b.sauid = g."SAUIDt"
GROUP BY b.sauid, g.geom, g.geompoint;