-- create scenario risk building indicators all
DROP VIEW IF EXISTS results.dsra_sim6p8_cr2022_rlz_0_b0_partial_retrofit_agg_view;
CREATE VIEW results.dsra_sim6p8_cr2022_rlz_0_b0_partial_retrofit_agg_view AS 

-- 4.0 Earthquake Risk
-- 4.5 Disaster Risk Reduction
-- 4.5.1 Partial Retrofit
SELECT
b.sauid AS "Sauid",
f.source_type AS "Source_Type",
f.rupture_name AS "Rupture_Name",
f.magnitude AS "Magnitude",
'b0' AS "Retrofit",
SUM(c."CAD_RetrofitCost_Bldg") AS "Retrofit_Cost",
--SUM((a."sD_Extensive_b0"*0.3) + (a."sD_Complete_b0"*0.2)) AS "sD_Failure_b0",
--SUM((a."sD_Extensive_r1"*0.3) + (a."sD_Complete_r1"*0.2)) AS "sD_Failure_r1",
SUM(((a."sD_Extensive_b0"*0.3) + (a."sD_Complete_b0"*0.2)) - ((a."sD_Extensive_r1"*0.3) + (a."sD_Complete_r1"*0.2))) AS "sDR_Failure_r1",
--SUM(a."sD_Collapse_b0") AS "sD_Collapse_b0",
--SUM(a."sD_Collapse_r1") AS "sD_Collapse_r1",
SUM(a."sD_Collapse_b0" - a."sD_Collapse_r1") AS "sDR_Collapse_r1",
--SUM(a."sD_Extensive_b0") AS "sD_YellowTag_b0",
--SUM(a."sD_Extensive_r1") AS "sD_YellowTag_r1",
SUM(a."sD_Extensive_b0" - a."sD_Extensive_r1") AS "sDR_YellowTag_r1",
--SUM(a."sD_Complete_b0") AS "sD_RedTag_b0",
--SUM(a."sD_Complete_r1") AS "sD_RedTag_r1",
SUM(a."sD_Complete_b0" - a."sD_Complete_r1") AS "sDR_regTag_r1",
--SUM(a."sC_Downtime_b0")/(SUM(b.number)) AS "sC_Downtime_b0",
--SUM(a."sC_Downtime_r1")/(SUM(b.number)) AS "sC_Downtime_r1",
SUM(a."sC_Downtime_b0")/(SUM(b.number)) - SUM(a."sC_Downtime_r1")/(SUM(b.number))  AS "sCR_Downtime_r1",
--SUM(a."sC_DebrisBW_b0" + a."sC_DebrisC_b0") AS "sC_Debris_total_b0",
--SUM(a."sC_DebrisBW_r1" + a."sC_DebrisC_r1") AS "sC_Debris_total_r1",
SUM(a."sC_DebrisBW_b0" + a."sC_DebrisC_b0") - SUM(a."sC_DebrisBW_r1" + a."sC_DebrisC_r1") as "sCR_Debris_r1",
--SUM(a."sL_Fatalities_b0") AS "sL_FatalityT_b0",
--SUM(a."sL_Fatalities_r1") AS "sL_FatalityT_r1",
SUM(a."sL_Fatalities_b0" - a."sL_Fatalities_r1") AS "sLR_Fatality_r1",
--SUM(a."sC_CasDayL4_b0") AS "sC_CasDay_crit_b0",
--SUM(a."sC_CasDayL4_r1") AS "sC_CasDay_crit_r1",
SUM(a."sC_CasDayL4_b0" - a."sC_CasDayL4_r1") AS "sCR_CritCasDay_r1",
0 AS "sCR_Shelter_r1",	-- TBD
--SUM(a."sC_DisplRes_90_b0")/h.people_du AS "sC_DHshld_90_b0",
--SUM(a."sC_DisplRes_90_r1")/h.people_du AS "sC_DHshld_90_r1",
SUM(a."sC_DisplRes_90_b0")/h.people_du - SUM(a."sC_DisplRes_90_r1")/h.people_du AS "sCR_DHshld_90_r1",
--SUM(a."sL_Str_b0" + a."sL_NStr_b0" + a."sL_Cont_b0") AS "sL_AssetLoss_b0",
--SUM(a."sL_Str_r1" + a."sL_NStr_r1" + a."sL_Cont_r1") AS "sL_AssetLoss_r1",
SUM(a."sL_Str_b0" + a."sL_NStr_b0" + a."sL_Cont_b0") - SUM(a."sL_Str_r1" + a."sL_NStr_r1" + a."sL_Cont_r1") AS "sLR_AssetLoss_r1",
0 AS "sLR_BCR_r1",	--TBD
0 AS "sLR_RoI_r1",	--TBD
g.geom AS "geom_poly",
g.geompoint AS "geom_point"

FROM dsra.dsra_sim6p8_cr2022_rlz_0 a
LEFT JOIN psra.canada_exposure b ON a."AssetID" = b.id 
LEFT JOIN lut.retrofit_costs c ON b.eqbldgtype = c."Eq_BldgType"
--LEFT JOIN lut.vs30_bc_site_model_xref d ON a."AssetID" = d.id
--LEFT JOIN lut.gmfdata_sitemesh_sim6p8_cr2022_37_xref e on b.id = e.id
LEFT JOIN ruptures.rupture_table f on f.rupture_name = a."Rupture_Abbr"
LEFT JOIN boundaries."Geometry SAUID" g on b.sauid = g."SAUIDt"
LEFT JOIN lut.census_2016_canada h on b.sauid = h.sauidt
GROUP BY b.sauid, g.geom, g.geompoint, f.source_type, f.rupture_name, f.magnitude,h.people_du;