-- create physical exposure indicators
DROP VIEW IF EXISTS results.canada_exposure_portfolio CASCADE;
CREATE VIEW results.canada_exposure_portfolio AS 

-- 2.0 Physical Exposure
-- 2.1 Buildings
-- 2.0.1 Portfolio
SELECT 
a.id AS "AssetID",
a.sauid AS "Sauid",
CAST(CAST(ROUND(CAST(a.lon AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "Asset_Lon",
CAST(CAST(ROUND(CAST(a.lat AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "Asset_Lat",
CAST(CAST(ROUND(CAST(a.number AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "BldNum",
CAST(CAST(ROUND(CAST(b."BldgArea_ft2" AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "BldgArea_ft2",
a.geom

FROM psra.canada_exposure a
LEFT JOIN lut.retrofit_costs b ON a.eqbldgtype = b."Eq_BldgType";


-- create physical exposure indicators
DROP VIEW IF EXISTS results.canada_exposure_functional_use CASCADE;
CREATE VIEW results.canada_exposure_functional_use AS 

-- 2.0 Physical Exposure
-- 2.1 Buildings
-- 2.1.1 Functional Use
SELECT 
a.id AS "AssetID",
a.landusetyp AS "LandUse",
a.genocc AS "Occ_General",
a.eqocctype AS "Occ_Specific",
a.geom

FROM psra.canada_exposure a;


-- create physical exposure indicators
DROP VIEW IF EXISTS results.canada_exposure_construction CASCADE;
CREATE VIEW results.canada_exposure_construction AS 

-- 2.0 Physical Exposure
-- 2.1 Buildings
-- 2.1.2 Construction
SELECT 
a.id AS "AssetID",
a.landusetyp AS "LandUse",
a.bldggen AS "Type_General",
a.eqbldgtype AS "Type_Specific",
a.eqdeslev AS "Design_Level",
a.geom

FROM psra.canada_exposure a;


-- create physical exposure indicators
DROP VIEW IF EXISTS results.canada_exposure_replacement_cost CASCADE;
CREATE VIEW results.canada_exposure_replacement_cost AS 

-- 2.0 Physical Exposure
-- 2.1 Buildings
-- 2.1.2 Replacement Cost
SELECT 
a.id AS "AssetID",
CAST(CAST(ROUND(CAST(a.structural AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "StrCost",
CAST(CAST(ROUND(CAST(a.nonstructural AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "NStrCost",
CAST(CAST(ROUND(CAST(a.contents AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "ContCost",
CAST(CAST(ROUND(CAST(a.structural + a.nonstructural + a.contents AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "AssetCost",
CAST(CAST(ROUND(CAST(a.structural + a.nonstructural AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "BldgCost",
CAST(CAST(ROUND(CAST(b."CAD_RetrofitCost_Bldg" AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "RetrofitCost",
a.geom

FROM psra.canada_exposure a
LEFT JOIN lut.retrofit_costs b ON a.eqbldgtype = b."Eq_BldgType";


-- create physical exposure indicators
DROP VIEW IF EXISTS results.canada_exposure_building_occupancy CASCADE;
CREATE VIEW results.canada_exposure_building_occupancy AS 

-- 2.0 Physical Exposure
-- 2.3 Buildings
-- 2.3.1 Building Occupancy
SELECT 
a.id AS "AssetID",
CAST(CAST(ROUND(CAST(a.day AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "DayPop",
CAST(CAST(ROUND(CAST(a.night AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "NightPop",
CAST(CAST(ROUND(CAST(a.transit AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "TransitPop",
a.geom

FROM psra.canada_exposure a;