-- create physical exposure indicators
DROP VIEW IF EXISTS results.canada_exposure_building_occupancy_agg_view;
CREATE VIEW results.canada_exposure_building_occupancy_agg_view AS 

-- 2.0 Physical Exposure
-- 2.3 People
-- 2.3.1 Building Occupancy
SELECT 
a.sauid AS "Sauid",
CAST(c.censuspop AS NUMERIC) AS "CensusPop",
CAST(SUM(a.day) AS NUMERIC) AS "DayPopT",
CAST(SUM(a.night) AS NUMERIC) AS "NightPopT",
CAST(SUM(a.transit) AS NUMERIC) AS "TransitPopT",
d.geom AS "geom_poly",
d.geompoint AS "geom_point"

FROM psra.canada_exposure a
--LEFT JOIN lut.retrofit_costs b ON a.eqbldgtype = b."Eq_BldgType"
LEFT JOIN lut.census_2016_canada c ON a.sauid = c.sauidt
LEFT JOIN boundaries."Geometry SAUID" d on a.sauid = d."SAUIDt"
GROUP BY a.sauid,c.censuspop,d.geom,d.geompoint;