-- create multi hazard indicators
DROP VIEW IF EXISTS results.mh_intensity_multi_hazard_potential CASCADE;
CREATE VIEW results.mh_intensity_multi_hazard_potential AS 

-- 3.0 Natural Hazards
-- 3.1 Multi-Hazard
-- 3.1.1 Multi-Hazard Potential
SELECT 
a.sauidt AS "Sauid",
CAST(a.lon AS NUMERIC) AS "lon",
CAST(a.lat AS NUMERIC) AS "lat",
b.geom AS "geom_poly",
b.geompoint AS "geom_point"

FROM lut.mh_intensity_canada a
LEFT JOIN boundaries."Geometry SAUID" b on a.sauidt = b."SAUIDt";