
DROP TABLE IF EXISTS lut.s_sitemesh_SIM6p8_CR2022_37;


-- create table
CREATE TABLE lut.s_sitemesh_SIM6p8_CR2022_37(
    site_id varchar,
    lon float,
    lat float
    
);

-- import exposure from csv
COPY lut.s_sitemesh_SIM6p8_CR2022_37(site_id, lon, lat)
    FROM 'C:\GitHub\opendrr-data-store\sample-datasets\model-outputs\scenario-hazard\s_sitemesh_SIM6p8_CR2022_37.csv'
        WITH 
          DELIMITER AS ','
          CSV HEADER ;

