-- script to generate the collapse probability LUT
DROP TABLE IF EXISTS LUT_PSRA_collapse_probability;


-- create tables
CREATE TABLE LUT_PSRA_collapse_probability(
    typology varchar,
    EqBldgType varchar,
    collapse_pc float

);


-- import results from csv
COPY LUT_PSRA_collapse_probability (typology, EqBldgType, collapse_pc)
    FROM 'C:\Workspace\eRisk_CA\PSRA_sample_data\collapse_probability_LUT.csv'
        WITH 
          DELIMITER AS ','
          CSV HEADER ;

