-- create views of PSRA indicators by province for easier access

DROP VIEW IF EXISTS psra_indicators_all_baseline_NL, psra_indicators_all_baseline_PE, psra_indicators_all_baseline_NS, psra_indicators_all_baseline_NB,
                    psra_indicators_all_baseline_QC, psra_indicators_all_baseline_ON, psra_indicators_all_baseline_MB, psra_indicators_all_baseline_SK,
                    psra_indicators_all_baseline_AB, psra_indicators_all_baseline_BC, psra_indicators_all_baseline_YT, psra_indicators_all_baseline_NT, 
                    psra_indicators_all_baseline_NU,

                    psra_indicators_buildingperformance_baseline_NL, psra_indicators_buildingperformance_baseline_PE, psra_indicators_buildingperformance_baseline_NS, psra_indicators_buildingperformance_baseline_NB,
                    psra_indicators_buildingperformance_baseline_QC, psra_indicators_buildingperformance_baseline_ON, psra_indicators_buildingperformance_baseline_MB, psra_indicators_buildingperformance_baseline_SK,
                    psra_indicators_buildingperformance_baseline_AB, psra_indicators_buildingperformance_baseline_BC, psra_indicators_buildingperformance_baseline_YT,
                    psra_indicators_buildingperformance_baseline_NT, psra_indicators_buildingperformance_baseline_NU,

                    psra_indicators_mortality_baseline_NL, psra_indicators_mortality_baseline_PE, psra_indicators_mortality_baseline_NS, psra_indicators_mortality_baseline_NB,
                    psra_indicators_mortality_baseline_QC, psra_indicators_mortality_baseline_ON, psra_indicators_mortality_baseline_MB, psra_indicators_mortality_baseline_SK,
                    psra_indicators_mortality_baseline_AB, psra_indicators_mortality_baseline_BC, psra_indicators_mortality_baseline_YT, psra_indicators_mortality_baseline_NT, 
                    psra_indicators_mortality_baseline_NU,

                    psra_indicators_affectedpeople_baseline_NL, psra_indicators_affectedpeople_baseline_PE, psra_indicators_affectedpeople_baseline_NS, psra_indicators_affectedpeople_baseline_NB,
                    psra_indicators_affectedpeople_baseline_QC, psra_indicators_affectedpeople_baseline_ON, psra_indicators_affectedpeople_baseline_MB, psra_indicators_affectedpeople_baseline_SK,
                    psra_indicators_affectedpeople_baseline_AB, psra_indicators_affectedpeople_baseline_BC, psra_indicators_affectedpeople_baseline_YT, psra_indicators_affectedpeople_baseline_NT, 
                    psra_indicators_affectedpeople_baseline_NU,

                    psra_indicators_economicsecurity_baseline_NL, psra_indicators_economicsecurity_baseline_PE, psra_indicators_economicsecurity_baseline_NS, psra_indicators_economicsecurity_baseline_NB,
                    psra_indicators_economicsecurity_baseline_QC, psra_indicators_economicsecurity_baseline_ON, psra_indicators_economicsecurity_baseline_MB, psra_indicators_economicsecurity_baseline_SK,
                    psra_indicators_economicsecurity_baseline_AB, psra_indicators_economicsecurity_baseline_BC, psra_indicators_economicsecurity_baseline_YT, psra_indicators_economicsecurity_baseline_NT, 
                    psra_indicators_economicsecurity_baseline_NU;


-- create psra_indicators_all_baseline for all provinces
CREATE VIEW psra_indicators_all_baseline_NL AS SELECT * FROM psra_indicators_all_baseline WHERE SAUID LIKE '10%';
CREATE VIEW psra_indicators_all_baseline_PE AS SELECT * FROM psra_indicators_all_baseline WHERE SAUID LIKE '11%';
CREATE VIEW psra_indicators_all_baseline_NS AS SELECT * FROM psra_indicators_all_baseline WHERE SAUID LIKE '12%';
CREATE VIEW psra_indicators_all_baseline_NB AS SELECT * FROM psra_indicators_all_baseline WHERE SAUID LIKE '13%';
CREATE VIEW psra_indicators_all_baseline_QC AS SELECT * FROM psra_indicators_all_baseline WHERE SAUID LIKE '24%';
CREATE VIEW psra_indicators_all_baseline_ON AS SELECT * FROM psra_indicators_all_baseline WHERE SAUID LIKE '35%';
CREATE VIEW psra_indicators_all_baseline_MB AS SELECT * FROM psra_indicators_all_baseline WHERE SAUID LIKE '46%';
CREATE VIEW psra_indicators_all_baseline_SK AS SELECT * FROM psra_indicators_all_baseline WHERE SAUID LIKE '47%';
CREATE VIEW psra_indicators_all_baseline_AB AS SELECT * FROM psra_indicators_all_baseline WHERE SAUID LIKE '48%';
CREATE VIEW psra_indicators_all_baseline_BC AS SELECT * FROM psra_indicators_all_baseline WHERE SAUID LIKE '59%';
CREATE VIEW psra_indicators_all_baseline_YT AS SELECT * FROM psra_indicators_all_baseline WHERE SAUID LIKE '60%';
CREATE VIEW psra_indicators_all_baseline_NT AS SELECT * FROM psra_indicators_all_baseline WHERE SAUID LIKE '61%';
CREATE VIEW psra_indicators_all_baseline_NU AS SELECT * FROM psra_indicators_all_baseline WHERE SAUID LIKE '62%';

-- create psra_indicators_buildingperformance_baseline for all provinces
CREATE VIEW psra_indicators_buildingperformance_baseline_NL AS SELECT * FROM psra_indicators_buildingperformance_baseline WHERE SAUID LIKE '10%';
CREATE VIEW psra_indicators_buildingperformance_baseline_PE AS SELECT * FROM psra_indicators_buildingperformance_baseline WHERE SAUID LIKE '11%';
CREATE VIEW psra_indicators_buildingperformance_baseline_NS AS SELECT * FROM psra_indicators_buildingperformance_baseline WHERE SAUID LIKE '12%';
CREATE VIEW psra_indicators_buildingperformance_baseline_NB AS SELECT * FROM psra_indicators_buildingperformance_baseline WHERE SAUID LIKE '13%';
CREATE VIEW psra_indicators_buildingperformance_baseline_QC AS SELECT * FROM psra_indicators_buildingperformance_baseline WHERE SAUID LIKE '24%';
CREATE VIEW psra_indicators_buildingperformance_baseline_ON AS SELECT * FROM psra_indicators_buildingperformance_baseline WHERE SAUID LIKE '35%';
CREATE VIEW psra_indicators_buildingperformance_baseline_MB AS SELECT * FROM psra_indicators_buildingperformance_baseline WHERE SAUID LIKE '46%';
CREATE VIEW psra_indicators_buildingperformance_baseline_SK AS SELECT * FROM psra_indicators_buildingperformance_baseline WHERE SAUID LIKE '47%';
CREATE VIEW psra_indicators_buildingperformance_baseline_AB AS SELECT * FROM psra_indicators_buildingperformance_baseline WHERE SAUID LIKE '48%';
CREATE VIEW psra_indicators_buildingperformance_baseline_BC AS SELECT * FROM psra_indicators_buildingperformance_baseline WHERE SAUID LIKE '59%';
CREATE VIEW psra_indicators_buildingperformance_baseline_YT AS SELECT * FROM psra_indicators_buildingperformance_baseline WHERE SAUID LIKE '60%';
CREATE VIEW psra_indicators_buildingperformance_baseline_NT AS SELECT * FROM psra_indicators_buildingperformance_baseline WHERE SAUID LIKE '61%';
CREATE VIEW psra_indicators_buildingperformance_baseline_NU AS SELECT * FROM psra_indicators_buildingperformance_baseline WHERE SAUID LIKE '62%';

-- create psra_indicators_mortality_baseline for all provinces
CREATE VIEW psra_indicators_mortality_baseline_NL AS SELECT * FROM psra_indicators_mortality_baseline WHERE SAUID LIKE '10%';
CREATE VIEW psra_indicators_mortality_baseline_PE AS SELECT * FROM psra_indicators_mortality_baseline WHERE SAUID LIKE '11%';
CREATE VIEW psra_indicators_mortality_baseline_NS AS SELECT * FROM psra_indicators_mortality_baseline WHERE SAUID LIKE '12%';
CREATE VIEW psra_indicators_mortality_baseline_NB AS SELECT * FROM psra_indicators_mortality_baseline WHERE SAUID LIKE '13%';
CREATE VIEW psra_indicators_mortality_baseline_QC AS SELECT * FROM psra_indicators_mortality_baseline WHERE SAUID LIKE '24%';
CREATE VIEW psra_indicators_mortality_baseline_ON AS SELECT * FROM psra_indicators_mortality_baseline WHERE SAUID LIKE '35%';
CREATE VIEW psra_indicators_mortality_baseline_MB AS SELECT * FROM psra_indicators_mortality_baseline WHERE SAUID LIKE '46%';
CREATE VIEW psra_indicators_mortality_baseline_SK AS SELECT * FROM psra_indicators_mortality_baseline WHERE SAUID LIKE '47%';
CREATE VIEW psra_indicators_mortality_baseline_AB AS SELECT * FROM psra_indicators_mortality_baseline WHERE SAUID LIKE '48%';
CREATE VIEW psra_indicators_mortality_baseline_BC AS SELECT * FROM psra_indicators_mortality_baseline WHERE SAUID LIKE '59%';
CREATE VIEW psra_indicators_mortality_baseline_YT AS SELECT * FROM psra_indicators_mortality_baseline WHERE SAUID LIKE '60%';
CREATE VIEW psra_indicators_mortality_baseline_NT AS SELECT * FROM psra_indicators_mortality_baseline WHERE SAUID LIKE '61%';
CREATE VIEW psra_indicators_mortality_baseline_NU AS SELECT * FROM psra_indicators_mortality_baseline WHERE SAUID LIKE '62%';

-- create psra_indicators_affectedpeople_baseline for all provinces
CREATE VIEW psra_indicators_affectedpeople_baseline_NL AS SELECT * FROM psra_indicators_affectedpeople_baseline WHERE SAUID LIKE '10%';
CREATE VIEW psra_indicators_affectedpeople_baseline_PE AS SELECT * FROM psra_indicators_affectedpeople_baseline WHERE SAUID LIKE '11%';
CREATE VIEW psra_indicators_affectedpeople_baseline_NS AS SELECT * FROM psra_indicators_affectedpeople_baseline WHERE SAUID LIKE '12%';
CREATE VIEW psra_indicators_affectedpeople_baseline_NB AS SELECT * FROM psra_indicators_affectedpeople_baseline WHERE SAUID LIKE '13%';
CREATE VIEW psra_indicators_affectedpeople_baseline_QC AS SELECT * FROM psra_indicators_affectedpeople_baseline WHERE SAUID LIKE '24%';
CREATE VIEW psra_indicators_affectedpeople_baseline_ON AS SELECT * FROM psra_indicators_affectedpeople_baseline WHERE SAUID LIKE '35%';
CREATE VIEW psra_indicators_affectedpeople_baseline_MB AS SELECT * FROM psra_indicators_affectedpeople_baseline WHERE SAUID LIKE '46%';
CREATE VIEW psra_indicators_affectedpeople_baseline_SK AS SELECT * FROM psra_indicators_affectedpeople_baseline WHERE SAUID LIKE '47%';
CREATE VIEW psra_indicators_affectedpeople_baseline_AB AS SELECT * FROM psra_indicators_affectedpeople_baseline WHERE SAUID LIKE '48%';
CREATE VIEW psra_indicators_affectedpeople_baseline_BC AS SELECT * FROM psra_indicators_affectedpeople_baseline WHERE SAUID LIKE '59%';
CREATE VIEW psra_indicators_affectedpeople_baseline_YT AS SELECT * FROM psra_indicators_affectedpeople_baseline WHERE SAUID LIKE '60%';
CREATE VIEW psra_indicators_affectedpeople_baseline_NT AS SELECT * FROM psra_indicators_affectedpeople_baseline WHERE SAUID LIKE '61%';
CREATE VIEW psra_indicators_affectedpeople_baseline_NU AS SELECT * FROM psra_indicators_affectedpeople_baseline WHERE SAUID LIKE '62%';

-- create psra_indicators_economicsecurity_baseline for all provinces
CREATE VIEW psra_indicators_economicsecurity_baseline_NL AS SELECT * FROM psra_indicators_economicsecurity_baseline WHERE SAUID LIKE '10%';
CREATE VIEW psra_indicators_economicsecurity_baseline_PE AS SELECT * FROM psra_indicators_economicsecurity_baseline WHERE SAUID LIKE '11%';
CREATE VIEW psra_indicators_economicsecurity_baseline_NS AS SELECT * FROM psra_indicators_economicsecurity_baseline WHERE SAUID LIKE '12%';
CREATE VIEW psra_indicators_economicsecurity_baseline_NB AS SELECT * FROM psra_indicators_economicsecurity_baseline WHERE SAUID LIKE '13%';
CREATE VIEW psra_indicators_economicsecurity_baseline_QC AS SELECT * FROM psra_indicators_economicsecurity_baseline WHERE SAUID LIKE '24%';
CREATE VIEW psra_indicators_economicsecurity_baseline_ON AS SELECT * FROM psra_indicators_economicsecurity_baseline WHERE SAUID LIKE '35%';
CREATE VIEW psra_indicators_economicsecurity_baseline_MB AS SELECT * FROM psra_indicators_economicsecurity_baseline WHERE SAUID LIKE '46%';
CREATE VIEW psra_indicators_economicsecurity_baseline_SK AS SELECT * FROM psra_indicators_economicsecurity_baseline WHERE SAUID LIKE '47%';
CREATE VIEW psra_indicators_economicsecurity_baseline_AB AS SELECT * FROM psra_indicators_economicsecurity_baseline WHERE SAUID LIKE '48%';
CREATE VIEW psra_indicators_economicsecurity_baseline_BC AS SELECT * FROM psra_indicators_economicsecurity_baseline WHERE SAUID LIKE '59%';
CREATE VIEW psra_indicators_economicsecurity_baseline_YT AS SELECT * FROM psra_indicators_economicsecurity_baseline WHERE SAUID LIKE '60%';
CREATE VIEW psra_indicators_economicsecurity_baseline_NT AS SELECT * FROM psra_indicators_economicsecurity_baseline WHERE SAUID LIKE '61%';
CREATE VIEW psra_indicators_economicsecurity_baseline_NU AS SELECT * FROM psra_indicators_economicsecurity_baseline WHERE SAUID LIKE '62%';

