-- script to generate the collapse probability LUT
DROP TABLE IF EXISTS collapse_probability_LUT;


-- create tables
CREATE TABLE collapse_probability_LUT(
    typology varchar,
    EqBldgType varchar,
    collapse_pc float

);


-- import results from csv
COPY collapse_probability_LUT (typology, EqBldgType, collapse_pc)
    FROM 'C:\Workspace\eRisk_CA\PSRA_sample_data\collapse_probability_LUT.csv'
        WITH 
          DELIMITER AS ','
          CSV HEADER ;

