-- create scenario risk building indicators
DROP VIEW IF EXISTS results.dsra_sim6p8_cr2022_rlz_0_b0_functional_state_agg_view;
CREATE VIEW results.dsra_sim6p8_cr2022_rlz_0_b0_functional_state_agg_view AS 

-- 4.0 Earthquake Risk
-- 4.2 Building Performance
-- 4.2.2 Functional State
SELECT 
b.sauid AS "Sauid",
f.source_type AS "Source_Type",
f.rupture_name AS "Rupture_Name",
f.magnitude AS "Magnitude",
'b0' AS "Retrofit",
CAST(SUM(b.number) AS NUMERIC) AS "BldgNumber",
CAST(SUM(a."sD_None_b0" + (a."sD_Slight_b0"*0.2) +(a."sD_Moderate_b0"*0.05)) AS NUMERIC) AS "sD_Operational",
CAST(SUM((a."sD_Slight_b0"*0.8) + (a."sD_Moderate_b0"*0.75) + (a."sD_Extensive_b0"*0.2)) AS NUMERIC) AS "sD_Functional",
CAST(SUM((a."sD_Moderate_b0"*0.2) + (a."sD_Extensive_b0"*0.4)) AS NUMERIC) AS "sD_Repairable",
CAST(SUM((a."sD_Extensive_b0"*0.3) + (a."sD_Complete_b0"*0.2)) AS NUMERIC) AS "sD_Failure",
CAST(SUM(a."sD_Collapse_b0") AS NUMERIC) AS "sD_Collapse",
g.geom AS "geom_poly",
g.geompoint AS "geom_point"

FROM dsra.dsra_sim6p8_cr2022_rlz_0 a
LEFT JOIN psra.canada_exposure b ON a."AssetID" = b.id 
--LEFT JOIN lut.retrofit_costs c ON b.eqbldgtype = c."Eq_BldgType"
--LEFT JOIN lut.vs30_bc_site_model_xref d ON a."AssetID" = d.id
--LEFT JOIN lut.gmfdata_sitemesh_sim6p8_cr2022_37_xref e on b.id = e.id
LEFT JOIN ruptures.rupture_table f on f.rupture_name = a."Rupture_Abbr"
LEFT JOIN boundaries."Geometry SAUID" g on b.sauid = g."SAUIDt"
GROUP BY b.sauid, g.geom, g.geompoint, f.source_type, f.rupture_name, f.magnitude;