-- create scenario risk building indicators
DROP VIEW IF EXISTS results.dsra_sim6p8_cr2022_rlz_0_r2_scenario_rupture CASCADE;
CREATE VIEW results.dsra_sim6p8_cr2022_rlz_0_r2_scenario_rupture AS 

-- 4.0 Earthquake Risk
-- 4.1 Scenario Hazard
-- 4.1.1 Scenario Rupture
SELECT 
a."AssetID",
f.source_type AS "Source_Type",
f.rupture_name AS "Rupture_Name",
f.magnitude AS "Magnitude",
f.rake AS "Rake",
CAST(CAST(ROUND(CAST(f.lon AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "Hypo_Lon",
CAST(CAST(ROUND(CAST(f.lat AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "Hypo_Lat",
CAST(CAST(ROUND(CAST(f.depth AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "Hypo_Depth",
CAST(CAST(ROUND(CAST(d."vs_lon" AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "vs30_Lon",
CAST(CAST(ROUND(CAST(d."vs_lat" AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "vs30_Lat",
CAST(CAST(ROUND(CAST(d.vs30 AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "vs30",
e.site_id AS "SiteID",
CAST(CAST(ROUND(CAST(e.lon AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "SiteID_Lon",
CAST(CAST(ROUND(CAST(e.lat AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "SiteID_Lat",
a."Realization" AS "Realization",
a."gmpe_Model" AS "gmpe_Model",
CAST(CAST(ROUND(CAST(a."Weight" AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "Weight",
b.geom

FROM dsra.dsra_sim6p8_cr2022_rlz_0 a
LEFT JOIN psra.canada_exposure b ON a."AssetID" = b.id 
--LEFT JOIN lut.retrofit_costs c ON b.eqbldgtype = c."Eq_BldgType"
LEFT JOIN lut.vs30_bc_site_model_xref d ON a."AssetID" = d.id
LEFT JOIN lut.gmfdata_sitemesh_sim6p8_cr2022_37_xref e on b.id = e.id
LEFT JOIN ruptures.rupture_table f on f.rupture_name = a."Rupture_Abbr";


-- create scenario risk building indicators
DROP VIEW IF EXISTS results.dsra_sim6p8_cr2022_rlz_0_r2_scenario_hazard CASCADE;
CREATE VIEW results.dsra_sim6p8_cr2022_rlz_0_r2_scenario_hazard AS 

-- 4.0 Earthquake Risk
-- 4.1 Scenario Hazard
-- 4.1.2 Scenario Hazard
SELECT 
a."AssetID",
e."event_id" AS "EventID",
CAST(CAST(ROUND(CAST(e."gmv_pgv" AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "PGV",
CAST(CAST(ROUND(CAST(e."gmv_pga" AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "PGA",
CAST(CAST(ROUND(CAST(e."gmv_SA(0.2)" AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "SA_0p2",
CAST(CAST(ROUND(CAST(e."gmv_SA(0.3)" AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "SA_0p3",
CAST(CAST(ROUND(CAST(e."gmv_SA(0.6)" AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "SA_0p6",
CAST(CAST(ROUND(CAST(e."gmv_SA(1.0)" AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "SA_1p0",
CAST(CAST(ROUND(CAST(0 AS NUMERIC),6) AS FLOAT) AS NUMERIC)AS "SA_2p0",  --"Spectral Acceleration (2.0s)" - change source to reflect 2.0 later
b.geom

FROM dsra.dsra_sim6p8_cr2022_rlz_0 a
LEFT JOIN psra.canada_exposure b ON a."AssetID" = b.id 
--LEFT JOIN lut.retrofit_costs c ON b.eqbldgtype = c."Eq_BldgType"
--LEFT JOIN lut.vs30_bc_site_model_xref d ON a."AssetID" = d.id
LEFT JOIN lut.gmfdata_sitemesh_sim6p8_cr2022_37_xref e on b.id = e.id;
--LEFT JOIN ruptures.rupture_table f on f.rupture_name = a."Rupture_Abbr";


-- create scenario risk building indicators
DROP VIEW IF EXISTS results.dsra_sim6p8_cr2022_rlz_0_r2_damage_state CASCADE;
CREATE VIEW results.dsra_sim6p8_cr2022_rlz_0_r2_damage_state AS 

-- 4.0 Earthquake Risk
-- 4.2 Building Performance
-- 4.2.1 Damage State
SELECT 
a."AssetID",
a."Rupture_Abbr",
f.magnitude AS "Source_Mag",
'r2' AS "Retrofit_Level",
a."Realization" AS "RealizationID", 
CAST(CAST(ROUND(CAST(a."sD_None_r2" AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "sD_None",
CAST(CAST(ROUND(CAST(a."sD_None_stdv_r2" AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "sD_None_stdv",
CAST(CAST(ROUND(CAST(a."sD_Slight_r2" AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "sD_Slight",
CAST(CAST(ROUND(CAST(a."sD_Slight_stdv_r2" AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "sD_Slight_stdv",
CAST(CAST(ROUND(CAST(a."sD_Moderate_r2" AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "sD_Moderate",
CAST(CAST(ROUND(CAST(a."sD_Moderate_stdv_r2" AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "sD_Moderate_stdv",
CAST(CAST(ROUND(CAST(a."sD_Extensive_r2" AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "sD_Extensive",
CAST(CAST(ROUND(CAST(a."sD_Extensive_stdv_r2" AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "sD_Extensive_stdv",
CAST(CAST(ROUND(CAST(a."sD_Complete_r2" AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "sD_Complete",
CAST(CAST(ROUND(CAST(a."sD_Complete_stdv_r2" AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "sD_Complete_stdv",
CAST(CAST(ROUND(CAST(a."sD_Collapse_r2" AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "sD_Collapse",
b.geom

FROM dsra.dsra_sim6p8_cr2022_rlz_0 a
LEFT JOIN psra.canada_exposure b ON a."AssetID" = b.id 
--LEFT JOIN lut.retrofit_costs c ON b.eqbldgtype = c."Eq_BldgType"
--LEFT JOIN lut.vs30_bc_site_model_xref d ON a."AssetID" = d.id
--LEFT JOIN lut.gmfdata_sitemesh_sim6p8_cr2022_37_xref e on b.id = e.id
LEFT JOIN ruptures.rupture_table f on f.rupture_name = a."Rupture_Abbr";


-- create scenario risk building indicators
DROP VIEW IF EXISTS results.dsra_sim6p8_cr2022_rlz_0_r2_recovery CASCADE;
CREATE VIEW results.dsra_sim6p8_cr2022_rlz_0_r2_recovery AS 

-- 4.0 Earthquake Risk
-- 4.2 Building Performance
-- 4.2.2 Recovery
SELECT 
a."AssetID",
a."Rupture_Abbr",
f.magnitude AS "Source_Mag",
'r2' AS "Retrofit_Level",
a."Realization" AS "RealizationID", 
CAST(CAST(ROUND(CAST(a."sC_Repair_r2" AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "sC_Repair",
CAST(CAST(ROUND(CAST(a."sC_Construxn_r2" AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "SC_Construxn",
CAST(CAST(ROUND(CAST(a."sC_Downtime_r2" AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "sC_Downtime",
b.geom

FROM dsra.dsra_sim6p8_cr2022_rlz_0 a
LEFT JOIN psra.canada_exposure b ON a."AssetID" = b.id 
--LEFT JOIN lut.retrofit_costs c ON b.eqbldgtype = c."Eq_BldgType"
--LEFT JOIN lut.vs30_bc_site_model_xref d ON a."AssetID" = d.id
--LEFT JOIN lut.gmfdata_sitemesh_sim6p8_cr2022_37_xref e on b.id = e.id
LEFT JOIN ruptures.rupture_table f on f.rupture_name = a."Rupture_Abbr";


-- create scenario risk building indicators
DROP VIEW IF EXISTS results.dsra_sim6p8_cr2022_rlz_0_r2_casualties CASCADE;
CREATE VIEW results.dsra_sim6p8_cr2022_rlz_0_r2_casualties AS 

-- 4.0 Earthquake Risk
-- 4.3 Afected People
-- 4.3.1 Casualties
SELECT
a."AssetID",
a."Rupture_Abbr",
f.magnitude AS "Source_Mag",
'r2' AS "Retrofit_Level",
a."Realization" AS "RealizationID",  
CAST(CAST(ROUND(CAST(a."sC_CasDayL1_r2" AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "sC_CasDayL1",
CAST(CAST(ROUND(CAST(a."sC_CasDayL2_r2" AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "sC_CasDayL2",
CAST(CAST(ROUND(CAST(a."sC_CasDayL3_r2" AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "sC_CasDayL3",
CAST(CAST(ROUND(CAST(a."sC_CasDayL4_r2" AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "sC_CasDayL4",
CAST(CAST(ROUND(CAST(a."sC_CasNightL1_r2" AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "sC_CasNightL1",
CAST(CAST(ROUND(CAST(a."sC_CasNightL2_r2" AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "sC_CasNightL2",
CAST(CAST(ROUND(CAST(a."sC_CasNightL3_r2" AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "sC_CasNightL3",
CAST(CAST(ROUND(CAST(a."sC_CasNightL4_r2" AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "sC_CasNightL4",
CAST(CAST(ROUND(CAST(a."sC_CasTransitL1_r2" AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "sC_CasTransitL1",
CAST(CAST(ROUND(CAST(a."sC_CasTransitL2_r2" AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "sC_CasTransitL2",
CAST(CAST(ROUND(CAST(a."sC_CasTransitL3_r2" AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "sC_CasTransitL3",
CAST(CAST(ROUND(CAST(a."sC_CasTransitL4_r2" AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "sC_CasTransitL4",
b.geom

FROM dsra.dsra_sim6p8_cr2022_rlz_0 a
LEFT JOIN psra.canada_exposure b ON a."AssetID" = b.id 
--LEFT JOIN lut.retrofit_costs c ON b.eqbldgtype = c."Eq_BldgType"
--LEFT JOIN lut.vs30_bc_site_model_xref d ON a."AssetID" = d.id
--LEFT JOIN lut.gmfdata_sitemesh_sim6p8_cr2022_37_xref e on b.id = e.id
LEFT JOIN ruptures.rupture_table f on f.rupture_name = a."Rupture_Abbr";


-- create scenario risk building indicators
DROP VIEW IF EXISTS results.dsra_sim6p8_cr2022_rlz_0_r2_social_disruption CASCADE;
CREATE VIEW results.dsra_sim6p8_cr2022_rlz_0_r2_social_disruption AS 

-- 4.0 Earthquake Risk
-- 4.3 Afected People
-- 4.3.2 Social Disruption
SELECT
a."AssetID",
a."Rupture_Abbr",
f.magnitude AS "Source_Mag",
'r2' AS "Retrofit_Level",
a."Realization" AS "RealizationID", 
CAST(CAST(ROUND(CAST(a."sC_DisplRes_3_r2" AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "sC_DisplRes_3",
CAST(CAST(ROUND(CAST(a."sC_DisplRes_30_r2" AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "sC_DisplRes_30",
CAST(CAST(ROUND(CAST(a."sC_DisplRes_90_r2" AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "sC_DisplRes_90",
CAST(CAST(ROUND(CAST(a."sC_DisplRes_360_r2" AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "sC_DisplRes_360",
CAST(CAST(ROUND(CAST(a."sC_DisrupEmpl_30_r2" AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "sC_DisrupEmpl_30",
CAST(CAST(ROUND(CAST(a."sC_DisrupEmpl_90_r2" AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "sC_DisrupEmpl_90",
CAST(CAST(ROUND(CAST(a."sC_DisrupEmpl_180_r2" AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "sC_DisrupEmpl_180",
CAST(CAST(ROUND(CAST(a."sC_DisrupEmpl_360_r2" AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "sC_DisrupEmpl_360",
CAST(CAST(ROUND(CAST(a."sC_DebrisBW_r2" AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "sC_DebrisBW",
CAST(CAST(ROUND(CAST(a."sC_DebrisC_r2" AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "sC_DebrisC",
b.geom

FROM dsra.dsra_sim6p8_cr2022_rlz_0 a
LEFT JOIN psra.canada_exposure b ON a."AssetID" = b.id 
--LEFT JOIN lut.retrofit_costs c ON b.eqbldgtype = c."Eq_BldgType"
--LEFT JOIN lut.vs30_bc_site_model_xref d ON a."AssetID" = d.id
--LEFT JOIN lut.gmfdata_sitemesh_sim6p8_cr2022_37_xref e on b.id = e.id
LEFT JOIN ruptures.rupture_table f on f.rupture_name = a."Rupture_Abbr";


-- create scenario risk building indicators
DROP VIEW IF EXISTS results.dsra_sim6p8_cr2022_rlz_0_r2_economic_loss CASCADE;
CREATE VIEW results.dsra_sim6p8_cr2022_rlz_0_r2_economic_loss AS 

-- 4.0 Earthquake Risk
-- 4.4 Economic Security
-- 4.4.1 Economic Loss
SELECT
a."AssetID",
a."Rupture_Abbr",
f.magnitude AS "Source_Mag",
'r2' AS "Retrofit_Level",
a."Realization" AS "RealizationID", 
CAST(CAST(ROUND(CAST(a."sL_Str_r2" + a."sL_NStr_r2" + a."sL_Cont_r2" AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "sL_Asset",
CAST(CAST(ROUND(CAST(a."sL_Str_r2" + a."sL_NStr_r2" AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "sL_Bldg",
CAST(CAST(ROUND(CAST(COALESCE((a."sL_Str_r2" + a."sL_NStr_r2") / NULLIF((a."sL_Str_r2" + a."sL_NStr_r2" + a."sL_Cont_r2"),0),0) AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "sL_BldgRatio",
CAST(CAST(ROUND(CAST(a."sL_Str_r2" AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "sL_Str",
CAST(CAST(ROUND(CAST(a."sL_Str_stdv_r2" AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "sL_Str_stdv",
CAST(CAST(ROUND(CAST(a."sL_NStr_r2" AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "sL_NStr",
CAST(CAST(ROUND(CAST(a."sL_NStr_stdv_r2" AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "sL_NStr_stdv",
CAST(CAST(ROUND(CAST(a."sL_Cont_r2" AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "sL_Cont",
CAST(CAST(ROUND(CAST(a."sL_Cont_stdv_r2" AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "sL_Cont_stdv",
CAST(CAST(ROUND(CAST(a."sL_Fatalities_r2" AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "sL_Fatality",
CAST(CAST(ROUND(CAST(a."sL_Fatalities_stdv_r2" AS NUMERIC),6) AS FLOAT) AS NUMERIC) AS "sL_Fatality_stdv",
b.geom

FROM dsra.dsra_sim6p8_cr2022_rlz_0 a
LEFT JOIN psra.canada_exposure b ON a."AssetID" = b.id 
--LEFT JOIN lut.retrofit_costs c ON b.eqbldgtype = c."Eq_BldgType"
--LEFT JOIN lut.vs30_bc_site_model_xref d ON a."AssetID" = d.id
--LEFT JOIN lut.gmfdata_sitemesh_sim6p8_cr2022_37_xref e on b.id = e.id
LEFT JOIN ruptures.rupture_table f on f.rupture_name = a."Rupture_Abbr";