CREATE SCHEMA IF NOT EXISTS results_psra_bc;


-- src loss values
DROP VIEW IF EXISTS results_psra_bc.psra_bc5910_src_loss CASCADE;
CREATE VIEW results_psra_bc.psra_bc5910_src_loss AS

SELECT 
source AS "src_zone",
trt AS "src_type",
SUM(loss_value_b0)/(SELECT SUM(loss_value_b0) FROM psra_bc.psra_bc5910_src_loss ) AS "src_value_b0",
SUM(loss_value_r2)/(SELECT SUM(loss_value_r2) FROM psra_bc.psra_bc5910_src_loss ) AS "src_value_r2"
FROM psra_bc.psra_bc5910_src_loss
GROUP BY source,trt;



-- src loss values
DROP VIEW IF EXISTS results_psra_bc.psra_bc5920_src_loss CASCADE;
CREATE VIEW results_psra_bc.psra_bc5920_src_loss AS

SELECT 
source AS "src_zone",
trt AS "src_type",
SUM(loss_value_b0)/(SELECT SUM(loss_value_b0) FROM psra_bc.psra_bc5910_src_loss ) AS "src_value_b0",
SUM(loss_value_r2)/(SELECT SUM(loss_value_r2) FROM psra_bc.psra_bc5910_src_loss ) AS "src_value_r2"
FROM psra_bc.psra_bc5920_src_loss
GROUP BY source,trt;



-- src loss values
DROP VIEW IF EXISTS results_psra_bc.psra_bc5930_src_loss CASCADE;
CREATE VIEW results_psra_bc.psra_bc5930_src_loss AS

SELECT 
source AS "src_zone",
trt AS "src_type",
SUM(loss_value_b0)/(SELECT SUM(loss_value_b0) FROM psra_bc.psra_bc5910_src_loss ) AS "src_value_b0",
SUM(loss_value_r2)/(SELECT SUM(loss_value_r2) FROM psra_bc.psra_bc5910_src_loss ) AS "src_value_r2"
FROM psra_bc.psra_bc5930_src_loss
GROUP BY source,trt;


-- src loss values
DROP VIEW IF EXISTS results_psra_bc.psra_bc5940_80_src_loss CASCADE;
CREATE VIEW results_psra_bc.psra_bc5940_80_src_loss AS

SELECT 
source AS "src_zone",
trt AS "src_type",
SUM(loss_value_b0)/(SELECT SUM(loss_value_b0) FROM psra_bc.psra_bc5910_src_loss ) AS "src_value_b0",
SUM(loss_value_r2)/(SELECT SUM(loss_value_r2) FROM psra_bc.psra_bc5910_src_loss ) AS "src_value_r2"
FROM psra_bc.psra_bc5940_80_src_loss
GROUP BY source,trt;