-- create physical exposure indicators
DROP VIEW IF EXISTS results.canada_exposure_construction CASCADE;
CREATE VIEW results.canada_exposure_construction AS 

-- 2.0 Physical Exposure
-- 2.1 Buildings
-- 2.1.2 Construction
SELECT 
a.id AS "AssetID",
a.landusetyp AS "LandUse",
a.bldggen AS "Type_General",
a.eqbldgtype AS "Type_Specific",
a.eqdeslev AS "Design_Level",
a.geom

FROM psra.canada_exposure a;