-- create physical exposure indicators
DROP VIEW IF EXISTS results.canada_exposure_building_occupancy CASCADE;
CREATE VIEW results.canada_exposure_building_occupancy AS 

-- 2.0 Physical Exposure
-- 2.3 Buildings
-- 2.3.1 Building Occupancy
SELECT 
a.id AS "AssetID",
CAST(a.day AS NUMERIC) AS "DayPop",
CAST(a.night AS NUMERIC) AS "NightPop",
CAST(a.transit AS NUMERIC) AS "TransitPop",
a.geom

FROM psra.canada_exposure a;