REM Export physical exposure views to geojson, and geopackage files. Replace exposure name {bldgexp_canada} to target exposure if different to run.  Change ogr2ogr path, location paths, db information if needed.

REM Geojson export
FOR %%x IN (psra677_seismic_hazard_site_amplification_b,psra_677_affected_people_casualties_b,psra_677_affected_people_casualties_s,psra_677_affected_people_social_disruption_b,psra_677_affected_people_social_disruption_s,
psra_677_building_damage_classical_damage_b,psra_677_building_damage_classical_damage_s,psra_677_building_damage_event_based_damage_b,psra_677_building_damage_event_based_damage_s,psra_677_building_damage_recovery_b,
psra_677_building_damage_recovery_s,psra_677_economic_security_economic_loss_b,psra_677_economic_security_economic_loss_s,psra_677_economic_security_pml_b0_s,psra_677_economic_security_pml_r1_s,psra_677_economic_security_pml_r2_s,
psra_677_seismic_hazard_500yr_hazard_intensity_b,psra_677_seismic_hazard_500yr_hazard_intensity_s,psra_677_seismic_hazard_2500yr_hazard_intensity_b,psra_677_seismic_hazard_2500yr_hazard_intensity_s,
psra_677_seismic_hazard_site_amplification_s) DO "C:\OSGeo4W64\bin\ogr2ogr.exe" -f "GeoJSON" D:\workspace\data\view_outputs\%%x.geojson PG:"host=localhost user=postgres dbname=oq_sandbox password=password" results_psra_677.%%x

REM Geopackage export
FOR %%x IN (psra677_seismic_hazard_site_amplification_b,psra_677_affected_people_casualties_b,psra_677_affected_people_casualties_s,psra_677_affected_people_social_disruption_b,psra_677_affected_people_social_disruption_s,
psra_677_building_damage_classical_damage_b,psra_677_building_damage_classical_damage_s,psra_677_building_damage_event_based_damage_b,psra_677_building_damage_event_based_damage_s,psra_677_building_damage_recovery_b,
psra_677_building_damage_recovery_s,psra_677_economic_security_economic_loss_b,psra_677_economic_security_economic_loss_s,psra_677_economic_security_pml_b0_s,psra_677_economic_security_pml_r1_s,psra_677_economic_security_pml_r2_s,
psra_677_seismic_hazard_500yr_hazard_intensity_b,psra_677_seismic_hazard_500yr_hazard_intensity_s,psra_677_seismic_hazard_2500yr_hazard_intensity_b,psra_677_seismic_hazard_2500yr_hazard_intensity_s,
psra_677_seismic_hazard_site_amplification_s) DO "C:\OSGeo4W64\bin\ogr2ogr.exe" -f "gpkg" D:\workspace\data\view_outputs\%%x.gpkg PG:"host=localhost user=postgres dbname=oq_sandbox password=password" results_psra_677.%%x

PAUSE