
DROP TABLE IF EXISTS lut.sovi_index_canada;

-- create table
CREATE TABLE lut.sovi_index_canada(
    PRIMARY KEY(SAUIDt),
    SAUIDi integer,
    SAUIDt varchar,
    Lon float,
    Lat float,
    Area_km2 float,
    Area_ha float,
    DAUIDt varchar,
    DAUIDi integer,
    SACCODE varchar,
    SACTYPE varchar,
    BldgNum float,
    CensusBldg float,
    CensusPop float,
    CensusDU float,
    People_DU float,
    Inc_Hshld float,
    Imm_LT5 float,
    Indigenous float,
    Work_None float,
    Pub_Trans float,
    No_EngFr float,
    Inc_Indv float,
    Hshld_NSuit float,
    Unemployed float,
    Pre_1975 float,
    Age_GT65 float,
    Age_Median float,
    Bldg_ha float,
    Retail_Job float,
    Work_Parttime float,
    Inc_LowDecile float,
    Bus_Ha float,
    NoSec_School float,
    LandUse float,
    Moved_LT1 float,
    Dwelling_ha float,
    Shltr_GT30 float,
    Health_Job float,
    Live_Alone float,
    NoWrkPlace float,
    LonePar3Kids float,
    Pop_Ha float,
    Hshld_Mntn1 float,
    Vis_Min float,
    Renter float,
    Hshld_MntnAge float,
    Fam_GT5 float,
    Age_LT6 float,
    Employ_Inc float

);

-- import exposure from csv
COPY lut.sovi_index_canada (SAUIDi, SAUIDt, Lon, Lat, Area_km2, Area_ha, DAUIDt, DAUIDi, SACCODE, SACTYPE, BldgNum, CensusBldg, CensusPop, CensusDU, People_DU, Inc_Hshld, Imm_LT5, Indigenous, Work_None, Pub_Trans, No_EngFr, Inc_Indv, Hshld_NSuit, Unemployed, Pre_1975, Age_GT65, Age_Median, Bldg_ha, Retail_Job, Work_Parttime, Inc_LowDecile, Bus_Ha, NoSec_School, LandUse, Moved_LT1, Dwelling_ha, Shltr_GT30, Health_Job, Live_Alone, NoWrkPlace, LonePar3Kids, Pop_Ha, Hshld_Mntn1, Vis_Min, Renter, Hshld_MntnAge, Fam_GT5, Age_LT6, Employ_Inc)

    FROM 'C:\workspace\human-settlement-national\3_sovi-index-canada.csv'
        WITH 
          DELIMITER AS ','
          CSV HEADER ;