-- script to generate Canada exposure table

DROP TABLE IF EXISTS psra.canada_exposure;

-- create table
CREATE TABLE psra.canada_exposure(
    PRIMARY KEY (id),
    OID varchar,
    id varchar,
    lon float,
    lat float,
    taxonomy varchar,
    number float,
    structural float,
    nonstructural float,
    contents float,
    day float,
    night float,
    transit float,
    landusetyp varchar,
    GenOcc varchar,
    hzOccType varchar,
    eqOccType varchar,
    BldgGen varchar,
    hzTaxon varchar,
    EqBldgType varchar,
    EqDesLev varchar,
    sauid varchar,
    dauid varchar,
    adauid varchar,
    fsauid varchar,
    csduid varchar,
    csdname varchar,
    cduid varchar,
    cdname varchar,
    SAC varchar,
    pruid varchar,
    prname varchar,
    ername varchar

);

-- import exposure from csv
COPY psra.canada_exposure (OID,id, lon, lat, taxonomy, number, structural, nonstructural, contents, day, night, transit, landusetyp, GenOcc, hzOccType, eqOccType, BldgGen, hzTaxon, EqBldgType, EqDesLev, sauid, dauid, adauid, fsauid, csduid, csdname, cduid, cdname, SAC, pruid, prname, ername)
    FROM 'C:\workspace\human-settlement-national\1_building-exposure-canada.csv'
        WITH 
          DELIMITER AS ','
          CSV HEADER ;


-- add geometries field to enable PostGIS (WGS1984 SRID = 4326)
ALTER TABLE psra.canada_exposure ADD COLUMN geom geometry(Point,4326);
UPDATE psra.canada_exposure SET geom = st_setsrid(st_makepoint(lon,lat),4326);

-- create spatial index
CREATE INDEX Canada_exposure_idx
ON psra.Canada_exposure using GIST (geom);



