-- update gmf data and sitemesh data into 1 table incorporating assetID

DROP TABLE IF EXISTS gmf.gmfdata_sitemesh_idm6p8_jdfpathways_metrovan_site_exposure_xref;

-- attach assetID to gmfdata_sitemesh based on closest location -event 0
CREATE TABLE gmf.gmfdata_sitemesh_idm6p8_jdfpathways_metrovan_site_exposure_xref AS

SELECT
a."id",
--b."event_id",
b."site_id",
b."gmv_pga",
--b."gmv_pgv",
--b."gmv_SA(0.1)",
--b."gmv_SA(0.2)",
b."gmv_SA(0.3)",
b."gmv_SA(0.6)",
b."gmv_SA(1.0)",
--b."gmv_SA(2.0)",
b.lon,
b.lat,
a.sitelon AS "asset_lon",
a.sitelat AS "asset_lat",
ST_Distance(a.geom_site,b.geom) AS "distance"

FROM exposure.metrovan_site_exposure a
CROSS JOIN LATERAL 
(
SELECT -- event_id,
	site_id,
	gmv_pga,
	--gmv_pgv,
	--"gmv_SA(0.1)",
	--"gmv_SA(0.2)",
	"gmv_SA(0.3)",
	"gmv_SA(0.6)",
	"gmv_SA(1.0)",
	--"gmv_SA(2.0)",
	lon,
	lat,
	geom
	
FROM gmf.gmfdata_sitemesh_idm6p8_jdfpathways
ORDER BY a.geom_site <-> geom
LIMIT 1
) AS b;

ALTER TABLE gmf.gmfdata_sitemesh_idm6p8_jdfpathways_metrovan_site_exposure_xref ADD COLUMN IF NOT EXISTS "gmv_pgv" float DEFAULT 0;
ALTER TABLE gmf.gmfdata_sitemesh_idm6p8_jdfpathways_metrovan_site_exposure_xref ADD COLUMN IF NOT EXISTS "gmv_SA(0.1)" float DEFAULT 0;
ALTER TABLE gmf.gmfdata_sitemesh_idm6p8_jdfpathways_metrovan_site_exposure_xref ADD COLUMN IF NOT EXISTS "gmv_SA(0.2)" float DEFAULT 0;
ALTER TABLE gmf.gmfdata_sitemesh_idm6p8_jdfpathways_metrovan_site_exposure_xref ADD COLUMN IF NOT EXISTS "gmv_SA(2.0)" float DEFAULT 0;

-- create index
CREATE INDEX gmfdata_sitemesh_idm6p8_jdfpathways_metrovan_site_exposure_idx ON gmf.gmfdata_sitemesh_idm6p8_jdfpathways_metrovan_site_exposure_xref (id);