-- create physical exposure indicators
DROP VIEW IF EXISTS results_float.canada_exposure_portfolio_agg_view CASCADE;
CREATE VIEW results_float.canada_exposure_portfolio_agg_view AS 

-- 2.0 Physical Exposure
-- 2.1 Buildings
-- 2.0.1 Portfolio
SELECT 
a.sauid AS "Sauid",
a.lon AS "Sauid_Lon",
a.lat AS "Sauid_Lat",
c."area_km2" AS "Area_km2",
c.area_ha AS "Area_ha",
SUM(a.number) AS "BldNumT",
COALESCE(c.censusbldg,0) AS "CensusBldg",
c.censusdu AS "CensusDU",
c.people_du as "People_DU",
d.geom AS "geom_poly",
d.geompoint AS "geom_point"

FROM psra.canada_exposure a
--LEFT JOIN lut.retrofit_costs b ON a.eqbldgtype = b."Eq_BldgType"
LEFT JOIN lut.census_2016_canada c ON a.sauid = c.sauidt
LEFT JOIN boundaries."Geometry SAUID" d on a.sauid = d."SAUIDt"
GROUP BY a.sauid,a.lon,a.lat,c."area_km2",c.area_ha,c.censusbldg,c.people_du,c.censusdu,d.geom,d.geompoint;


-- create physical exposure indicators
DROP VIEW IF EXISTS results_float.canada_exposure_functional_use_agg_view CASCADE;
CREATE VIEW results_float.canada_exposure_functional_use_agg_view AS 

-- 2.0 Physical Exposure
-- 2.1 Buildings
-- 2.1.1 Functional Use
SELECT 
a.sauid AS "Sauid",
c.sactype AS "SAC",
c.landuse AS "LandUse",
SUM(CASE WHEN a.genocc ='Residential-LD' THEN a.number ELSE 0 END) AS "RES_LD",
SUM(CASE WHEN a.genocc ='Residential-MD' THEN a.number ELSE 0 END) AS "RES_MD",
SUM(CASE WHEN a.genocc ='Residential-HD' THEN a.number ELSE 0 END) AS "RES_HD",
SUM(CASE WHEN a.genocc ='Commercial' THEN a.number ELSE 0 END) AS "Comm",
SUM(CASE WHEN a.genocc ='Industrial' THEN a.number ELSE 0 END) AS "Ind",
SUM(CASE WHEN a.genocc ='Civic' THEN a.number ELSE 0 END) AS "Civic",
SUM(CASE WHEN a.genocc ='Agricultural' THEN a.number ELSE 0 END) AS "Agr",
SUM(CASE WHEN a.genocc ='Residential-LD' THEN a.number ELSE 0 END) / c.people_du AS "SF_Hshlds",
(SUM(CASE WHEN a.genocc ='Residential-MD' THEN a.number ELSE 0 END) + SUM(CASE WHEN a.genocc ='Residential-HD' THEN a.number ELSE 0 END)) / c.people_du AS "MF_Hshlds",
d.geom AS "geom_poly",
d.geompoint AS "geom_point"

FROM psra.canada_exposure a
--LEFT JOIN lut.retrofit_costs b ON a.eqbldgtype = b."Eq_BldgType"
LEFT JOIN lut.census_2016_canada c ON a.sauid = c.sauidt
LEFT JOIN boundaries."Geometry SAUID" d on a.sauid = d."SAUIDt"
GROUP BY a.sauid,c.sactype,c.landuse,c.people_du,d.geom,d.geompoint;


-- create physical exposure indicators
DROP VIEW IF EXISTS results_float.canada_exposure_construction_agg_view;
CREATE VIEW results_float.canada_exposure_construction_agg_view AS 

-- 2.0 Physical Exposure
-- 2.1 Buildings
-- 2.1.2 Construction
SELECT 
a.sauid AS "Sauid",
SUM(CASE WHEN a.bldggen ='Wood' THEN a.number ELSE 0 END) AS "Wood",
SUM(CASE WHEN a.bldggen ='Concrete' THEN a.number ELSE 0 END) AS "Concrete",
SUM(CASE WHEN a.bldggen ='Precast' THEN a.number ELSE 0 END) AS "PreCast",
SUM(CASE WHEN a.bldggen ='RMasonry' THEN a.number ELSE 0 END) AS "RMasonry",
SUM(CASE WHEN a.bldggen ='URMasonry' THEN a.number ELSE 0 END) AS "URMasonry",
SUM(CASE WHEN a.bldggen ='Steel' THEN a.number ELSE 0 END) AS "Steel",
SUM(CASE WHEN a.bldggen ='Manufactured' THEN a.number ELSE 0 END) AS "Manufactured",
SUM(CASE WHEN a.eqdeslev ='PC' THEN a.number ELSE 0 END) AS "PreCode",
SUM(CASE WHEN a.eqdeslev ='LC' THEN a.number ELSE 0 END) AS "LowCode",
SUM(CASE WHEN a.eqdeslev ='MC' THEN a.number ELSE 0 END) AS "ModCode",
SUM(CASE WHEN a.eqdeslev ='HC' THEN a.number ELSE 0 END) AS "HiCode",
d.geom AS "geom_poly",
d.geompoint AS "geom_point"

FROM psra.canada_exposure a
--LEFT JOIN lut.retrofit_costs b ON a.eqbldgtype = b."Eq_BldgType"
--LEFT JOIN lut.census_2016_canada c ON a.sauid = c.sauidt
LEFT JOIN boundaries."Geometry SAUID" d on a.sauid = d."SAUIDt"
GROUP BY a.sauid,d.geom,d.geompoint;


-- create physical exposure indicators
DROP VIEW IF EXISTS results_float.canada_exposure_replacement_cost_agg_view;
CREATE VIEW results_float.canada_exposure_replacement_cost_agg_view AS 

-- 2.0 Physical Exposure
-- 2.1 Buildings
-- 2.1.3 Replacement Cost
SELECT 
a.sauid AS "Sauid",
SUM(a.structural + a.nonstructural + a.contents) AS "AssetCostT",
SUM(a.structural + a.nonstructural) AS "BldgCostT",
SUM(a.structural) AS "StrCostT",
SUM(a.nonstructural) AS "NStrCostT",
SUM(a.contents) AS "ContCost",
d.geom AS "geom_poly",
d.geompoint AS "geom_point"

FROM psra.canada_exposure a
--LEFT JOIN lut.retrofit_costs b ON a.eqbldgtype = b."Eq_BldgType"
--LEFT JOIN lut.census_2016_canada c ON a.sauid = c.sauidt
LEFT JOIN boundaries."Geometry SAUID" d on a.sauid = d."SAUIDt"
GROUP BY a.sauid,d.geom,d.geompoint;


-- create physical exposure indicators
DROP VIEW IF EXISTS results_float.canada_exposure_building_occupancy_agg_view;
CREATE VIEW results_float.canada_exposure_building_occupancy_agg_view AS 

-- 2.0 Physical Exposure
-- 2.3 People
-- 2.3.1 Building Occupancy
SELECT 
a.sauid AS "Sauid",
c.censuspop AS "CensusPop",
SUM(a.day) AS "DayPopT",
SUM(a.night) AS "NightPopT",
SUM(a.transit) AS "TransitPopT",
d.geom AS "geom_poly",
d.geompoint AS "geom_point"

FROM psra.canada_exposure a
--LEFT JOIN lut.retrofit_costs b ON a.eqbldgtype = b."Eq_BldgType"
LEFT JOIN lut.census_2016_canada c ON a.sauid = c.sauidt
LEFT JOIN boundaries."Geometry SAUID" d on a.sauid = d."SAUIDt"
GROUP BY a.sauid,c.censuspop,d.geom,d.geompoint;