-- script to generate Canada exposure table

DROP TABLE IF EXISTS lut.vs30_bc_site_model;


-- create table
CREATE TABLE lut.vs30_bc_site_model(
    lon float,
    lat float,
    vs30 float
    
);

-- import exposure from csv
COPY lut.vs30_bc_site_model (lon, lat, vs30)
    FROM 'C:\GitHub\opendrr-data-store\sample-datasets\vs30_BC_site_model.csv'
        WITH 
          DELIMITER AS ','
          CSV HEADER ;


-- add geometries field to enable PostGIS (WGS1984 SRID = 4326)
ALTER TABLE lut.vs30_bc_site_model ADD COLUMN geom geometry(Point,4326);
UPDATE lut.vs30_bc_site_model SET geom = st_setsrid(st_makepoint(lon,lat),4326);

-- create spatial index
CREATE INDEX vs30_bc_site_model_idx
ON lut.vs30_bc_site_model using GIST (geom);




