-- create physical exposure indicators
DROP VIEW IF EXISTS results.canada_exposure_portfolio CASCADE;
CREATE VIEW results.canada_exposure_portfolio AS 

-- 2.0 Physical Exposure
-- 2.1 Buildings
-- 2.0.1 Portfolio
SELECT 
a.id AS "AssetID",
a.sauid AS "Sauid",
a.lon AS "Asset_Lon",
a.lat AS "Asset_Lat",
a.number AS "BldNum",
b."BldgArea_ft2" AS "BldgArea_ft2",
a.geom

FROM psra.canada_exposure a
LEFT JOIN lut.retrofit_costs b ON a.eqbldgtype = b."Eq_BldgType";


-- create physical exposure indicators
DROP VIEW IF EXISTS results.canada_exposure_functional_use CASCADE;
CREATE VIEW results.canada_exposure_functional_use AS 

-- 2.0 Physical Exposure
-- 2.1 Buildings
-- 2.1.1 Functional Use
SELECT 
a.id AS "AssetID",
a.landusetyp AS "LandUse",
a.genocc AS "Occ_General",
a.eqocctype AS "Occ_Specific",
a.geom

FROM psra.canada_exposure a;


-- create physical exposure indicators
DROP VIEW IF EXISTS results.canada_exposure_construction CASCADE;
CREATE VIEW results.canada_exposure_construction AS 

-- 2.0 Physical Exposure
-- 2.1 Buildings
-- 2.1.2 Construction
SELECT 
a.id AS "AssetID",
a.landusetyp AS "LandUse",
a.bldggen AS "Type_General",
a.eqbldgtype AS "Type_Specific",
a.eqdeslev AS "Design_Level",
a.geom

FROM psra.canada_exposure a;


-- create physical exposure indicators
DROP VIEW IF EXISTS results.canada_exposure_replacement_cost CASCADE;
CREATE VIEW results.canada_exposure_replacement_cost AS 

-- 2.0 Physical Exposure
-- 2.1 Buildings
-- 2.1.2 Replacement Cost
SELECT 
a.id AS "AssetID",
a.structural AS "StrCost",
a.nonstructural AS "NStrCost",
a.contents AS "ContCost",
a.structural + a.nonstructural + a.contents AS "AssetCost",
a.structural + a.nonstructural AS "BldgCost",
b."CAD_RetrofitCost_Bldg" AS "RetrofitCost",
a.geom

FROM psra.canada_exposure a
LEFT JOIN lut.retrofit_costs b ON a.eqbldgtype = b."Eq_BldgType";


-- create physical exposure indicators
DROP VIEW IF EXISTS results.canada_exposure_building_occupancy CASCADE;
CREATE VIEW results.canada_exposure_building_occupancy AS 

-- 2.0 Physical Exposure
-- 2.3 Buildings
-- 2.3.1 Building Occupancy
SELECT 
a.id AS "AssetID",
a.day AS "DayPop",
a.night AS "NightPop",
a.transit AS "TransitPop",
a.geom

FROM psra.canada_exposure a;