
-- november 2021 update, import sovi dauid nov 2021 update and convert to SA.  Import SA table as new source.
DROP TABLE IF EXISTS sovi.sovi_dauid_nov2021 CASCADE;

-- create table
CREATE TABLE sovi.sovi_dauid_nov2021(
PRIMARY KEY("DAUID"),
fid varchar,
"OBJECTID_12" varchar,
"OBJECTID" varchar,
"DAUID" varchar,
"PRUID" varchar,
"PRNAME" varchar,
"CSDTYPE" varchar,
"SACTYPE" varchar,
"CensusPop" float,
"AgeGT65" float,
"Vn_AgeGT65" float,
"Vt_AgeGT65" float,
"AgeLT6" float,
"Vn_AgeLT6" float,
"Vt_AgeLT6" float,
"AgeMedian" float,
"Vn_AgeMedian" float,
"Vt_AgeMedian" float,
"FamGT5" float,
"Vn_FamGT5" float,
"Vt_FamGT5" float,
"Health" float,
"Vn_Health" float,
"Vt_Health" float,
"ImmLT5" float,
"Vn_ImmLT5" float,
"Vt_ImmLT5" float,
"IncEmpl" float,
"Vn_IncEmpl" float,
"Vt_IncEmpl" float,
"IncHshld" float,
"Vn_IncHshld" float,
"Vt_IncHshld" float,
"IncInd" float,
"Vn_IncInd" float,
"Vt_IncInd" float,
"IncLowdec" float,
"Vn_IncLowDec" float,
"Vt_IncLowDec" float,
"Indigenous" float,
"Vn_Indigenous" float,
"Vt_Indigenous" float,
"LiveAlone" float,
"Vn_LivAlone" float,
"Vt_LivAlone" float,
"LonPar3Kids" float,
"Vn_LonPar3Kids" float,
"Vt_LonPar3Kids" float,
"MntnAge" float,
"Vn_MntnAge" float,
"Vt_MntnAge" float,
"MovedLT1" float,
"Vn_MovedLT1" float,
"Vt_MovedLT1" float,
"NoEngFr" float,
"Vn_NoEngFr" float,
"Vt_NoEngFr" float,
"NonResHa" float,
"Vn_NonResHa" float,
"Vt_NonResHa" float,
"NoSecEd" float,
"Vn_NoSecEd" float,
"Vt_NoSecEd" float,
"NoWrkPlace" float,
"Vn_NoWrkPlace" float,
"Vt_NoWrkPlace" float,
"NSuitHouse" float,
"Vn_NSuitHouse" float,
"Vt_NSuitHouse" float,
"OneIncHshld" float,
"Vn_OneIncHshld" float,
"Vt_OneIncHshld" float,
"PopHa" float,
"Vn_PopHa" float,
"Vt_PopHa" float,
"Pre1975" float,
"Vn_Pre1975" float,
"Vt_Pre1975" float,
"PubTrans" float,
"Vn_PubTrans" float,
"Vt_PubTrans" float,
"Renter" float,
"Vn_Renter" float,
"Vt_Renter" float,
"Retail" float,
"Vn_Retail" float,
"Vt_Retail" float,
"ShltrGT30" float,
"Vn_ShltrGT30" float,
"Vt_ShltrGT30" float,
"Unemployed" float,
"Vn_Unemployed" float,
"Vt_Unemployed" float,
"VisMinority" float,
"Vn_VisMinority" float,
"Vt_VisMinority" float,
"WorkNone" float,
"Vn_WorkNone" float,
"Vt_WorkNone" float,
"WorkPart" float,
"Vn_WorkPart" float,
"Vt_WorkPart" float,
"SVIt_Social" float,
"SVIt_Autonomy" float,
"SVIt_Housing" float,
"SVIt_Financial" float,
"SVIt_Total" float
);

-- import exposure from csv
COPY sovi.sovi_dauid_nov2021(fid,"OBJECTID_12","OBJECTID","DAUID","PRUID","PRNAME","CSDTYPE","SACTYPE","CensusPop","AgeGT65","Vn_AgeGT65","Vt_AgeGT65","AgeLT6","Vn_AgeLT6","Vt_AgeLT6","AgeMedian","Vn_AgeMedian","Vt_AgeMedian",
"FamGT5","Vn_FamGT5","Vt_FamGT5","Health","Vn_Health","Vt_Health","ImmLT5","Vn_ImmLT5","Vt_ImmLT5","IncEmpl","Vn_IncEmpl","Vt_IncEmpl","IncHshld","Vn_IncHshld","Vt_IncHshld","IncInd","Vn_IncInd","Vt_IncInd","IncLowdec",
"Vn_IncLowDec","Vt_IncLowDec","Indigenous","Vn_Indigenous","Vt_Indigenous","LiveAlone","Vn_LivAlone","Vt_LivAlone","LonPar3Kids","Vn_LonPar3Kids","Vt_LonPar3Kids","MntnAge","Vn_MntnAge","Vt_MntnAge","MovedLT1","Vn_MovedLT1",
"Vt_MovedLT1","NoEngFr","Vn_NoEngFr","Vt_NoEngFr","NonResHa","Vn_NonResHa","Vt_NonResHa","NoSecEd","Vn_NoSecEd","Vt_NoSecEd","NoWrkPlace","Vn_NoWrkPlace","Vt_NoWrkPlace","NSuitHouse","Vn_NSuitHouse","Vt_NSuitHouse","OneIncHshld",
"Vn_OneIncHshld","Vt_OneIncHshld","PopHa","Vn_PopHa","Vt_PopHa","Pre1975","Vn_Pre1975","Vt_Pre1975","PubTrans","Vn_PubTrans","Vt_PubTrans","Renter","Vn_Renter","Vt_Renter","Retail","Vn_Retail","Vt_Retail","ShltrGT30","Vn_ShltrGT30",
"Vt_ShltrGT30","Unemployed","Vn_Unemployed","Vt_Unemployed","VisMinority","Vn_VisMinority","Vt_VisMinority","WorkNone","Vn_WorkNone","Vt_WorkNone","WorkPart","Vn_WorkPart","Vt_WorkPart","SVIt_Social","SVIt_Autonomy","SVIt_Housing",
"SVIt_Financial","SVIt_Total")
    FROM 'D:\Workspace\data\source datasets\sovi\November 2021\csv\sovi_dauid_nov2021.csv'
        WITH 
          DELIMITER AS ','
          CSV HEADER ;



-- transfer DA values to SA table, export from qgis to csv
DROP TABLE IF EXISTS sovi.sovi_sauid_nov2021 CASCADE;

-- create table
CREATE TABLE sovi.sovi_sauid_nov2021 AS
(
SELECT
a."Sauid" AS "sauid",
a."E_SauidLon" AS "lat",
a."E_SauidLat" AS "lon",
a.dauid ,
a.fsauid,
a.csduid,
a.csdname,
a.cduid,
a.cdname,
a.eruid,
a.ername,
a.pruid,
a.prname,
a.sactype,
a.saccode,
a."Et_BldgNum" AS "BldgNum",
a."Et_AssetValue" AS "CostAsset",
a."Et_BldgValue" AS "CostBldg",
a."Et_PopDay" AS "PopDay",
a."Et_PopNight" AS "PopNight",
a."Et_PopTransit" AS "PopTrnst",
a."E_LandUse" AS "LandUse",
b."AgeGT65",
b."Vn_AgeGT65",
b."Vt_AgeGT65",
b."AgeLT6",
b."Vn_AgeLT6",
b."Vt_AgeLT6",
b."AgeMedian",
b."Vn_AgeMedian",
b."Vt_AgeMedian",
b."FamGT5",
b."Vn_FamGT5",
b."Vt_FamGT5",
b."Health",
b."Vn_Health",
b."Vt_Health",
b."ImmLT5",
b."Vn_ImmLT5",
b."Vt_ImmLT5",
b."IncEmpl",
b."Vn_IncEmpl",
b."Vt_IncEmpl",
b."IncHshld",
b."Vn_IncHshld",
b."Vt_IncHshld",
b."IncInd",
b."Vn_IncInd",
b."Vt_IncInd",
b."IncLowdec",
b."Vn_IncLowDec",
b."Vt_IncLowDec",
b."Indigenous",
b."Vn_Indigenous",
b."Vt_Indigenous",
b."LiveAlone",
b."Vn_LivAlone",
b."Vt_LivAlone",
b."LonPar3Kids",
b."Vn_LonPar3Kids",
b."Vt_LonPar3Kids",
b."MntnAge",
b."Vn_MntnAge",
b."Vt_MntnAge",
b."MovedLT1",
b."Vn_MovedLT1",
b."Vt_MovedLT1",
b."NoEngFr",
b."Vn_NoEngFr",
b."Vt_NoEngFr",
b."NonResHa",
b."Vn_NonResHa",
b."Vt_NonResHa",
b."NoSecEd",
b."Vn_NoSecEd",
b."Vt_NoSecEd",
b."NoWrkPlace",
b."Vn_NoWrkPlace",
b."Vt_NoWrkPlace",
b."NSuitHouse",
b."Vn_NSuitHouse",
b."Vt_NSuitHouse",
b."OneIncHshld",
b."Vn_OneIncHshld",
b."Vt_OneIncHshld",
b."PopHa",
b."Vn_PopHa",
b."Vt_PopHa",
b."Pre1975",
b."Vn_Pre1975",
b."Vt_Pre1975",
b."PubTrans",
b."Vn_PubTrans",
b."Vt_PubTrans",
b."Renter",
b."Vn_Renter",
b."Vt_Renter",
b."Retail",
b."Vn_Retail",
b."Vt_Retail",
b."ShltrGT30",
b."Vn_ShltrGT30",
b."Vt_ShltrGT30",
b."Unemployed",
b."Vn_Unemployed",
b."Vt_Unemployed",
b."VisMinority",
b."Vn_VisMinority",
b."Vt_VisMinority",
b."WorkNone",
b."Vn_WorkNone",
b."Vt_WorkNone",
b."WorkPart",
b."Vn_WorkPart",
b."Vt_WorkPart",
b."SVIt_Social",
b."SVIt_Autonomy",
b."SVIt_Housing",
b."SVIt_Financial",
b."SVIt_Total" 

FROM results_nhsl_physical_exposure.nhsl_physical_exposure_indicators_s a
LEFT JOIN sovi.sovi_dauid_nov2021 b ON a.dauid = b."DAUID"
);


-- load in new sovi sauid source table nov 2021
DROP TABLE IF EXISTS sovi.sovi_sauid_nov2021 CASCADE;

CREATE TABLE sovi.sovi_sauid_nov2021(
PRIMARY KEY("sauid"),
sauid varchar,
lon float,
lat float,
dauid varchar,
fsauid varchar,
csduid varchar,
csdname varchar,
cduid varchar,
cdname varchar,
eruid varchar,
ername varchar,
pruid varchar,
prname varchar,
sactype varchar,
saccode varchar,
"BldgNum" float,
"CostAsset" float,
"CostBldg" float,
"PopDay" float,
"PopNight" float,
"PopTrnst" float,
"LandUse" varchar,
"AgeGT65" float,
"Vn_AgeGT65" float,
"Vt_AgeGT65" float,
"AgeLT6" float,
"Vn_AgeLT6" float,
"Vt_AgeLT6" float,
"AgeMedian" float,
"Vn_AgeMedian" float,
"Vt_AgeMedian" float,
"FamGT5" float,
"Vn_FamGT5" float,
"Vt_FamGT5" float,
"Health" float,
"Vn_Health" float,
"Vt_Health" float,
"ImmLT5" float,
"Vn_ImmLT5" float,
"Vt_ImmLT5" float,
"IncEmpl" float,
"Vn_IncEmpl" float,
"Vt_IncEmpl" float,
"IncHshld" float,
"Vn_IncHshld" float,
"Vt_IncHshld" float,
"IncInd" float,
"Vn_IncInd" float,
"Vt_IncInd" float,
"IncLowdec" float,
"Vn_IncLowDec" float,
"Vt_IncLowDec" float,
"Indigenous" float,
"Vn_Indigenous" float,
"Vt_Indigenous" float,
"LiveAlone" float,
"Vn_LivAlone" float,
"Vt_LivAlone" float,
"LonPar3Kids" float,
"Vn_LonPar3Kids" float,
"Vt_LonPar3Kids" float,
"MntnAge" float,
"Vn_MntnAge" float,
"Vt_MntnAge" float,
"MovedLT1" float,
"Vn_MovedLT1" float,
"Vt_MovedLT1" float,
"NoEngFr" float,
"Vn_NoEngFr" float,
"Vt_NoEngFr" float,
"NonResHa" float,
"Vn_NonResHa" float,
"Vt_NonResHa" float,
"NoSecEd" float,
"Vn_NoSecEd" float,
"Vt_NoSecEd" float,
"NoWrkPlace" float,
"Vn_NoWrkPlace" float,
"Vt_NoWrkPlace" float,
"NSuitHouse" float,
"Vn_NSuitHouse" float,
"Vt_NSuitHouse" float,
"OneIncHshld" float,
"Vn_OneIncHshld" float,
"Vt_OneIncHshld" float,
"PopHa" float,
"Vn_PopHa" float,
"Vt_PopHa" float,
"Pre1975" float,
"Vn_Pre1975" float,
"Vt_Pre1975" float,
"PubTrans" float,
"Vn_PubTrans" float,
"Vt_PubTrans" float,
"Renter" float,
"Vn_Renter" float,
"Vt_Renter" float,
"Retail" float,
"Vn_Retail" float,
"Vt_Retail" float,
"ShltrGT30" float,
"Vn_ShltrGT30" float,
"Vt_ShltrGT30" float,
"Unemployed" float,
"Vn_Unemployed" float,
"Vt_Unemployed" float,
"VisMinority" float,
"Vn_VisMinority" float,
"Vt_VisMinority" float,
"WorkNone" float,
"Vn_WorkNone" float,
"Vt_WorkNone" float,
"WorkPart" float,
"Vn_WorkPart" float,
"Vt_WorkPart" float,
"SVIt_Social" float,
"SVIt_Autonomy" float,
"SVIt_Housing" float,
"SVIt_Financial" float,
"SVIt_Total" float
);

-- import exposure from csv
COPY sovi.sovi_sauid_nov2021(sauid,lon,lat,dauid,fsauid,csduid,csdname,cduid,cdname,eruid,ername,pruid,prname,sactype,saccode,"BldgNum","CostAsset","CostBldg","PopDay","PopNight","PopTrnst","LandUse","AgeGT65","Vn_AgeGT65","Vt_AgeGT65","AgeLT6","Vn_AgeLT6","Vt_AgeLT6","AgeMedian","Vn_AgeMedian","Vt_AgeMedian",
"FamGT5","Vn_FamGT5","Vt_FamGT5","Health","Vn_Health","Vt_Health","ImmLT5","Vn_ImmLT5","Vt_ImmLT5","IncEmpl","Vn_IncEmpl","Vt_IncEmpl","IncHshld","Vn_IncHshld","Vt_IncHshld","IncInd","Vn_IncInd","Vt_IncInd","IncLowdec",
"Vn_IncLowDec","Vt_IncLowDec","Indigenous","Vn_Indigenous","Vt_Indigenous","LiveAlone","Vn_LivAlone","Vt_LivAlone","LonPar3Kids","Vn_LonPar3Kids","Vt_LonPar3Kids","MntnAge","Vn_MntnAge","Vt_MntnAge","MovedLT1","Vn_MovedLT1",
"Vt_MovedLT1","NoEngFr","Vn_NoEngFr","Vt_NoEngFr","NonResHa","Vn_NonResHa","Vt_NonResHa","NoSecEd","Vn_NoSecEd","Vt_NoSecEd","NoWrkPlace","Vn_NoWrkPlace","Vt_NoWrkPlace","NSuitHouse","Vn_NSuitHouse","Vt_NSuitHouse","OneIncHshld",
"Vn_OneIncHshld","Vt_OneIncHshld","PopHa","Vn_PopHa","Vt_PopHa","Pre1975","Vn_Pre1975","Vt_Pre1975","PubTrans","Vn_PubTrans","Vt_PubTrans","Renter","Vn_Renter","Vt_Renter","Retail","Vn_Retail","Vt_Retail","ShltrGT30","Vn_ShltrGT30",
"Vt_ShltrGT30","Unemployed","Vn_Unemployed","Vt_Unemployed","VisMinority","Vn_VisMinority","Vt_VisMinority","WorkNone","Vn_WorkNone","Vt_WorkNone","WorkPart","Vn_WorkPart","Vt_WorkPart","SVIt_Social","SVIt_Autonomy","SVIt_Housing",
"SVIt_Financial","SVIt_Total")
    FROM 'D:\Workspace\data\source datasets\sovi\November 2021\csv\sovi_sauid_nov2021.csv'
        WITH 
          DELIMITER AS ','
          CSV HEADER ;