COPY (SELECT
a.sauid,
a."MHInt",
a."MHInt_t",
a."BldgNumT_mht",
a."RES_LD_mht",
a."RES_MD_mht",
a."RES_HD_mht",
a."Comm_mht",
a."Ind_mht",
a."Civic_mht",
a."Agr_mht",
b."Wood_mht",
b."Concrete_mht",
b."PreCast_mht",
b."RMasonry_mht",
b."URMasonry_mht",
b."Steel_mht",
b."Manufactured_mht",
b."PreCode_mht",
b."LowCode_mht",
b."ModCode_mht",
b."HiCode_mht",
c."CensusPop_mht",
c."DayPopT_mht",
c."NightPopT_mht",
c."TransitPopT_mht",
c."SF_Hshlds_mht",
c."MF_Hshlds_mht",
d."AssetCostT_mht",
d."BldgCostT_mht",
d."StrCostT_mht",
d."NStrCostT_mht",
d."ContCostT_mht"

FROM results.mh_threat_mh_building_function_view a
INNER JOIN results.mh_threat_mh_building_construction_view b ON a.sauid = b.sauid
INNER JOIN results.mh_threat_mh_people_view c ON a.sauid = c.sauid
INNER JOIN results.mh_threat_mh_assets_view d ON a.sauid = d.sauid)

TO 'D:\workspace\data\v2\Indicators\csv\mh_intensity_view_mh.csv' DELIMITER ',' CSV HEADER;